### ISSUE TITLE
TypeError in AddReservoirConstraintWithActive

### ISSUE THREAD

**Issue by philippegr** [google/or-tools#1001]
The `AddReservoirConstraintWithActive` in Python does not work, it returns a TypeError for `actives` "has type IntVar, but expected one of: int, long". Active should indeed be of type IntVar. 

Below is a simple code to reproduce the bug
 
```
model = cp_model.CpModel()
model.AddReservoirConstraintWithActive(
    [model.NewIntVar(0,10, f'var_{i}') for i in range(3)],
    [2 for _ in range(3)],
    [model.NewBoolVar(f'active+{i}') for i in range(3)],
     0,
     10)
```

**Comment by lperron** [comment]
Yes, this is a bug.

It will be fixed in 7.0.

In the meantime, you can patch the cp_model.py file

model_ct.reservoir.actives.extend([self.GetOrMakeIndex(x) for x in actives])

or build from source.

Thanks for the report.
You can also copy the AddReservoir... code in your file, fix it and use it
until 7.0 is out.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 3 janv. 2019 à 21:09, philippegr <notifications@github.com> a
écrit :
