### ISSUE TITLE
Cannot install or-tools inside virtualenv in MacOS

### ISSUE THREAD

**Issue by julesbacon** [google/or-tools#1042]
Having some issues installing or-tools for python whenever I run:
`running pip install ortools`
as well as everything on the python install [page](https://developers.google.com/optimization/install/python/mac). 

I get the following output:
```
Could not find a version that satisfies the requirement ortools (from versions: )
No matching distribution found for ortools
```

This was all done inside of a virtualenv, on `python 3.7.2`. The OS is `MacOS 10.12.6`

Has anyone encountered the same problem before? What's the best approach?

Thanks for making this awesome software!
Julian

**Comment by lperron** [comment]
I believe we build on 10.13
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le sam. 2 févr. 2019 à 01:17, julesbacon <notifications@github.com> a
écrit :

**Comment by Mizux** [comment]
Binary are generated on a (Google) Mac Pro which is automatically updated (for security concern) to the last MacOS which was the 10.13.
you can see the wheel package in the release https://github.com/google/or-tools/releases/tag/v6.10 contains the macos version in its name.

note: Currently this laptop is in `10.14.2` so next v7.0 should provide prebuilt package for 10.14 MacOS...

PR welcome to provide various MacOS docker container to generate package for severals MacOS version, otherwise we continue to follow the Google approved last MacOS version...

**Comment by julesbacon** [comment]
Thanks for the pointers. I upgraded and it worked. Thanks for providing this great software!
