### ISSUE TITLE
question about unfriendly APIs in VRP

### ISSUE THREAD

**Issue by lihuiknight** [google/or-tools#1043]
Because there is no official API available for python, I should learn or-tools from the provided examples or reading the source code.  Obviously, it's time expensive and inefficient if I just want to check whether this tool is suitable for my problem. So I suggest the authors to improve the API document like other influential tools, such as pytorch, tensorflow.

I list some unclear API when solving the problem of VRP.

```

def distance_callback(from_index, to_index):
	# Convert from routing variable Index to distance matrix NodeIndex.
	from_node = manager.IndexToNode(from_index)
	to_node = manager.IndexToNode(to_index)
	return data['distance_matrix'][from_node][to_node]

callback = distance_callback
transit_callback_index = routing.RegisterTransitCallback(callback)
routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)
```

dimension_name = 'Distance'
routing.AddDimension(
	transit_callback_index,
	0,  # **no slack, difficult to understand this parameter.**
	30000,  # vehicle maximum travel distance
	True,  # start cumul to zero
	dimension_name)

distance_dimension = routing.GetDimensionOrDie(dimension_name)  **# what is the underlying function of this sentence.**
distance_dimension.SetGlobalSpanCostCoefficient(100) **# what is the underlying function of this sentence.**

Some other samples use the following codes to register distance matrix, such as 
```
distance_evaluator = routing.RegisterTransitCallback(partial(create_distance_evaluator(data), manager))
routing.SetArcCostEvaluatorOfAllVehicles(distance_evaluator)
```

Actually, the above two methods usually return different solution despite I use the same optimization method.

**Comment by lperron** [comment]
User guide: on the stable branch
  https://developers.google.com/optimization/routing/

since you are using the beta API:
  https://github.com/google/or-tools/tree/master/ortools/constraint_solver/doc

API: (beta branch)
  https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h

There is nearly a 1 to 1 mapping between the python and the C++ APIs, and the C++ API is fully documented. Unfortunately, the SWIG tool that creates the python wrapper does not transport documentation other.

**Comment by lperron** [comment]
And we now have http://google.github.io/or-tools/python/ortools/constraint_solver/pywrapcp.html#pywrapcp.RoutingModel.GetNumberOfDisjunctions which lists all the available API.
