### ISSUE TITLE
BOP returns worse solutions as optimal

### ISSUE THREAD

**Issue by abeham** [google/or-tools#1080]
I have created a small knapsack example and uploaded it to GitHub. It shows that the BOP solver returns "optimal" solutions that are worse than those found by CBC. The problem solved is a 1024-item single-resource 0-1 Knapsack.

The link to the repo is: https://github.com/abeham/bop_knapsack

**Comment by Mizux** [comment]
Can you put the output of the program ?
https://github.com/abeham/bop_knapsack/blob/master/Knapsack/Program.cs

i.e. 
```sh
dotnet run
....
```

**Comment by abeham** [comment]
Sure, the output is as follows:

```
Using BOP:
result: OPTIMAL
objective: 59775
bound: 59775
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0221 22:39:52.903899 649124 linear_solver.cc:1464] Trying to set an unsupported parameter: 1.
W0221 22:39:52.905897 649124 linear_solver.cc:1464] Trying to set an unsupported parameter: 2.
Using CBC:
result: OPTIMAL
objective: 59780
bound: 59780
```

**Comment by abeham** [comment]
It's also likely that it doesn't respect tolerance parameters. Maybe a status such as "optimal with tolerance" should be included in order to hint that this is not the true optimum.

**Comment by lperron** [comment]
GLPK
Optimal solution:  59846.0
walltime  : 1105 ms

CBC
Optimal solution:  59846.0
walltime  : 45 ms

SCIP
Optimal solution:  59851.0
walltime  : 205 ms

BOP
Optimal solution:  59849.0
walltime  : 202 ms

SAT
Optimal solution:  59851.0
walltime  : 88 ms

So, higher means better solution. The true optimal is 59851.0. SCIP and our SAT solver find it.
All other solvers stop before because the gap is small enough.

**Comment by lperron** [comment]
Note that for all MIP solver, by default it is optimal with tolerance. There is no other meaning of optimal.
