### ISSUE TITLE
Plot the results

### ISSUE THREAD

**Issue by ankitgupta0310** [google/or-tools#1098]
Is there some code somewhere to easily plot the results that are output from the tool? Im using the VRPTW with vehicle constraints on Python. 

Thank you for all the help provided so far.

**Comment by stuarthillary** [comment]
Take a look at this Google Groups thread. It mentions some code available in this repo that may be of help.

**Comment by ankitgupta0310** [comment]
@stuarthillary thanks! Which group though? Can you post a link? That would be very helpful

**Comment by stuarthillary** [comment]
Sorry, I forgot to late the link 
https://groups.google.com/forum/m/#!topic/or-tools-discuss/Cnln-OUwEK4

**Comment by Mizux** [comment]
On Master you can found my dirty python program wihch output on console a  svg.
see: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/doc/routing.md#misc
example: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/doc/vrp.md

otherwise in example/python you have:
https://github.com/google/or-tools/blob/master/examples/python/cvrptw_plot.py
