### ISSUE TITLE
New CBC version 2.10 released

### ISSUE THREAD

**Issue by rlloretb** [google/or-tools#1111]
I just would like to inform that a new major version of CBC solver, 2.10, has been released.
Would you mind adding it as default in or-tools at some point?

**Comment by Mizux** [comment]
I'll try to do it for v7.0 **or** v7.1 probably

**Comment by rlloretb** [comment]
It seems that CBC team is speeding up the release of new versions.
Current version is 2.10.2, where bugs got corrected.
2.10.3 and 2.11 are planned to be released soon.
Can I just use the latest ones or you guys need to modify significant stuff to make them work?

**Comment by Mizux** [comment]
On the Makefile-based build you can use few variable if you want to ship your own version of coin-or
https://github.com/google/or-tools/blob/f3fd201e68cf75b7720ff5c3cadc599a1d02b54b/makefiles/Makefile.third_party.unix.mk#L13-L17
otherwise v7.1 will use this tag
https://github.com/google/or-tools/blob/f3fd201e68cf75b7720ff5c3cadc599a1d02b54b/makefiles/Makefile.third_party.unix.mk#L26-L30

IIRC we only patch `rpath` in order to use it from the build dir and inside the python package etc...

note: For the CMake-based build we would like to move to a coin-or cmake based build instead (I send few PR to coin-or github)

**Comment by rlloretb** [comment]
So every time there is a new version of CBC released, you guys just change the tag, then?

**Comment by lperron** [comment]
in the Makefile.third_party.{unix|win}.mk, in Dependencies.txt and in the
github repo that contains the cmake rules.

But roughly yes.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *Roger Lloret-Batlle <notifications@github.com>
*Date : *ven. 10 mai 2019 à 12:11
*À : *google/or-tools
*Cc : *Laurent Perron, State change

So every time there is a new version of CBC released, you guys just change

**Comment by rlloretb** [comment]
Can you guys add the tags for CBC version 2.10.2 then, for or-tools 7.1 or 7.2?

**Comment by lperron** [comment]
I pushed the change to master yesterday.

*De : *Roger Lloret-Batlle <notifications@github.com>
*Date : *lun. 13 mai 2019 à 06:10
*À : *google/or-tools
*Cc : *Laurent Perron, State change

Can you guys add the tags for CBC version 2.10.2 then, for or-tools 7.1 or
