### ISSUE TITLE
Presolver crash with "Check failed: !DomainIsEmpty(ref)"

### ISSUE THREAD

**Issue by jesenko** [google/or-tools#1136]
On latest master (7.0.6501), this model [proto](https://gist.github.com/jesenko/d7649a08f3d6136bebe3611875a12105) crashes presolver with
<pre>
cp_model_presolve.cc:91] Check failed: !DomainIsEmpty(ref)
</pre>

When using 7.x build from ~2 months ago, solver returned "INFEASIBLE".

Model proto originates from shift scheduling problem; I can also extract relevant python code for constructing model if it will be of any help...

**Comment by lperron** [comment]
Thanks. I can reproduce it from the proto.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 18 mars 2019 à 13:23, Simon Jesenko <notifications@github.com> a
écrit :

**Comment by gregy4** [comment]
I have same problem on build 7.0.6546 that includes the fix but the code in the method was further modified by another commit. My csp-sat problem was without problems executed on previous stable version (6.10). Since csp-sat model is in my case dynamically generated and only in some cases solving fails, I will try to prepare an example for reproduction of a bug.
