### ISSUE TITLE
FlatZinc: -all_solutions switch disables parallel search

### ISSUE THREAD

**Issue by laserbat** [google/or-tools#1208]
If I run

    fzn-or-tools -threads 8 -all_solutions  ./test.fzn

I can clearly see only single core being utilized. This doesn't happen without -all_solutions flag. 
I'm not sure if it's intentional or not.

**Comment by lperron** [comment]
It is intentional if the problem has no objective.
The synchronization needed to implement all solutions in parallel without
duplicates make it not very useful.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le sam. 20 avr. 2019 à 20:10, Olga Ustuzhanina <notifications@github.com> a
écrit :

**Comment by laserbat** [comment]
Thank you for your quick clarification!
