### ISSUE TITLE
Windows: Cannot link cplex

### ISSUE THREAD

**Issue by ryankfrench** [google/or-tools#1248]
When trying to build from source linking CPLEX and make dotnet I get this error:

```
LINK : fatal error LNK1181: cannot open input file 'c:\Program  Files\IBM\ILOG\CPLEX_Studio129\cplex\\cplex.lib'
tools\make.exe: *** [lib/ortools.lib] Error 1181
```
It seems that the cplex.lib file does not exist in that directory. This seems like a similar to #599.  
No one seemed to have an issue after the proposed solution but I dont even have a cplex.lib on my computer and cplex is installed.

There are cplex1290.lib files in "C:\Program Files\CPLEX_Studio129\cplex\lib\x64_windows_vs2017\stat_mdd\cplex1290.lib" but not in the directory defined in Makefile.win.mk: STATIC_CPLEX_LNK = "$(WINDOWS_CPLEX_DIR)\\cplex.lib"

I cannot use the CBC mixed integer solver because it has a bug and finds the wrong solution and claims it's optimal. Looks like it might be a current bug in their source according to their issues tracker. Any help would be appreciated.

**Comment by Mizux** [comment]
related to #1181 to.

CPLEX support is "community" based, since installation of CPLEX on Google machine is forbidden (AFAIK IBM CPLEX wants to scan all your machine/network to avoid piracy)

As you figured out try to change "$(WINDOWS_CPLEX_DIR)\cplex.lib" by "$(WINDOWS_CPLEX_DIR)\cplex1290.lib" in the makefile you build with option `WINDOWS_CPLEX_DIR=C:\Program Files\CPLEX_Studio129\cplex\lib\x64_windows_vs2017\stat_mdd`

note: PR (on master) are welcome

**Comment by ryankfrench** [comment]
What I did was copy all of the .dll files from ..\x64_windows_vs2017\stat_mdd to C:\Program Files\CPLEX_Studio129\cplex because I believe the make file looks for the include directory which is the in the cplex folder and not present in the stat_mdd folder.

But in the end I have it working now.

**Comment by Mizux** [comment]
Ok so I will close it now, don't hesitate if you have any feedback (or PR :wink: ) to share with us.
