### ISSUE TITLE
Specific nodes visited by specific vehicles

### ISSUE THREAD

**Issue by vitalv** [google/or-tools#1258]
Hi,
I'm working on a VRP problem with a few vehicles and a hundred locations.
I'm trying to allow only certain vehicles to certain locations. I have read the comments at:
https://github.com/google/or-tools/issues/334#issuecomment-484781754
and
https://github.com/google/or-tools/issues/1202

But it seems inconsistent in my data.

If I allow only a specific vehicle to visit a specific node like this:
`routing.VehicleVar(manager.NodeToIndex(node_1)).SetValues([-1, first_vehicle])`
The solver instantly finds a solution where `vehicle_1` visits `node_1` 

But if I change the vehicle to visit `node_1` : 
`routing.VehicleVar(manager.NodeToIndex(node_1)).SetValues([-1, last_vehicle])`
 then the solver fails

I'm using time windows at every location but I'm not using any capacity or any other constrains on the vehicles.

If a solution is proven to exist (when using `first_vehicle`) . 
Why can't I set it to `last_vehicle`? 
What am I missing?

Any info is much appreciated. Thanks for the help and for the great library.

**Comment by pardeep632** [comment]
can you try routing.setAllowedVehiclesForIndex(arrayOfAllowedVehicles, index)

**Comment by amih77** [comment]
@vitalv 
Any solution/progress on this one?
https://github.com/google/or-tools/issues/1647
Today I added https://github.com/google/or-tools/issues/1647

**Comment by MarioLeung** [comment]
I encounter the same problem. I try to allow only certain vehicles to certain locations by using routing.setAllowedVehiclesForIndex()
`x = self.manager.NodeToIndex(i)`
`self.routing.SetAllowedVehiclesForIndex([1, 2, 4, 5, 6, 7, 8], x) # remove vehicle 0`

I've tried a number of combination in the domain values, and find that the solver fails only when I remove vehicle 0 in the list. 

I think the issues should be caused by some constraints that reduce search space and removes some feasible solution at the same time (e.g. symmetry breaking constraints). But I'm not sure if it is the case...

**Comment by Mizux** [comment]
@MarioLeung did you make a disjunction on the node to make it optional ? `-1` is here because at the beginning the node is no visited (you can see it a initial state) but at the end in order to have a solution (i.e. solver don't fail) it must be assigned unless it is part of a disjunction
https://github.com/google/or-tools/blob/b4298f709f116de08f490ac2bfe5e295fcc91f40/ortools/constraint_solver/routing.h#L559-L577

**Comment by MarioLeung** [comment]
@Mizux Yes, I forgot to make a disjunction on the node to make it optional. Everything is fine after adding disjunction.
