### ISSUE TITLE
CP-SAT: Minor version removed function

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#1262]
I don't think it is good practice to remove functions like `AddSumConstraint` in a minor release.
The new `AddLinearConstraint` function seems to be more powerful, but maybe marking the old function as deprecated first and removing them in a major release would be nice :)

Nevertheless, keep up the good work and support 👍

**Comment by lperron** [comment]
I know, but I am stretched too thin to maintain multiple code, especially
since internally, we port all user's code.
And frankly, calling it 8.0 would not have helped much, unless you really
want to block update based on version.

What is missing are the full release notes. They will come in soon.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *Phibedy <notifications@github.com>
*Date : *jeu. 9 mai 2019 à 21:07
*À : *google/or-tools
*Cc : *Subscribed

I don't think it is good practice to remove functions like AddSumConstraint

**Comment by Phibedy** [comment]
Ok, good to know, thanks :)

**Comment by Mizux** [comment]
Since at Google they use a monorepo there is no real notion of semantic versioning.
i.e. you break an API you can change all call site/user code and it's OK.

Further more since or-tools is a "software **suite**" while v7.1 have introduce breaking change CP-SAT this is not the case for the LinearSolver or Routing component -> major change for one component is a minor for an other component...
note: we don't have enough human resource to split in true separate component with their own version scheme....

note: You can also look at presentation on the `Live At Head` from abseil-cpp Team -> since it's a mandatory dependencies there are likely to impose their workflow/vision (i.e. no versioning) to all dependents (i.e. or-tools) (and most Google projet in near future ?)...

**Comment by dimiterbak** [comment]
Could you please let me know what function is to replace addLinearSumEqual in Java?

**Comment by lperron** [comment]
https://developers.google.com/optimization/support/release_notes#cp-sat-api-changes

*De : *Dimitar Bakardzhiev <notifications@github.com>
*Date : *dim. 12 mai 2019 à 07:43
*À : *google/or-tools
*Cc : *Laurent Perron, State change

Could you please let me know what function is to replace addLinearSumEqual
