### ISSUE TITLE
min() and max() constructs

### ISSUE THREAD

**Issue by luiscastro193** [google/or-tools#1293]
[In here](https://github.com/google/or-tools/blob/master/ortools/sat/doc/integer_arithmetic.md#limitations) it says that the Python construct sum() is supported, but min() or max() are not.

Why not? How can I emulate them?

**Comment by lperron** [comment]
Because <= and >= returns constraints object and not a Boolean value.
Thus when python scan the array to compute the min or the max, every
comparison returns True (a object is never None), and the result is
unpredictable.

Please use AddMaxEquality() and AddMinEquality.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
