### ISSUE TITLE
non additive capacity Constraint 

### ISSUE THREAD

**Issue by KaramallahG** [google/or-tools#1313]
I'm working on a problem where I want to apply a capacity constraint, but the capacity at each node depend on the previous nodes.  Let me try to explain it with an example
Assuming that we need to visit three nodes **A**, **B** , **C** 

- At **A** we have two products: (p1,p2)
- At **B** we have two products: (p2,p3)
- At **C** we have one product: (p3).
The capacity at each node is computed as the length of the union of all unique products ab to this node:
1. If the route started at A the capacity is defined by the length of the unique products 
 `Len(unique (p1,p2))=2
 

2. Then if we go to B, then the capacity is increased as follows 
 `Len(unique(p1,p2,p2,p3))=3

3. Then at C the capacity does not increase since p3 is already in the set 
`Len(unique(p1,p2,p2,p3,p3))=3

The following example solved all my problems except that point.
> https://github.com/google/or-tools/blob/stable/examples/python/cvrptw_plot.py

any advice will be appreciated.

**Comment by lperron** [comment]
How big is your model?
How do you use the len() after it has been computed ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 30 mai 2019 à 22:34, KaramallahG <notifications@github.com> a
écrit :

**Comment by KaramallahG** [comment]
1- It is routing problem with almost 50 city and 4 vehicles. 
2- Indeed, this is my problem which I could not not solve. At each step the len should be re-computed, so the list of products should be stored during the iterations to be able to recompute it?

**Comment by KaramallahG** [comment]
> How big is your model? How do you use the len() after it has been computed ? Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53 00 Le jeu. 30 mai 2019 à 22:34, KaramallahG <notifications@github.com> a écrit :
> […](#)

1- It is routing problem with almost 50 city and 4 vehicles.
2- Indeed, this is my problem which I could not not solve. At each step the len should be re-computed, so the list of products should be stored during the iterations to be able to recompute it?

**Comment by lperron** [comment]
I meant what are the constraints on this len ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 31 mai 2019 à 10:15, KaramallahG <notifications@github.com> a
écrit :

**Comment by KaramallahG** [comment]
> I meant what are the constraints on this len ? Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53 00 Le ven. 31 mai 2019 à 10:15, KaramallahG <notifications@github.com> a écrit :
> […](#)

It should not exceed a certain given value X
len (    all nodes in a route     ) < X
Thanks for your reply

**Comment by lperron** [comment]
How many different items ? 
what is the value of X ?

Can you send me some data ? (distance matrix, items for each nodes) ?

**Comment by KaramallahG** [comment]
Thanks for reply. Hope this can explain the problem
```
#!/usr/bin/env python3
from six.moves import xrange
from ortools.constraint_solver import pywrapcp
from ortools.constraint_solver import routing_enums_pb2
import random
stops = 20
vehicles = 5
depot = 0

# generate nodes 
products=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n' , 'o', 'p', 'q', 'r', 's', 't', 'u','v', 'w', 'x', 'y', 'z']
nodes={}
for i in range(stops):
    random_number=random.sample([2,3,4],1)[0]
    nodes[i]=random.sample(products, random_number)

def nodes_fn(node1):
    return len(set(node1))

## max cost 
max_cost = 12 # the route cost should not excced this number
    

random.sample(products, 3)
# Create the routing index manager.
manager = pywrapcp.RoutingIndexManager(stops+1, vehicles, depot)

# Create Routing Model.
routing = pywrapcp.RoutingModel(manager)

def distance_callback(from_index, to_index):
    del from_index, to_index
    return 1

transit_callback_index = routing.RegisterTransitCallback(distance_callback)
routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

slack_max = 20
capacity = 20
fix_start_cumul_to_zero = True
name = 'time'
routing.AddDimension(
        transit_callback_index,
        slack_max,
        capacity,
        fix_start_cumul_to_zero,
        name)

time_dimension = routing.GetDimensionOrDie(name)
time_dimension.SetGlobalSpanCostCoefficient(1000)

search_params = pywrapcp.DefaultRoutingSearchParameters()

search_params.log_search = True
search_params.time_limit.seconds = 10
search_params.local_search_metaheuristic = (
        routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH)
assignment = routing.SolveWithParameters(search_params)

def print_solution(manager, routing, assignment):
    """Prints assignment on console"""
    print('Objective: {}'.format(assignment.ObjectiveValue()))
    total_distance = 0
    for vehicle_id in xrange(vehicles):
        index = routing.Start(vehicle_id)
        plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
        distance = 0
        union_elements=[]
        while not routing.IsEnd(index):
            union_elements +=nodes[manager.IndexToNode(min(index,19))]
            plan_output += ' {} -> '.format(manager.IndexToNode(min(index,19)))
            plan_output += ' (cost= {} )'.format(nodes_fn(union_elements))
            previous_index = index
            index = assignment.Value(routing.NextVar(index))
            distance += routing.GetArcCostForVehicle(previous_index, index, vehicle_id)
        plan_output += ' {}\n'.format(manager.IndexToNode(index))
        plan_output += 'Time of the route: {}h\n'.format(distance)
        print(plan_output)
        total_distance += distance
    print('Total Time of all routes: {}h'.format(total_distance))

print_solution(manager, routing, assignment)
```

The output 
```
Objective: 8023
Route for vehicle 0:
 0 ->  (cost= 4 ) 14 ->  (cost= 6 ) 15 ->  (cost= 8 ) 16 ->  (cost= 11 ) 17 ->  (cost= 12 ) 18 ->  (cost= 13 ) 19 ->  (cost= 15 ) 19 ->  (cost= 15 ) 0
Time of the route: 8h

Route for vehicle 1:
 19 ->  (cost= 2 ) 13 ->  (cost= 6 ) 9 ->  (cost= 8 ) 10 ->  (cost= 11 ) 12 ->  (cost= 11 ) 11 ->  (cost= 15 ) 1 ->  (cost= 18 ) 0
Time of the route: 7h

Route for vehicle 2:
 19 ->  (cost= 2 ) 0
Time of the route: 0h

Route for vehicle 3:
 19 ->  (cost= 2 ) 0
Time of the route: 0h

Route for vehicle 4:
 19 ->  (cost= 2 ) 8 ->  (cost= 6 ) 7 ->  (cost= 8 ) 6 ->  (cost= 9 ) 5 ->  (cost= 10 ) 4 ->  (cost= 13 ) 3 ->  (cost= 16 ) 2 ->  (cost= 17 ) 0
Time of the route: 8h

Total Time of all routes: 23h
```
In this example I want to force the total cost to be less than 12

**Comment by lperron** [comment]
total cost == sum of costs of each route ? or max cost of each route ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 3 juin 2019 à 21:01, KaramallahG <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Second question, is the distance matrix realistic ? Or just for the sake of
the example ?

Meaning is it a real delivery problem, or another problem mapped to a vrp
one ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by aliajouz** [comment]
Thanks for reply. I would say it is max cost of each route since the cost increase by adding nodes but not as sum.
Yes, it is real delivery problem, but here I just used dummy example for the distance.

**Comment by KaramallahG** [comment]
Thanks for reply. 
- I would say max cost of each route, since the cost increase by adding nodes but not as a sum.
- Yes, it is real delivery problem, but here I used dummy distance example

**Comment by jmarca** [comment]
staring at your code, I don't think it does what you think it does.

You've set up a time dimension, and call the maximum time value "capacity".

The travel time callback function sets the travel time at 1 for each pair, regardless.  Obviously a toy example, but that is fine.

So at each node, time increases by 1.

But then in your problem output statement you start doing strange things, like calling `nodes_fn` which returns the length of a set made with the argument.  You haven't told the solver to do anything with this information, so you can't expect the output to be anything other than arbitrary.

I ran your code, rewriting your output function to be:

```python
def print_solution2(manager, routing, assignment):
    """Prints assignment on console"""
    print('Objective: {}'.format(assignment.ObjectiveValue()))
    total_distance = 0
    time_dimension = routing.GetDimensionOrDie('time')
    for vehicle_id in xrange(vehicles):
        index = routing.Start(vehicle_id)
        plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
        distance = 0
        while not routing.IsEnd(index):
            time_var = time_dimension.CumulVar(index)
            plan_output += ' {} -> '.format(manager.IndexToNode(index))
            plan_output += ' (time= {} )'.format(assignment.Value(time_var))
            previous_index = index
            index = assignment.Value(routing.NextVar(index))
            distance += routing.GetArcCostForVehicle(previous_index, index, vehicle_id)
        plan_output += ' {}\n'.format(manager.IndexToNode(index))
        plan_output += 'Time of the route: {}h\n'.format(distance)
        print(plan_output)
        total_distance += distance
    print('Total Time of all routes: {}h'.format(total_distance))
```

The output looks like:

```
Objective: 8023
Route for vehicle 0:
 0 ->  (time= 0 ) 14 ->  (time= 1 ) 15 ->  (time= 2 ) 16 ->  (time= 3 ) 17 ->  (time= 4 ) 18 ->  (time= 5 ) 19 ->  (time= 6 ) 20 ->  (time= 7 ) 0
Time of the route: 8h

Route for vehicle 1:
 0 ->  (time= 0 ) 13 ->  (time= 1 ) 9 ->  (time= 2 ) 10 ->  (time= 3 ) 12 ->  (time= 4 ) 11 ->  (time= 5 ) 1 ->  (time= 6 ) 0
Time of the route: 7h

Route for vehicle 2:
 0 ->  (time= 0 ) 0
Time of the route: 0h

Route for vehicle 3:
 0 ->  (time= 0 ) 0
Time of the route: 0h

Route for vehicle 4:
 0 ->  (time= 0 ) 8 ->  (time= 1 ) 7 ->  (time= 2 ) 6 ->  (time= 3 ) 5 ->  (time= 4 ) 4 ->  (time= 5 ) 3 ->  (time= 6 ) 2 ->  (time= 7 ) 0
Time of the route: 8h

Total Time of all routes: 23h
```

So in this case, the time horizon of 20 is respected for each vehicle, as each route caps out at 8 hrs.  And of course, the actual problem relating to products at nodes not reported because the solver doesn't care about that.

Because I can never debug things with random numbers thrown in the mix, I replaced your random node generator with the first run, namely:

```python
nodes={0:['q', 'w', 'o'],
       1:['l', 'j', 's'],
       2:['a', 'f', 'x', 'q'],
       3:['f', 'z', 'p'],
       4:['y', 'l', 'c', 'v'],
       5:['g', 'p', 'd'],
       6:['m', 'h'],
       7:['q', 'h', 'l'],
       8:['o', 'z', 'c'],
       9:['i', 't', 'f'],
       10:['x', 'q'],
       11:['p', 'g', 'v', 'i'],
       12:['u', 'k', 'q', 'x'],
       13:['f', 'y', 'm', 'c'],
       14:['n', 't', 'u'],
       15:['v', 'm', 'k'],
       16:['i', 'e'],
       17:['d', 'h', 'm'],
       18:['r', 'n', 'a', 's'],
       19:['w', 'x', 'y']
}
```
which, when `union`ed and `sorted`, produces a list:
```
['a', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
```
(only 'b' seems to be missing).

My interpretation of what you want is you're looking for a maximum number of unique items on each vehicle.  You haven't said exactly what this capacity should be, but from the comment in the code, I'm going to assume you want at most 12 unique items per vehicle.

Here's where it gets really tricky, AND where I'm going to stop for a moment and let you respond before I do anything more.  The problem is you're asking for the capacity (how much more is loaded into the vehicle at some node `i`) to be dependent upon all prior nodes that were visited by the vehicle.  By just sticking with one dimension to model vehicle load, this cannot be done.

Consider 0, 1, and 2 from above, where 0 has ['q', 'w', 'o'], 1 has ['l', 'j', 's'], and 2 has ['a', 'f', 'x', 'q'].  Visit to 0 picks up 3 items, a visit to 1 picks up 3 items and a visit to 2 picks up 4.  But instead, you want the pickup to be state dependent, so after visiting 0, a subsequent visit to 2 will only add 3 more items to the vehicle's load.  Correct?

The problem is you don't get much information at all in the demand callback.  In fact, you just get the node itself.   The solver also just collects integers, so you don't even get 'a', 'c', etc, you just get the running sum of numbers, so even if you use C++ and get access to the state-dependent transit callbacks, you still can't do what you want with just one dimension.  The dimension callback does not get to know what vehicle is being used, nor what nodes have come before that node in the vehicle's trip.

It isn't full stop; rather you have to figure out a clever hack.  What I would do is define one dimension per unique load type. This can get quite large, and might blow up the complexity.  In this case 26 dimensions (one per unique letter in the alphabet).  Then each node supplies 0 or 1 in each dimension, depending on what products it has that need to be collected.  What I can't see clearly is how to specify your max load criteria.  Perhaps setting a global constraint for each vehicle at the final depot node, such that no more than "max value" of these dimensions can be non-zero.

**Comment by KaramallahG** [comment]
Thank you for your response. Each node can contain more than 100 different elements, so I'll first try grouping them into smaller groups, and then I'll try your method. Is it possible to post the complete code?
Many Thanks

**Comment by jmarca** [comment]
I'd say just try it with all the products first.  If it fails it fails, but the solver often surprises me that it can handle what I think are complex constraints fairly easily.  If it doesn't work, then you can try combining products.

The code is mostly what you posted, with minor additions as follows:

First you need a function generator for use with each dimension.  I did it this way, but probably cleaner to use partial from functools.  It is also ugly in that it uses the global `nodes` object, but whatever.

```python
def demand_fn_gen(dim,manager):
    def closure(index):
        node = manager.IndexToNode(index)
        # should probably check to make sure node is in nodes too...
        if dim in nodes[node]:
            return 1
        return 0
    return closure
```

Then set up each dimension in a loop.  The loop calls the function generator for each dimension to get the right evaluator.  Again, the dimension is collecting product names, and the evaluator takes a node and returns whether or not (0,1) there is similarly named product on offer there.  Also, I collect the dimensions in the loop.  Again, bad use of globals, but you'll fix that in production, right?

```python
product_dimensions = []
for p in products:
    dimname = 'dim_'+p
    p_callback = demand_fn_gen(p,manager)
    p_callback_index = routing.RegisterUnaryTransitCallback(p_callback)
    routing.AddDimension(
        p_callback_index, # same "cost" evaluator as above
        0,  # No slack
        max_cost,  # at most max_cost pickups of this dimension
        True, # set to zero for each vehicle
        dimname)
    _D = routing.GetDimensionOrDie(dimname)
    product_dimensions.append(_D)
```

That goes above the constraints I posted earlier.  Otherwise same as your code.

Oh, I also added a few lines and a print statement to your output, mostly just to prove it was working:

```python
    time_dimension = routing.GetDimensionOrDie('time')
    ...
        while not routing.IsEnd(index):
            time_var = time_dimension.CumulVar(index)
            union_elements += nodes[manager.IndexToNode(index)]
            print(union_elements,sorted(set(union_elements)))
            plan_output += ' {} -> '.format(manager.IndexToNode(index))
            plan_output += ' (time= {} )'.format(assignment.Value(time_var))
            plan_output += ' (cost= {} )'.format(nodes_fn(union_elements))
   ...
```

Also, you're initial bit of code was off by one---you should not have any demand at the depot node

```python
nodes={0:[]}
for i in range(1,stops+1):
    random_number=random.sample([2,3,4],1)[0]
    nodes[i]=random.sample(products, random_number)
```

**Comment by KaramallahG** [comment]
Thanks for your reply. I will test it
