### ISSUE TITLE
Couldn't get test_dotnet to work with SCIP

### ISSUE THREAD

**Issue by TornadoJo** [google/or-tools#1343]
Hi!

Currently, tools\make third_party cc dotnet runs fine!

When trying tools\make test_dotnet I get an error that the dll can not be found.

Appending the tools\make detect_all test_dotnet - log file with some additional information of the system: [test_dotnet.log](https://github.com/google/or-tools/files/3276535/test_dotnet.log)

After some work I got it to work with v7.0 before - hmm. Maybe it's just the heat around here^^ but what am I doing wrong now? Any help very much appreciated!

PS: The same result with Gurobi810

**Comment by lperron** [comment]
Just pushed and tested SCIP support for windows.

Use the vs2015 64 bit installer for scip 6.0.1

install it somewhere (preferably without any space in the name, otherwise use DOS names, aka c:\progra~1\SCIPOP~1.1 on my laptop).

Add <scipdir>\bin to the path

define WINDOWS_SCIP_DIR=<scipdir> in Makefile.local

recompile and test with tools\make run SOURCE=examples\dotnet\csintegerprogramming.cs

It worked for me.

**Comment by TornadoJo** [comment]
Of course u r exactly right!

Once everything is configured correctly ->rebuild everything from scratch, SCIP6.01, OR-Tools 7.1, adding bin to path...^^ - works like a charm!

Tests are running through meanwhile! - All this is awesome!

Thanks!
