### ISSUE TITLE
Force all vehicles to visit atleast one node in VPR

### ISSUE THREAD

**Issue by vedantlodha** [google/or-tools#1351]
Is there any way to force all vehicles to visit at least one node in VRP ?

**Comment by jmarca** [comment]
Well,  first of all in general you cannot guarantee this...what if there are more vehicles than nodes that need visiting?  

With that caveat, I think you can do it anyway and just pay a penalty if there are extra vehicles.  The guts of my idea (in python)

```python
# set up a counting dimension that increments by one for each node visited, then
# constrain vehicle end node ...
for veh in range(0, num_veh):
    index_end = routing.End(veh)
    count_dimension.SetCumulVarSoftLowerBound(index_end,
                                              2,
                                              100000)
```

This *should* work because the counting node will increase by one with each node visited.  Since every vehicle at a minimum visits the depot (count 0) and the return to depot node (count 1), by setting the soft lower bound at 2, the solver *should* try to make every vehicle visit one node if possible.

I have a blog post with more details on how I set up counting dimension, etc.  See https://activimetrics.com/blog/ortools/counting_dimension/

**Comment by vedantlodha** [comment]
Hi,
I fixed it by forbidding each vehicle to return immediately to its ending depot.
 
```
for vehicle_number in range (data['num_vehicles']):
    start_var = routing.NextVar(routing.Start(vehicle_number))
    for node_index in range (routing.Size(), routing.Size()+routing.vehicles()):
        start_var.RemoveValue(node_index)
            
```

**Comment by jmarca** [comment]
I think that will fail if you have more vehicles than locations to visit, so be careful. 

Also, I think the correct way to grab the vehicle’s destination index is routing.End(vehicle_number). Not so safe to rely on the current implementation detail that vehicle destination nodes are numbered as you have there. Then you can just remove the one destination from each start location. 

Otherwise, clever hack!  

My two cents,

James

**Comment by lperron** [comment]
This is generally a bad idea to add min values to cumul vars.
You can easily run into infeasible problems. It would be better to constraint the max number of visits per vehicle.

If you want to model fairness, it should be reflected in the objective, not in hard constraints.
