### ISSUE TITLE
pkg-conf with cmake

### ISSUE THREAD

**Issue by akstrfn** [google/or-tools#1412]
Hi, while making [or-tools package](https://aur.archlinux.org/packages/or-tools/) for ArchLinux I've hit a few problems which I managed to solve.

0. I'm using CMake based build because pure Make based build was not great for packaging. Building all depencendies did not work because protobuf cmake config was not found (I did not debug this), so I used system libraries from ArchLinux.  

1. The main problem is that most of or-tools dependencies in ArchLinux are built with autotools hence there is no cmake config file. I've patched or-tools cmake files to add workaround for this which I'll put at the end of the message.  
Patch summary: in the main CMakeLists.txt forcing building of all dependencies was turned off. In cpp.cmake file pkg-conf is used to find packages and alias targets were added to fake cmake config.

2. The pkg-conf <-> cmake issue could probably be solved by adding e.g. FindProtobuf.cmake and checking if there is cmake config file and if not fallback on pkg-config.

3. I didn't quite understand is why force building of all dependencies if only one is turned on? Currently abseil is still not in good shape for packaging since they still haven't pinned the release with updated cmake, so I wanted to build abseil with or-tools (its a static link anyway). @Mizux should be more familiar  than me with abseil situation since I believe that he wrote majority of cmake for abseil.

4. With my current patch the build fails for python saying that it is missing cmake file in examples/python but I didn't really bother with this, if you are interested in a followup let me know.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 29357c1dc..cd28cd365 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -44,28 +44,17 @@ message(STATUS "Build .Net: ${BUILD_DOTNET}")
 # IF building any wrapper THEN Force BUILD_DEPS=ON
 # IF BUILD_DEPS=ON THEN Force all BUILD_*=ON
 include(CMakeDependentOption)
-CMAKE_DEPENDENT_OPTION(BUILD_DEPS "Force re-build of all dependencies" OFF
-  "NOT BUILD_PYTHON; NOT BUILD_JAVA; NOT BUILD_DOTNET" ON)
-CMAKE_DEPENDENT_OPTION(BUILD_ZLIB "Build the ZLIB dependency Library" OFF
-  "NOT BUILD_DEPS" ON)
-CMAKE_DEPENDENT_OPTION(BUILD_absl "Build the abseil-cpp dependency Library" OFF
-  "NOT BUILD_DEPS" ON)
-CMAKE_DEPENDENT_OPTION(BUILD_gflags "Build the gflags dependency Library" OFF
-  "NOT BUILD_DEPS" ON)
-CMAKE_DEPENDENT_OPTION(BUILD_glog "Build the glog dependency Library" OFF
-  "NOT BUILD_DEPS" ON)
-CMAKE_DEPENDENT_OPTION(BUILD_Protobuf "Build the Protobuf dependency Library" OFF
-  "NOT BUILD_DEPS" ON)
-CMAKE_DEPENDENT_OPTION(BUILD_CoinUtils "Build the CoinUtils dependency Library" OFF
-  "NOT BUILD_DEPS" ON)
-CMAKE_DEPENDENT_OPTION(BUILD_Osi "Build the Osi dependency Library" OFF
-  "NOT BUILD_DEPS" ON)
-CMAKE_DEPENDENT_OPTION(BUILD_Clp "Build the Clp dependency Library" OFF
-  "NOT BUILD_DEPS" ON)
-CMAKE_DEPENDENT_OPTION(BUILD_Cgl "Build the Cgl dependency Library" OFF
-  "NOT BUILD_DEPS" ON)
-CMAKE_DEPENDENT_OPTION(BUILD_Cbc "Build the Cbc dependency Library" OFF
-  "NOT BUILD_DEPS" ON)
+option(BUILD_DEPS "Force re-build of all dependencies" OFF)
+option(BUILD_ZLIB "Build the ZLIB dependency Library" OFF)
+option(BUILD_absl "Build the abseil-cpp dependency Library" OFF)
+option(BUILD_gflags "Build the gflags dependency Library" OFF)
+option(BUILD_glog "Build the glog dependency Library" OFF)
+option(BUILD_Protobuf "Build the Protobuf dependency Library" OFF)
+option(BUILD_CoinUtils "Build the CoinUtils dependency Library" OFF)
+option(BUILD_Osi "Build the Osi dependency Library" OFF)
+option(BUILD_Clp "Build the Clp dependency Library" OFF)
+option(BUILD_Cgl "Build the Cgl dependency Library" OFF)
+option(BUILD_Cbc "Build the Cbc dependency Library" OFF)
 
 message(STATUS "Build all dependencies: ${BUILD_DEPS}")
 message(STATUS "Build ZLIB: ${BUILD_ZLIB}")
diff --git a/cmake/cpp.cmake b/cmake/cpp.cmake
index 9097739bc..12e7230b5 100644
--- a/cmake/cpp.cmake
+++ b/cmake/cpp.cmake
@@ -7,6 +7,8 @@ set(CMAKE_THREAD_PREFER_PTHREAD TRUE)
 set(THREAD_PREFER_PTHREAD_FLAG TRUE)
 find_package(Threads REQUIRED)
 
+find_package(PkgConfig REQUIRED)
+
 find_package(ZLIB REQUIRED)
 find_package(absl REQUIRED CONFIG)
 set(GFLAGS_USE_TARGET_NAMESPACE TRUE)
@@ -16,13 +18,26 @@ if(BUILD_gflags)
 else()
   set(GFLAGS_DEP gflags::gflags)
 endif()
-find_package(glog REQUIRED CONFIG)
-find_package(Protobuf REQUIRED CONFIG)
-find_package(CoinUtils REQUIRED CONFIG)
-find_package(Osi REQUIRED CONFIG)
-find_package(Clp REQUIRED CONFIG)
-find_package(Cgl REQUIRED CONFIG)
-find_package(Cbc REQUIRED CONFIG)
+
+pkg_check_modules(GLOG REQUIRED libglog IMPORTED_TARGET GLOBAL)
+add_library(glog::glog ALIAS PkgConfig::GLOG)
+pkg_check_modules(PROTOBUF REQUIRED protobuf IMPORTED_TARGET GLOBAL)
+add_library(protobuf::libprotobuf ALIAS PkgConfig::PROTOBUF)
+
+pkg_check_modules(COINUTILS REQUIRED coinutils IMPORTED_TARGET GLOBAL)
+
+pkg_check_modules(OSI_CBC REQUIRED osi-cbc IMPORTED_TARGET GLOBAL)
+add_library(Coin::OsiCbc ALIAS PkgConfig::OSI_CBC)
+pkg_check_modules(OSI_CLP REQUIRED osi-clp IMPORTED_TARGET GLOBAL)
+add_library(Coin::OsiClp ALIAS PkgConfig::OSI_CLP)
+pkg_check_modules(CLP REQUIRED clp IMPORTED_TARGET GLOBAL)
+add_library(Coin::ClpSolver ALIAS PkgConfig::CLP)
+
+pkg_check_modules(CGL REQUIRED cgl) # not used?
+
+pkg_check_modules(CBC REQUIRED cbc IMPORTED_TARGET GLOBAL)
+add_library(Coin::Cbc ALIAS PkgConfig::CBC)
+add_library(Coin::CbcSolver ALIAS PkgConfig::CBC)
 
 # If wrapper are built, we need to have the install rpath in BINARY_DIR to package
 if(BUILD_PYTHON OR BUILD_JAVA OR BUILD_DOTNET)
@@ -119,6 +134,7 @@ target_link_libraries(${PROJECT_NAME} PUBLIC
   absl::any
   ${GFLAGS_DEP}
   glog::glog
+  # ${GLOG_LIBRARIES}
   protobuf::libprotobuf
   Coin::CbcSolver Coin::OsiCbc Coin::ClpSolver Coin::OsiClp
   Threads::Threads)
@@ -154,12 +170,13 @@ foreach (PROTO_FILE ${proto_files})
   #message(STATUS "protoc src: ${PROTO_SRC}")
   add_custom_command(
     OUTPUT ${PROTO_SRC} ${PROTO_HDR}
-    COMMAND protobuf::protoc
+    # COMMAND protobuf::protoc
+    COMMAND /usr/bin/protoc
     "--proto_path=${PROJECT_SOURCE_DIR}"
     ${PROTO_DIRS}
     "--cpp_out=${PROJECT_BINARY_DIR}"
     ${PROTO_FILE}
-    DEPENDS ${PROTO_FILE} protobuf::protoc
+    DEPENDS ${PROTO_FILE} /usr/bin/protoc
     COMMENT "Running C++ protocol buffer compiler on ${PROTO_FILE}"
     VERBATIM)
   list(APPEND PROTO_HDRS ${PROTO_HDR})
@@ -174,7 +191,8 @@ set_target_properties(${PROJECT_NAME}_proto PROPERTIES CXX_EXTENSIONS OFF)
 target_include_directories(${PROJECT_NAME}_proto PRIVATE
   ${PROJECT_SOURCE_DIR}
   ${PROJECT_BINARY_DIR}
-  $<TARGET_PROPERTY:protobuf::libprotobuf,INTERFACE_INCLUDE_DIRECTORIES>
+  ${PROTOBUF_LIBRARIES}
+  #$<TARGET_PROPERTY:protobuf::libprotobuf,INTERFACE_INCLUDE_DIRECTORIES>
   )
 #target_link_libraries(${PROJECT_NAME}_proto PRIVATE protobuf::libprotobuf)
 add_dependencies(${PROJECT_NAME}_proto protobuf::libprotobuf)
```

**Comment by Mizux** [comment]
First, CMake is (currently was :disappointed:) in work in progress.
To understand where we want to go:
* I need to fix #1200 first
* We want to support two main scenarii:
  1. Be able to package libortools like any distro package library and depending on system for dependencies.
  2. Be able to create **standalone** **native** package for Java (.maven), Python (.whl), .Net (.nupkg) i.e. containing all its dependencies (compiled as static if possible) since most of them don't have a clear specification on native library dependencies management (i.e. out of their scope or usage, not supported).

So my answer should be:

0. Yes, we want to migrate to CMake to provide a "clean" c++ library package
note: currently Make only generate tar.gz archive with C++/Java/.Net together.

1. By default, CMake will:
   1. Only build the C++ part, so
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/CMakeLists.txt#L39-L42
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/CMakeLists.txt#L59-L60
should not change in the foreseeable future.
   2. When **only** building the C++ part, by default, will just use a simple find_package(deps REQUIRED) but it will be the responsibility to the user (i.e. distro maintainer) to provide the right FindXXX.cmake or XXXConfig.cmake to fulfill this command
note: I may add some dumb FindXXX.cmake in cmakedirectory in the future
see:
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/cmake/cpp.cmake#L10-L15
   3. When building **any** Java, Python or .Net, we will force building **all** dependencies (as static) since our first goal is to provide a **standalone native package**.
note: I "may" be open to use also system library in this case but will be done later once we will be feature complete compared to the current Make based build.

2. Yup, all your pkg_* stuff should be moved to cmake/findXXX.cmake
I'll try do it, so don't try to rush on this ;)

3. Don't get it... We only force building all dependencies only if we are building Python, Java or .Net since it reduce the combinatory logic (i.e. maintenance effort).
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/CMakeLists.txt#L59-L60
by default `BUILD_DEPS` is `OFF` (but you can set/force it to `ON` if you want) if `BUILD_JAVA`, or `BUILD_PYTHON` or `BUILD_DOTNET` then it is forced to `ON` (and you can't set/force it to `OFF`), this is why it is written that way...

3bis. Yes currently we pinned the version https://github.com/google/or-tools/blob/f367f394fdab14273a423dac0572bb7254f07b56/cmake/dependencies/CMakeLists.txt#L57
since we need absl::flags and absl::random (these libs were not provided in the last release `20190808` IIRC).

4. it's **Work In Progress**, don't expect it to be stable and working (ed I didn't even remember that I have already started the Python support in OR-Tools :disappointed:).
note: First I do some experiments there: https://github.com/Mizux/cmake-swig then, once it's good I port/integrate it to OR-Tools...  
note2: The built-in UseSWIG.cmake has evolved a lot from between CMake [3.11.4](https://cmake.org/cmake/help/v3.11/module/UseSWIG.html) to [3.13](https://cmake.org/cmake/help/v3.13/module/UseSWIG.html) IIRC, so I guess we will require CMake >= 3.13/3.14 when enabling Java, Python or .Net than trying to support older CMake version (swig naming was ugly etc..).
(ed i'll try to stick to CMake ~3.5/3.8 for the C++ part since it is widely available)
see: https://repology.org/project/cmake/versions

Hope you'll have a better understanding where we are, and where we go...

**Comment by Mizux** [comment]
On master branch, we already depend on `absl::random`:
```sh
grepc -rIin "absl/random" ortools 
ortools/lp_data/permutation.h:17:#include "absl/random/random.h"
ortools/constraint_solver/local_search.cc:27:#include "absl/random/distributions.h"
ortools/constraint_solver/local_search.cc:28:#include "absl/random/random.h"
ortools/constraint_solver/constraint_solver.h:76:#include "absl/random/distributions.h"
ortools/constraint_solver/constraint_solver.h:77:#include "absl/random/random.h"
ortools/base/random.h:20:#include "absl/random/random.h"
ortools/base/BUILD:184:        "@com_google_absl//absl/random",
ortools/sat/BUILD:975:        "@com_google_absl//absl/random",
ortools/sat/util.h:19:#include "absl/random/random.h"
ortools/sat/optimization.cc:27:#include "absl/random/random.h"
ortools/bop/bop_ls.h:34:#include "absl/random/random.h"
```

**Comment by akstrfn** [comment]
I realized that Make is more complete than CMake but it was really hard to work
with hence my use of CMake for aur package. You plan to continue working on
CMake implementation?

I am not sure how it works for Java or .Net but for Python I am sure that
dynamic linking works just fine so no need to make it static i.e. linking other
dynamic libraries from ArchLinux to libortools compiled with Python should
work but I have not done any work to test it.

I have forgotten what I did on this package tbh so if you sort out pkg_* it
would make my life easier since now I need to patch it again in order to work :)

My 3rd point was that I wanted to use system libraries but build Absl IIRC, but
then it turned to be all or nothing so I patched CMake file to allow choosing
what to build and what not to build. Having BUILD_ALL as a convenience is fine
but distro's might not need to build all libraries since some dynamic ones
might work so package maintainers can do the tests and choose what to build.
Not sure if this complicates your work too much?

The Absl mess in the last release of or-tools definitely comes from "living at
head" philosophy which can only work for monolithic code bases but I think
Titus et al. had enough pressure so they at least pin the release now
(situation similar to microsoft-gsl btw). On the other hand FB pins their
libraries weekly which also causes problems.

Pinning a version of absl in aur just for or-tools is possible since I maintain
it but some other package might say that it needs some other commit to be
pinned so I don't think its a good idea. Although nobody uses the package
anyway... I believe that building some libraries that anyway link statically,
such as Absl, is probably the way to go and one of the reasons why no package
actually links Absl aur package.

**Comment by akstrfn** [comment]
Btw congrats on great CMake work on this and other libraries it really makes packaging easier.

**Comment by Mizux** [comment]
@akstrfn  FYI I'm working on it in [mizux/dev](https://github.com/google/or-tools/commits/mizux/dev) branch...

note: By default BUILD_DEPS is ON when any wrappers enabled but you can change it (not forced anymore ;))
note2: and BUILD_DEPS is set to OFF when only building the C++ library (the default)
