### ISSUE TITLE
flatzinc from C#

### ISSUE THREAD

**Issue by amoertlseder** [google/or-tools#1433]
I'm trying to compile and run the csfz project in the Google.OrTools.Examples solution.
Unfortunately it doesn't compile. The namespace Google.OrTools.Flatzinc is not known and therefore all types in this namespace are also unknown.
Any hints?

**Comment by lperron** [comment]
Indeed, I have not maintained this for a long time.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 19 juil. 2019 à 01:41, amoertlseder <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
I have removed support for C# support in fz.

**Comment by amoertlseder** [comment]
In this case you should remove the dotnet example csfz.cs from the Google.OrTools.Examples solution!
Its still in 7.3.

Do you have a suggestion how to run a flatzinc model from C#?

**Comment by lperron** [comment]
I will remove it.

Write a simple wrapper in managed c++, and use it.

Personally, I would use the CpModel API, which is close in spirit, but the
API we developed.

Le mar. 6 août 2019 à 23:46, amoertlseder <notifications@github.com> a
écrit :

**Comment by eosfor** [comment]
Oh wow, that is sad. So is there any way to supply a flatzinc or a minizinc file to the solver via C# now? @lperron

**Comment by lperron** [comment]
This feature has been removed years ago.

**Comment by lperron** [comment]
As I said, write a small wrapper in managed c++.
The biggest problem will be that flatzinc is a text interface. 

You can also system("FZ model.fzn")

**Comment by eosfor** [comment]
Hello @lperron, I understand this. I should also mention that I'm more like a "system engineer" focused on clods and scripting languages, like PowerShell :) I can try to write a wrapper on managed c++, but I need some clues like what to "wrap", some directions, perhaps. Can you help with that? would be really great!

In fact, I'm just trying to "port" a minizinc model into some .NET-based thing so it can be used from PowerShell directly without the necessity to install minizinc, etc. I'm looking at using `z3` or `or-tools`, whatever is easier. I haven't made progress in any of them though, I'm 100% new to the concept of "solvers". However, this would be a preferable way. Maybe it just makes more sense to do it instead of making a wrapper. Maybe you could just point me at c# based example or examples of a model similar to [this](https://github.com/eosfor/z3tests/blob/main/vmCostsCalculation-integer.mzn) so I can try to port it to c# for or-tools.

**Comment by lperron** [comment]
There are some samples in
https://github.com/google/or-tools/tree/stable/ortools/sat/doc and in
https://github.com/google/or-tools/tree/stable/examples/dotnet (the *Sat.cs
examples).
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
