### ISSUE TITLE
Is it possible to use OR Tools to plan for multiple-run cases?

### ISSUE THREAD

**Issue by YooTimmy** [google/or-tools#1451]
For example, we have some export & import orders to be fulfilled. The import & export orders are mainly between 2 locations: Customer A & Port B, but with different time windows planned for delivery.
Is google OR Tools able to handle the planning for multi-run, with the objective to minimize the number of vehicles used? e.g. pick up from A and delivery to B at 9am, then pick up from B and delivery to A at 11am, these 2 orders should be combined into a same vehicle.
Currently based on what I see, seems google OR Tools planning could only visit a single node once per plan. One possible walk-around might be creating duplicate nodes for each transactions, but that seems really inefficient...
Appreciated if any suggestions could be given.

**Comment by jmarca** [comment]
You are correct in both cases.  Yes, the solver can handle multi-run cases like you describe.  And yes, you need to create duplicate nodes for each transaction.  Think of it like a graph that the solver is trying to visit each node.  If you don't let it drop a node (using disjunctions), then it will fail if it cannot visit each node.  But it only visits each node once.  

Obviously the more days you try to schedule at once, the larger the problem becomes as duplicated nodes start to add up.  While it depends on the details, I think you shouldn't have a problem up to 500 nodes, and probably will be okay with up to 1000 nodes or so.  The largest problem I ever ran was 3,000 "real" customers, which translated into 12,000 or so nodes in the model, which took 24 hrs to get to an initial solution.

If you can at all take advantage of natural partitions in your data, then do so.  For example, if you have continuous, non-stop operations 24hrs/7days, then there is no natural break, and you will probably have to set up a rolling planning horizon in order to keep the problem manageable.  However, if the work shuts down every night, or if everybody takes a break at a fixed lunch time, then you can break your problem into smaller problems.

**Comment by YooTimmy** [comment]
Dear jmarca,

Thank you for your comments! I would try to partition the problem as you described first.
