### ISSUE TITLE
Python OR-Tools Linear CBC Solver v7.2 fails to find solution unless SetNumThreads explicitly specified

### ISSUE THREAD

**Issue by klaventall** [google/or-tools#1461]
Running the latest version of OR-Tools (v7.2) with python 3.7.2. A problem I was previously able to solve as FEASIBLE/OPTIMAL with v7.0 now returns an INFEASIBLE solution unless solver.SetNumThreads() is explicitly set. 

Please let me know what other information I can provide. Thanks!

**Comment by lperron** [comment]
What is the number of threads you set it to ?

The interface code has not changed.
The solver version has changed.

So the bug is most likely within CBC.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 29 juil. 2019 à 16:14, klaventall <notifications@github.com> a
écrit :

**Comment by klaventall** [comment]
Strangely, a very high number: 100. Anything less it still fails to solve. However I do not see any effect of the increased thread count when I monitor CPU. Similar to [this issue](https://groups.google.com/forum/#!searchin/or-tools-discuss/SetNumThreads%7Csort:date/or-tools-discuss/TN2kdiSNOoo/T5aFs2YJBAAJ)

**Comment by lperron** [comment]
Most likely a CBC bug.
