### ISSUE TITLE
Do not count duplicate nodes as a separate visit in the vehicle.

### ISSUE THREAD

**Issue by YashSharma79** [google/or-tools#1467]
I use the VehicleRouting from OR Tools for pickups and deliveries(in C#). I want to set the constraint that a vehicle can visit only 3 pickup points at max.This I have been able to do with following:

```
RoutingModel routing = new RoutingModel(manager);
routing.AddConstantDimension(1, 4, false, "maxNodesToVisit");
```

The problem is that there are multiple pickup points which are actually from the same location and I don't want them to be counted as two separate visits in the route.

For example: If there are 3 nodes indexed 1,2,3 and node = 1 is already present in the vehicle and node 2 is being visited by the same vehicle, I do not want this visit to be counted again.

I reckon the approach would be to add capacity dimension which will update the visits. I know which nodeIndexes are actually the same location and if I know which nodes are already present in the vehicle I will decide to increment the visit count or not.

What I need to know is how to find the nodes that a current vehicle has visited? Then I can decide whether to increment the visits count or not.

If there is another approach, that would be great as well.

**Comment by jmarca** [comment]
This is difficult because it is hard to know what nodes a vehicle has visited.  The callback functions only get the from and to node at most, not the vehicle and not its state.  So any solution is going to have to be of the "clever hack" variety. 

An idea I had that is bad and inefficient but might work:  create "gateway" dummy nodes, one per vehicle per real location.  Only these nodes increment the counter.

So if you have 3 vehicles and one location to visit, and that location has 3 pickups, you'd generate three dummy Gateway nodes, GA1, GA2, GA3, and three dummy visit nodes, A1, A2, A3.  Each of the GA nodes can ONLY visit any and all of the A nodes (so remove all other nodes from next node set, or make the travel time to other nodes some large value) but put a constraint on the G nodes such that only vehicle 1 can visit GA1, V2 can visit GA2, and V3 can visit GA3.  Then, when V1 visits GA1, the visit count goes up.  

The problem with this of course is that it means each vehicle only gets one chance to visit the A nodes.  It might be the case, say, that a vehicle is full after visiting A1 and needs to come back after dropping off loads to finish picking up loads from A2, A3.  Maybe that won't be the case. Anyway, it's a start.

**Comment by lperron** [comment]
Agreed, I do not think there are good solutions to this.

Closing the issue. Please reopen if somebody has an idea :-)

**Comment by lperron** [comment]
Sorry, 

instead of using unary callbacks at each node, use a binary callback.

If you are arriving at any of the 3 duplicate nodes from the rest of the graph, increase by 1.
If you are transitioning between duplicate nodes, do not increase the count.

It should solve your problem.
