### ISSUE TITLE
PDPTW with multiple copies of same depot

### ISSUE THREAD

**Issue by filippobistaffa** [google/or-tools#1582]
I'm playing around with some [single-depot PDPTW instances](https://www.sintef.no/projectweb/top/pdptw/li-lim-benchmark/) and I compared the results I get with a corresponding multi-depot formulation with multiple copies of the same original depot location.
In other words, each vehicle corresponds to a "different" depot location (as explained [here](https://developers.google.com/optimization/routing/routing_tasks) under "setting start and end locations for routes", where all these locations are actually copies of the original depot location.
While I usually get the same solution for single and multiple-depot (as I would expect), there are instances in which the solution of the multi-depot version is slightly worse.
Now, I'm aware that the solver does not necessarily return the optimal solution (BTW: is there a way to check whether the solution is optimal or not?), hence it might be that in the multi-depot case I get a sub-optimal solution, i.e., this issue might be not bug-related.
On the other hand, is there a way (e.g., with some solver parameter) to "force" the solver to compute the optimal solution, so as to better compare the solution in both cases?

**Comment by CervEdin** [comment]
CP solvers prove optimality by exhausting the search space. If you set a solution or time-limit, the solution isn't going to be proven optimal. Conversely, you prove optimality by not setting a search-limit and letting the solver exhaust the search space.

In all likelihood, by introducing multiple copies of the depot you decrease performance of that model and you're getting different results because one model is able to perform better within a given search limit.

I haven't used this solver myself but I imagine you simply omit any search limit parameters to prove optimality.

I haven't used the benchmarks you mention either, but it looks like they use 100+ tasks. I wouldn't be surprised if you wouldn't be able to prove optimality in a reasonable timeframe for instances that large.

If you want to verify that the two models are equivalent, I would suggest trimming the instance data down to were you can solve for optimal solutions and verify that the two models get the same optimal solution.

Alternatively, take the solution of either model and plug it into the other to verify that it's still a valid solution under a different viewpoint.
