### ISSUE TITLE
Set Minimal Slack Value

### ISSUE THREAD

**Issue by mslazynski** [google/or-tools#1611]
Similarly to the recently closed #1549, I'm interested in setting a minimal value for slacks in the routing problem (VRPTW). In contrast to the referenced issue, the reason is not to add waiting time, but to give each driver enough time to have a break. I understand, that there are already APIs to consider breaks in the plan, but unfortunately in the considered problem each driver/carrier may have different break policy and planning them ahead of time is out of question. 

What I want to eventually achieve is to force CumulVars' min/max to be different by at least predefined amount of time, e.g. with 1h of required daily break.
At the moment my plans look similar to:
`A (08:00 - 08:15) -> B (11:00 - 11:15) -> C (12:00 - 12:30) -> D (13:00 - 14:00)`
and I would like to make it:
`A (08:00 - 09:00) -> B (11:00 - 12:00) -> D (13:00 - 14:00) -> ...`
(`C` should be assigned to another vehicle because it violates minimal slack for `A` and `B`, `D` is not impacted because there's already 1h of slack).

I've tried to put constraints directly on the Slack variables but it didn't have any impact on the results. The advice on adding required slack to the distance (#1549) doesn't really apply - adding 1h to every distance would in fact make this "emulated slack" at least 1h long, but with every trip this slack would accumulate. After 5 trips I would have 5h of extra slack, while only 1h is needed.

Thank you in advance for your answer.

**Comment by routemegood** [comment]
You need to be careful when adding constraints on the slack variables, because they're not the same as "slack" in an operational research sense. The top of the RoutingDimension documentation page shows how slack variables are implemented: [https://developers.google.com/optimization/reference/constraint_solver/routing/RoutingDimension/](url)

If you were to add a constraint that said the slack was 1 hour for each node, that is equivalent to increasing the transit time by 1 hour in each case. What you really want is exactly one of the transits to have a slack at least the length of your break.

There is a proper way of doing this, using the FixedDurationIntervalVar, which you can find in the example [https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrptw_break.py](url), however there are some issues with this implementation that still need to be resolved. I've managed to get this to work on small-medium sized examples by making all nodes optional (add a disjunction) and set the first solution strategy to ALL_UNPERFORMED.

Hope this helps.
