### ISSUE TITLE
Multiple time windows for vehicle routing problem instance

### ISSUE THREAD

**Issue by tigrandp** [google/or-tools#167]
It is not quite an issue but rather question on usage, just didn't find a place where I could ask this question. Is there a way to provide multiple time windows to vehicle routing problem solver instance ? Currently I am using some heuristics for solving that.

**Comment by DaveCausey** [comment]
There is a solution proposed [here](https://groups.google.com/forum/#!topic/or-tools-discuss/MBq1TcqSQTI) that kind-of works but it breaks the filtered decision builder because it assumes a contiguous domain (min..max) for the time intvars. I got it to work by adding a second filter that checks the full domain. There may be other related problems that I haven't uncovered yet, so be wary of that.

Another possible approach is to duplicate the job and add a disjunction constraint to allow only one of them to be serviced.

**Comment by lperron** [comment]
I have implemented a ForbiddenIntervalCt that takes a list on disjunctive
intervals.
You could use that to constrain the cumul variables of your time dimension
to belong to the desired intervals.



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-03-19 10:54 GMT+01:00 Tigran Hakobyan <notifications@github.com>:

**Comment by tigrandp** [comment]
Thanks @lperron a lot. Where can I take a look on example if such exists, or if not is there any documentation ?

**Comment by SlimBelhaiza** [comment]
Hi Tigran,
We published some papers on vehicle routing problems with multiple time windows.
The first one appeared in Computers & Operations Research in 2014.  The problems needs a procedure to minimize route durations. Methods working on single time windows do not work here.
Good Luck.
Slim Belhaiza

**Comment by furnon** [comment]
BTW since Laurent's email, an example showing how to model multiple time
windows has been added (
https://github.com/google/or-tools/blob/master/examples/cpp/cvrp_disjoint_tw.cc)
and the routing solver has been tuned to perform well on such models.
