### ISSUE TITLE
How to compile static link library

### ISSUE THREAD

**Issue by chenicel** [google/or-tools#1709]
I have encountered some problems with the ortools dynamic link library connected to the bazel project. Now I want to use the static link library link, but the document does not specify how to compile the static link library. Can you provide the compilation method? Thank you!

**Comment by lperron** [comment]
i do not know.

**Comment by Diddlik** [comment]
There are any news how to compile static library?

**Comment by lperron** [comment]
This is a bazel question, not an or-tools one. I do not specify static or
dynamic anywhere.

**Comment by davidhgriffiths** [comment]
I think this is an OR-Tools question as the OR-Tools make files specify the /MD flag.  

I have managed to compile OR-Tools as a static library for windows which does not need the C++ runtime.  Although this should be as simple as changing the /MD and /MDt flags to /MT and /MDt in the makefiles in the folder or-tools/makefiles, it turned out to be very involved because the changes don't work for all the dependencies.  Looking back at my notes I think the steps I took were as follows:

step 1 
tools\make third_party

step 2
In dependencies\sources\zlib1.2.11\win32\makefile.msc change MD to MT, delete install files and make third party again

step 3
edit Makefile.win.mk in the makefiles folder to change MD to MT

and run  tools\make dotnet

step 4
In dependencies\sources\abseil-cpp... \build_cmake

edit CMakeCache to change all the MD  and MDt to MT and MTt

make third party and make dotnet

repeat for gflags and glog and protobuf

step 5
for CBC open the CBC solution file in visual studio and in the C/C++ code generation menu change the Runtime Library setting to Multithreaded /MT (see e.g.  https://helloacm.com/how-to-static-link-vc-runtime-in-visual-c/ )

delete all the obj files in port\obj folder

step 6
make dotnet again

Good luck to anyone trying to repeat this!

**Comment by Mizux** [comment]
Side note: Since CMake 3.15 and CMP0091, by using the CMake based build, it will be easier to select it, thanks to the introduction `CMAKE_MSVC_RUNTIME_LIBRARY`, still need to propagate this flag to ortools and all its dependencies...

**Comment by DiegoJRAleixandre** [comment]
Hi. I would like to compile or-tools statically for unix(linux and macos). Is this possible? 

Thank you

**Comment by Mizux** [comment]
@DiegoJRAleixandre you should use the CMake based build instead, using `-DBUILD_SHARED_LIBS=ON` since we don't force to build static (except on windows)

see:
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/CMakeLists.txt#L63-L64
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/CMakeLists.txt#L76-L78

https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/cmake/cpp.cmake#L6

ref: https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html

**Comment by DiegoJRAleixandre** [comment]
So in order to build the libraries as static in macOS and linux, I should just remove that flag (set it to OFF for UNIX too)? 

Thank you, and pretty new to this so sorry if this are basic questions
