### ISSUE TITLE
Error when updating linear_solver model after solving

### ISSUE THREAD

**Issue by antoniomedrano** [google/or-tools#179]
I'm trying to run a model, then based on the output I want to change some variable and constraints, then re-run the model. When I try to do so, I get the following error printed many many times, and it prematurely breaks out of my for loop:

[17:47:06] src/linear_solver/linear_solver.cc:1241: The model has been changed since the solution was last computed. MPSolverInterface::status_ = 0

Is there a way I can suppress this error? What the proper way for running slight variations on a model numerous times from the same script? I'm using the python interface for or-tools.

**Comment by glennon** [comment]
I'm not really a C++ programmer (and haven't examined the full code closely), but there seems to be a pattern with that particular Interface... All other instances (8 of  them) of the check exist as `CheckSolutionIsSynchronizedAndExists`, but the one on line 1192 (and the one that would relate to your error) is only `CheckSolutionIsSynchronized`. `CheckSolutionIsSynchronized` otherwise is not referenced anywhere else in the code.

**Comment by FrnkVieira** [comment]
@antoniomedrano did you find a solution ?

**Comment by antoniomedrano** [comment]
@FrnkVieira nope. It was a complicated model with lots of dependencies, and I never got around to simplifying it to the point where I could post it here.
