### ISSUE TITLE
global dimension

### ISSUE THREAD

**Issue by PIPIKAI-Sung** [google/or-tools#1842]
SetSpanCostCoefficientForAllVehicles and SetGlobalSpanCostCoefficient really confuse me.Do they have the same function. I have seen the discription of them. It says that the SetGlobalSpanCostCoefficient has an effect on global dimension. What is a global dimension

**Comment by PIPIKAI-Sung** [comment]
could someone help explain the meaning of global dimension and the difference between it and local dimension

**Comment by Mizux** [comment]
SpanCost is the "distance" (start, end) i.e. **per vehicle**, while Global is the distance(min(start), max(end)) among all vehicles.

e.g.
```
v_0: |--2--|
v_1: |--3----|
```
here you have two vehicle `v_0` and `v_1` with span of 2 and 3 respectively since they start at the same time the global span is 3

```
v_0: |  2 |--2--|
v_1: |--3----|
```
here you have two vehicle `v_0` and `v_1` with span of 2 and 3 respectively but `v_0` start at 2 so the global span is start_1 to end_0 so 4

see:
https://github.com/google/or-tools/blob/6755c61315c7bb382a558b27cdff7ea2d5970c9c/ortools/constraint_solver/routing.h#L2115-L2129

**Comment by Mizux** [comment]
you can also see the effect of global cost here: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/doc/VRP.md#vehicle-routing-problem

without GlobalSpan solver will use only one vehicle, while have a GlobalSpan solver will use the four vehicles...

**Comment by PIPIKAI-Sung** [comment]
@Mizux 
Thank you and glad to see your reply. Your explanation makes it easier to understand.  Thanks again
