### ISSUE TITLE
CVRPTW with reload - Solution problem

### ISSUE THREAD

**Issue by AntonisKl** [google/or-tools#1865]
**Version**: The default one that is installed with pip3
**Language**: Python
**Solver**: Routing Solver
**OS**: Ubuntu 19.04

Hello,
I had constructed a dummy example of a CVRPTW problem with vehicles with multiple compartments which I have modeled with or-tools and the solution of the solver was the following:

```
Vehicle 0
Route for vehicle 0:
 0 Load(0), Time(2,2) ->  2 Load(0), Time(11,11) ->  0 Load(0), Time(28,28)
Time of the route: 28min
Distance of the route: 776m
Load of the route: 0

Vehicle 1
Route for vehicle 1:
 0 Load(0), Time(1,1) ->  1 Load(0), Time(7,7) ->  4 Load(8), Time(10,10) ->  3
Load(28), Time(14,14) ->  0 Load(28), Time(27,27)
Time of the route: 27min
Distance of the route: 856m
Load of the route: 28

Vehicle 2
Route for vehicle 2:
 0 Load(0), Time(4,4) ->  0 Load(0), Time(10,10)
Time of the route: 10min
Distance of the route: 0m
Load of the route: 0

Total distance of all routes: 1632m
Total load of all routes: 28
```

Afterwards, I added 3 dummy depots (in matrices's positions 1, 2 and 3) to simulate reloading as per this example: https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrp_reload.py . Also, I updated the required input tables (time matrix, distance matrix, time window matrix, service time matrix and demand/order matrix) to accomodate the 3 new dummy depots. Finally, I added some code to make the 3 new dummy depots disjuctions and to add some loading intervals to each of them.
After the addition of dummy depots, with the input parameters which I have set, the solution should have been identical (in terms of times, visited locations and loads) to the previously mentioned solution because no vehicle should make a stop to the dummy depots as its maximum capacity won't be reached. In other words, with the input data which I have set the dummy depots should be completely ignored and not affect the solution.
However, **(1)** the solution after the addition of dummy depots is different from the previous one. You can see the new solution below:

```
Vehicle 0
Route for vehicle 0:
 0 Load(0), Time(2,2) ->  5 Load(0), Time(11,11) ->  0 Load(0), Time(28,28)
Time of the route: 28min
Distance of the route: 776m
Load of the route: 0

Vehicle 1
Route for vehicle 1:
 0 Load(0), Time(1,1) ->  4 Load(0), Time(9,9) ->  7 Load(8), Time(13,13) ->  0
Load(8), Time(24,24)
Time of the route: 24min
Distance of the route: 742m
Load of the route: 8

Vehicle 2
Route for vehicle 2:
 0 Load(0), Time(4,4) ->  6 Load(0), Time(13,13) ->  0 Load(0), Time(27,27)
Time of the route: 27min
Distance of the route: 696m
Load of the route: 0

Total distance of all routes: 2214m
Total load of all routes: 8
```

Furthermore, **(2)** I noticed that sometimes when the vehicle stops to a location it does not get any load even if its remaining capacity is sufficient and the time constraints (time windows) can be satisfied.

I would be grateful if you could provide me with explanation to both of my observations (**(1)** and **(2)**).

**Comment by Mizux** [comment]
Few questions/answers, but without any code snippet it may difficult to help you:

1. Which first strategy did you use ? some heuristic are nodes order dependent so i could explain why route can be different

2. Did you use the local search ?

3. What was the objective of each solution ?

4. does your disjunctions on dummy depots have a zero penalty ?

5. You point `2)` seems strange to me, vehicle visiting a node have to call all transit callback associate to each Dimension, are you sure of model changes ?
Supposing you have a Load Dimension in the sample `1)` we have the arc 4 -> 3 with a load increase of 20 i.e. the unary load callback (4) should return 20 IMHO. Then in the next sample 4 must be 7 according to you since you add 3 dummy nodes but this time we have the arc 7 -> 0 with a load increase of 0. so your callback (7) should have returned 20 not 0 IMHO.

Again without source code is difficult to find your issue...

**Comment by AntonisKl** [comment]
My answers:

1. I am using "routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC".
2. I am not using local search.
3. What do you mean exactly?
4. Yes, they have 0 penalty.
5. I just realized that the printing of loads was wrong. So, just ignore my 2nd observation.

**Comment by Mizux** [comment]
Adding node may impact the solver exploration of the solutions space, since you didn't use a local search or try to reach the optimality, it's expected that since first strategy may found a different first solution each time (exploration search space) then you'll add a different assignment...

By 3) I meant the value of the objective in the assignment...

**Comment by luiscarlos27** [comment]
I have a question, because always in the first location to visit the load value is equal to (0)?

Example: 

Vehicle 0
Route for vehicle 0:
 0 Load(0), Time(2,2) ->  5 Load(0), Time(11,11) ->  0 Load(0), Time(28,28)
Time of the route: 28min
Distance of the route: 776m
Load of the route: 0

-> 5 Load(0)

Vehicle 1
Route for vehicle 1:
 0 Load(0), Time(1,1) ->  4 Load(0), Time(9,9) ->  7 Load(8), Time(13,13) ->  0
Load(8), Time(24,24)
Time of the route: 24min
Distance of the route: 742m
Load of the route: 8

->4 Load(0)
