### ISSUE TITLE
GetOrMakeIndex with negated booleans

### ISSUE THREAD

**Issue by DominikRoB** [google/or-tools#1870]
Version: Version: 7.5.7466 
Language: Python
Solver: CP-SAT
OS: Windows 10

I tried to use model.AddMaxEquality(…) with a negated variable ( varA.not() ) and a list of boolean variables to model that varA is True only if all of the boolean variables are False.

From the documentation I expected that GetOrMakeIndex can handle negated variables,
but I receive a TypeError, NotSupported: model.GetOrMakeIndex(not(varA))

**Comment by lperron** [comment]
This is the intended behavior. Negated Booleans are not valid in integer constraints (with the exception of linear constraints if you use the API).

The reason is that I do not know if the semantics of not(x) is -x or 1 - x in that case.
If all your variables are Boolean, use bool_or and implications instead of MaxEquality.

for all literals:
  literals implies target
bool_or([literal1.Not(), .., literaln.Not(), target.Not())  # target.Not() implies all literals are false.
