### ISSUE TITLE
Google.OrTools v7.6.7691 Issue with VS 2019

### ISSUE THREAD

**Issue by Aghlara** [google/or-tools#1983]
Hi there,

I have issues referencing Google.OrTools v7.6.7691 in VS 2019 in project .Net Core 2.1.

![image](https://user-images.githubusercontent.com/5187409/80432166-be2bc400-8936-11ea-8084-79d2a78be900.png)

How can I resolve this issue?

Thanks,

**Comment by ptr1120** [comment]
This issue seems to be due to the missing target file for netstandard2.0 in the or-tools google.ortools.runtime.win-x64.7.6.7691 NuGet package.
![Capture](https://user-images.githubusercontent.com/582627/80791478-0bf03880-8b92-11ea-9ef4-acb0abe37d1e.PNG)

**Comment by zplan** [comment]
Same probleme here with .Net Core 3.1:

warning NU1701: Package 'Google.OrTools.runtime.win-x64 7.6.7691' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

**Comment by CervEdin** [comment]
NuGet is just warning you that the package is compiled using .net framework but you're using .net core.

**Comment by Mizux** [comment]
Strange, it should contain net45, netstandard2.0 and netstandard2.1 instead...

Need to check why...

**Comment by Mizux** [comment]
I'll try to suppress net45 and the .target file to be sure netstandard2.0/2.1 is working as expected and not silently fallback on the net45 stuff...

**Comment by awonihlgard** [comment]
Any news on this? Facing the same issue on all releases after 7.5.

**Comment by Gilbert2010** [comment]
Is this just a warning message or potentially affect the performance of CP-SAT?  Got the same message but my program using CP-SAT still runs and the results seem correct.

**Comment by lperron** [comment]
No, it is a mismatch between the .NET framework we build for (.net 4.5.2,
dotnet core 2.0, dotnet 2.1) and what is specified by default in visual
studio projects.

It should not affect anything.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 10 sept. 2020 à 23:06, Gilbert2010 <notifications@github.com> a
écrit :

**Comment by Gilbert2010** [comment]
That's great. Thanks, Laurent.

**Comment by adomass** [comment]
We get same issue even though when restoring package --runtime linux-x64 is set

warning NU1701: Package 'Google.OrTools.runtime.win-x64 7.8.7959' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

**Comment by lperron** [comment]
On the linux platform, we do not build net frameworks, only net core.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by adomass** [comment]
Why is win-x64 restored if there is package https://www.nuget.org/packages/Google.OrTools.runtime.linux-x64/ Shoudnt this package be restored when using linux-x64 runtime?
And why do we get this warning?

**Comment by Mizux** [comment]
our meta package Google.OrTools depends on three runtime package, and at runtime the correct libraries are loaded.
if you want only one runtime, you can rebuild from source since only runtime will be detected the meta package will only depend on it
see: https://github.com/google/or-tools/blob/a0a56698ba8fd07b7f84aee4fc45d891a8cd9828/ortools/dotnet/Google.OrTools/Google.OrTools.csproj.in#L73-L88

for full explaination, please read:
 https://github.com/Mizux/dotnet-native/blob/master/README.md
then
https://github.com/google/or-tools/blob/stable/cmake/doc/dotnet.md

**Comment by Mizux** [comment]
now all packages target netstandard2.0 and netstandard2.1 TFM so application targeting netcoreapp3.1 or netcoreapp2.1 should catch it, unfortunately it seems VIsual Studio do weird things.
Please note we are not using VS but only dev,test,use the dotnet-sdk i.e. the dotnet-cli

**Comment by PauliusLe** [comment]
We are getting same warning using dotnet cli, inside linux container. It's not VS specific issue.

**Comment by despair3435** [comment]
@Mizux Would it be possible to also add .NET 5 as target framework? It tries to restore with .NET framework if .NET 5 is the target framework currently:

```
Package 'Google.OrTools.runtime.win-x64 8.1.8487' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
```

**Comment by lperron** [comment]
This is just a warning and is very likely not problematic at all as the
surface API used by or-tools is minimal.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 8 févr. 2021 à 11:30, despair3435 <notifications@github.com> a
écrit :

**Comment by despair3435** [comment]
@lperron Yes, everything works as intended, that is not the issue. It is more about getting rid of the warning. As I treat warnings as errors in my project I now have to make an exception for this warning.

**Comment by Mizux** [comment]
https://github.com/google/or-tools/issues/2207#issuecomment-716515367

**Comment by Mizux** [comment]
> @Mizux Would it be possible to also add .NET 5 as target framework? It tries to restore with .NET framework if .NET 5 is the target framework currently:
> 
> ```
> Package 'Google.OrTools.runtime.win-x64 8.1.8487' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
> ```

FYI: We should provide net5.0 since last release v9.1
