### ISSUE TITLE
GLOP returns an ABNORMAL status code

### ISSUE THREAD

**Issue by snedeljkovic** [google/or-tools#1986]
**What version of OR-tools and what language are you using?**
Version: 7.6.7691
Language: Python 3.6.9

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLOP

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18.04.3 LTS
The model is run on Google Colab.

**What did you do?**
I ran the attached model with GLOP.

**What did you expect to see**
I expected GLOP to solve the model. CLP solves the model just fine.

**What did you see instead?**
GLOP returns an ABNORMAL status code.

Here is the failing model:
[model_lp.zip](https://github.com/google/or-tools/files/4549205/model_lp.zip)

I'm being frustrated by GLOP and BOP throughout the latest releases. Especially BOP seems to fail often and inexplicably. I suspect that something may have been broken on the LP side of things a couple of releases back. For example this model is painfully simple yet I get an ABNORMAL status.

**Comment by lperron** [comment]
1) I do not like the language. GLOP is much more pedantic than CLP w.r.t. numerical precision. So perfectly fine may be relative. 

2) BOP code has not changed in ~2 years.

**Comment by lperron** [comment]
Can you attach the model in mps format ?

**Comment by snedeljkovic** [comment]
@lperron Sorry, I didn't mean to be rude. I was just frustrated. To make amends I changed the title a bit. How can I export the model as mps?

**Comment by lperron** [comment]
So most likely, the solution error exceeds the allowed precision of the checker.

But when I run on master (no changes from 7.6), I get this: 

 ./bin/solve  --input ~/Work/support/issue1986.mps
File        : '/Users/lperron/Work/support/issue1986.mps'
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0429 17:38:02.596122 299015616 solve.cc:136] Failed to set number of threads due to: SetNumThreads() not supported by Glop-0.0.. Using 1 as default.
Solver      : GLOP_LINEAR_PROGRAMMING
Dimension   : 952 x 32
I0429 17:38:02.606174 299015616 solve.cc:227] Verifying the solution
Status      : MPSOLVER_OPTIMAL
Objective   : 1.364219149428259e+00
BestBound   :             inf
Iterations  : 84
Time        : 0.006881

**Comment by snedeljkovic** [comment]
@lperron Thank you very much for having a look at it. From the log you posted it seems that the objective is correct. Unfortunately I don't know how to access such a log from python (I'm running the code in a notebook). How should I proceed using the python API? Is this a bug or a feature? Can I configure the checker from within Python?
