### ISSUE TITLE
Update Java to Java 11

### ISSUE THREAD

**Issue by lperron** [google/or-tools#2079]
Java 8 will not receive any new security update. We should switch all our builds/deliveries to Java 11.

Todo list
* [ ] Makefile java.mk to update
* [ ] CMakelists.txt to update
  * [ ] Maven pom.xml to update
* [ ] CI(make): Bump Java in Dockerfile
* [ ] CI(cmake): Bump Java in Dockerfile
* [ ] Tools(docker): Update Java in Dockerfile
* [ ] CI: Update travis jobs
* [ ] CI: Update appveyor jobs
* [ ] CI: Update github workflow jobs

ref: https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by gregy4** [comment]
Since I investigated possibility to move to java 11 few months ago, I can give you some comments.

A lot of java libraries is not ready for java8+, even Oracle itself modified libraries months after release of java11.

Java11 is lts version, supported by Oracle for 3 years that means until September 2021 without some extended support.

Other companies like Redhat (one of major player in openjdk) for example have different roadmaps.
              https://access.redhat.com/articles/1299013
At this time, support for java8 should end in 2026 and java11 in 2024.

My recommendation is to currently release java code with java8 compatibility, for example in maven should be specified not only "target" but also "release" to guarantee api compatibility. And check whether there are some problems with java11 or java14. I think that or-tools use only swig library that claims no problems with new java versions.

**Comment by Mizux** [comment]
Currently we use:
https://github.com/google/or-tools/blob/45770b833997f827d322e929b1ed4781c4e60d44/ortools/java/pom-local.xml.in#L51-L55

But I should replace it by:
```java
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.0</version>
    <configuration>
        <release>11</release>
    </configuration>
</plugin>
```

JDK 11 use "Release" parameter instead of source/target.

IIRC SWIG is very conservative so it should generate wrapper to be compatible to java 8.

**Comment by gregy4** [comment]
Unfortunately produced bytecode will not be compatible with java8 thanks release 11 and there’s a risk that some new language feature will be used in java part.
When you specify source, target and release to java8, you can compile and run it with java8 and java11. Only downside is that you cannot use new language features of java11 and some “hidden” packages like sun.* will be visible. Highly probably not problem in or-tools java code.

**Comment by Mizux** [comment]
Even when specifying `-target` and `-source` you can't be sure it will work since code can still use recent implementation
see: http://openjdk.java.net/jeps/247

Currently we are facing this bug in Fedora Docker CI (Make and CMake)
see:
* Docker Make (fedora, java) https://github.com/google/or-tools/runs/1449059456?check_suite_focus=true
* Docker CMake (fedora, java) https://github.com/google/or-tools/runs/1449059746?check_suite_focus=true

BUT I suspect, it is some of our dependency in our Pom.xml to depend on Java 9+ without knowing it...
note: It seems, "someone" depend on `java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer`

Otherwise SWIG should generate Java 6 compatible code but since we are using custom `%typemap` we may depends on a more recent Java JDK (ed JDK 8 ?).
