### ISSUE TITLE
CVRP start from any nodes (without depot) and visit the remaining points , end routing in depot

### ISSUE THREAD

**Issue by Khixinhxan** [google/or-tools#2108]
**What language and solver does this apply to?**
Python. Routing, Linear Solver

**Describe the problem you are trying to solve.**
I'm having new problem. I want to find plan for routing, start from any nodes (without depot), visit the remaining points , end route in depot.
I'm using constraint as demand and capacity, distance, time window
I tried test setting start and end in RoutingIndexManager, refer by 
[https://developers.google.com/optimization/routing/routing_tasks#setting-start-and-end-locations-for-routes]

Example : 
list_nodes = [1,2,3,4,5]
depot = 0

RoutingIndexManager(
            5,
            4,
            [1,2,4],
            [0,0,0]
        ) 
So I had some results
First route: 1 -> 3 -> 0 
Second route: 2 -> 5 -> 0

But result is missed the case : routing 4->0
The weights of node 4 may seem large, so not combine with other nodes, but it is actually possible to satisfy for routing 4 -> 0
I think AddDisjunction is affected, I tried setting value is 0 or value is very large but solution still ignore node 4 !

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mizux** [comment]
Please use the mailing list !

* 0 + [1,2,3,4,5] == 6 nodes
* why did you set 4 a vehicle number but give two list of size 3 ?

Otherwise to start from "any" location simply in you distance matrix set the distance from start to any location as 0, it will simulate this behaviour and simply don't print the start node in your print function...
