### ISSUE TITLE
C++ use own pre-built multi-threaded CBC libs on Windows

### ISSUE THREAD

**Issue by iainfullelove** [google/or-tools#2226]
**What language and solver does this apply to?**
C++ / linear solver / CBC (COIN OR)

**Describe the problem you are trying to solve.**
I am currently using or-tools in a larger C++ CMake project on Windows (MSVC) - the CMake integration as it is works great. I am currently just using the provided single-threaded CBC solver that comes with or-tools to run basic models. However, I was interested in trying to build and provide to or-tools a multi-threaded version of CBC for Windows.

I have pre-built all the C++ COIN OR libs (.lib files with associated headers) on Windows (with CBC multi-threaded) using the CMakeLists available from AMPL CBC build repository (https://github.com/ampl/coin). I was just wanting to see whether there is any easy way to integrate these pre-built libs into the current or-tools CMake setup? Or alternatively, use a CBC dll with an or-tools binary that are both built using the same C++ build tools for compatibility?

**Comment by Mizux** [comment]
Easy no, doable yes.
First, you can disable the built of COIN-OR using these options
https://github.com/google/or-tools/blob/84c35244c9bdd635609af703bbf3053c16c487c0/CMakeLists.txt#L175-L197
warning: you must keep `USE_COINOR=ON` otherwise ortools will be built without the support.

then later we expect to find a cbc-config.cmake file
https://github.com/google/or-tools/blob/84c35244c9bdd635609af703bbf3053c16c487c0/cmake/cpp.cmake#L70-L92

So you have to provide a CMake config file for Cbc with the corresponding targets  etc. **OR** patch the cmake build at your convenience...
