### ISSUE TITLE
google tools can not be installed from source following the instructions 

### ISSUE THREAD

**Issue by jiadongwang** [google/or-tools#2238]
By following the instruction on installing or-tools from source , 

Installing OR-Tools on your operating system
You can install OR-Tools for C++ on your operating system by entering

tools\make install_cc

![image](https://user-images.githubusercontent.com/6073489/99679583-ba31d180-2a41-11eb-856b-530c5d34a3b1.png)

**Comment by lperron** [comment]
It may have trouble supporting paths with spaces.
Can you try with the dos name (progra~1) ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 19 nov. 2020 à 15:32, Jiadong Wang <notifications@github.com> a
écrit :

**Comment by brunodema** [comment]
This might be late already, but I identified that the build process - either using [cmake C++](https://github.com/google/or-tools/blob/stable/cmake/doc/cpp.md) or the steps (described on the official website)[https://developers.google.com/optimization/install/cpp/source_windows] have problems with paths containing spaces (the or-tools path). Since I am in Brazil, the %DESKTOP% path contains both spaces and special symbols ('Área de Trabalho'). 

In my case, I got errors while following the steps described in the official documentation (I do not remember which ones anymore), so I went straight for the Cmake C++ steps. I managed to run the initial Cmake command with no problems, but the build identified problems when building the 'prototools-src' dependency (something related to a relative path). After I changed the 'or-tools' location to 'C:\', everything went smoothly. I used version 8.1 for this, but this probably applies to the latest branches.
