### ISSUE TITLE
Different number of solutions on different OS with same code

### ISSUE THREAD

**Issue by ankane** [google/or-tools#2340]
**What version of OR-tools and what language are you using?**
Version: v8.1
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)** CP-SAT

**What operating system (Linux, Windows, ...) and version?** Ubuntu 18.04, Mac 10.15, Windows 2019

**What did you do?**

Ran the [wedding_optimal_chart_sat.py](https://github.com/google/or-tools/blob/stable/examples/python/wedding_optimal_chart_sat.py) example.

**What did you expect to see**

The same solutions on Linux, Mac, and Windows.

**What did you see instead?**

The same solutions on Mac and Windows (4 total), but there are 7 solutions on Linux.

Here's the output for each OS: https://github.com/ankane/ortools_repro/runs/1705791567?check_suite_focus=true

**Comment by lperron** [comment]
Sorry, but we rely on system libraries for randomization for instance.

We will have a look, but most likely, there is nothing we can do.

Thanks for the report.

**Comment by Mizux** [comment]
At least all reach the objective 214 and must respect all constraints so they are equivalent from the solver point of view...

Also it's a NP hard problem so, usually, you can't just brute force to have all solutions BUT need to use some smart heuristics, logic etc to minimize the exploration or at least make it efficient and as Laurent said sometime you need few random values to choose which solution search space to explore first etc and in this case the solutions found by the solver may diverge since the random generator is platform dependent.

**Comment by ankane** [comment]
Hey @Mizux and @lperron, thanks for the helpful explanation. Will close this out since it's expected. I appreciate the responses.

**Comment by RashidBakirov** [comment]
Hello,
I have the similar experience while evaluating a same piece of code on my local Windows machine and cloud Databricks instance, however the number of evaluated solutions is quite noticeably different, about 20 on the local machine and >200 on Databricks. Depending on the number of workers, sometimes both do converge to the same solution. Additionally, Databricks search seems to get stuck at some point and never stops. Could that be expected behaviour? I am using Python with OR-tools 9.5.2237 Happy to provide more details if needed.

**Comment by lperron** [comment]
Yes, numerical precision depends on the machine/compiler.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 1 mars 2023 à 19:31, RashidBakirov ***@***.***> a
écrit :
