### ISSUE TITLE
Routing Flags not working on python

### ISSUE THREAD

**Issue by acrogenesis** [google/or-tools#235]
In the example of cvrptw https://github.com/google/or-tools/blob/master/examples/python/cvrptw_plot.py#L641 you suggest we can change the lsp flag like this `parameters.no_lns = False` but I get the error `'RoutingSearchParameters' object has no attribute 'no_lns'`
This happens with every flag. ej. `no_tsp`

**Comment by mjfwest** [comment]
I think the flags and parameters were changed in bb6e091027eee3c88b855fbf67775be10f00c16f.   I can't really find any documentation on how you are supposed to set parameters, but the edit below seems to work for me.   I am even less sure about what is the default behaviour, and the rational behind setting various local search operators.  I will open a pull request if I hear this is a good enough example on how the parameters should be set, otherwise I will suggest a pull request removing the offending comments.

```python
    parameters = routing.DefaultSearchParameters()

    # Setting first solution heuristic (cheapest addition).
    parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)
    # Disabling Large Neighborhood Search, ( I think this is the default behaviour)
    parameters.local_search_operators.use_path_lns = False
    parameters.local_search_operators.use_inactive_lns = False
    # Routing: forbids use of TSPOpt neighborhood, 
    parameters.local_search_operators.use_tsp_opt = False

    parameters.time_limit_ms = 10 * 1000  # 10 seconds
    parameters.use_light_propagation = False
    # To log the search uncomment the following.
    # parameters.log_search = True 
```

**Comment by dlahlou** [comment]
Hello,
Since or-tools is using protobuf, you can find the parameters in .proto files. for example, routing parameters are defined in [routing_parameters.proto](https://github.com/google/or-tools/blob/master/src/constraint_solver/routing_parameters.proto) and constraint solver parameters in [solver_parameters.proto](https://github.com/google/or-tools/blob/master/src/constraint_solver/solver_parameters.proto)
As @mjfwest mentioned, you can set use_path_lns parameter like so : `parameters.local_search_operators.use_path_lns = False`
Please note that `local_search_operators` is instantiated [here](https://github.com/google/or-tools/blob/master/src/constraint_solver/routing_parameters.proto#L209).
I agree that the use of parameters should be documented, and we will work on this as soon as possible, so I will close this issue, and open another one about documentation.
Regards,
Driss

**Comment by pratcurve** [comment]
What exactly is the benefit of disabling lns?
