### ISSUE TITLE
How to export or print the mathematical model (java)

### ISSUE THREAD

**Issue by EkaterinaAlekseeva** [google/or-tools#237]
I would like to get the final mathematical model used by a solver.
My code for CVRP is written in java. I have found ModelVisitor method but I have not succeed using it. Is there any other command or how could I export or print the model?

**Comment by dlahlou** [comment]
Hello,

The [protobuf](https://developers.google.com/protocol-buffers/docs/overview) parameter [print_model](https://github.com/google/or-tools/blob/master/src/constraint_solver/solver_parameters.proto#L83) allows to print the model. It is defined in ConstraintSolverParameters, which is settable within RoutingModel since it is instantiated in [RoutingModelParameters](https://github.com/google/or-tools/blob/master/src/constraint_solver/routing_parameters.proto#L280).

In java, you can do this like so :

```
import com.google.ortools.constraintsolver.RoutingModelParameters;
import com.google.ortools.constraintsolver.ConstraintSolverParameters;
import com.google.ortools.constraintsolver.Solver;

...
   
ConstraintSolverParameters constraint_solver_parameters =
  ConstraintSolverParameters.newBuilder()
  .mergeFrom(Solver.defaultSolverParameters()) // using defaultSolverParameters is mandatory 
  .setPrintModel(true) // sets print_model to true
  .build();

RoutingModelParameters model_parameters =
  RoutingModelParameters.newBuilder()
  .mergeFrom(RoutingModel.defaultModelParameters())
  .mergeSolverParameters(constraint_solver_parameters)
  .build();

RoutingModel routing = new RoutingModel(size, 1, model_parameters);
```

I hope this helps.

Regards,

Driss
