### ISSUE TITLE
routing: gives bad solutions for hamiltonian path problems

### ISSUE THREAD

**Issue by willangley** [google/or-tools#247]
Skiena's _The Algorithm Design Manual_ gives a reduction from Hamiltonian Cycle problems to Traveling Salesman: assign a weight of 1 to edges that are present in the graph, and a weight > 1 to edges that are not present.

I haven't figured out how to get the ortools routing library to work reliably with this reduction though; it often produces routes that :
- don't use the configured start and end points
- go through edges of high weight
- and don't visit all the vertices in the graph

when configured as in the `tsp.py` example.  I.e. the below program will work if the vehicle starts and ends at 0, but will break in all of the above ways if the vehicle starts at 0 and ends at 1.

`hamiltonian_path_routing.py`

``` python
import sys

from ortools.constraint_solver import pywrapcp
from ortools.constraint_solver import routing_enums_pb2

ROWS = 2
COLS = 2

def Distance(i, j):
  y1, x1 = divmod(i, ROWS)  
  y2, x2 = divmod(j, ROWS)
  return abs(y2 - y1) + abs(x2 - x1)


def main():
  start = int(sys.argv[1])
  end = int(sys.argv[2])

  routing = pywrapcp.RoutingModel(ROWS * COLS, 1, [start], [end])
  search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters()
  search_parameters.first_solution_strategy = (
    routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)

  routing.SetArcCostEvaluatorOfAllVehicles(Distance)
  assignment = routing.Solve()
  if assignment:
    print assignment.ObjectiveValue()

    route_number = 0
    node = routing.Start(route_number)
    route = ''
    while not routing.IsEnd(node):
      route += str(node) + ' -> '
      node = assignment.Value(routing.NextVar(node))
    route += '0'
    print(route)

  else:
    print 'No solution found.'

if __name__ == '__main__':
  main()
```

```
(macOS) Aule% python hamiltonian_path_routing.py 0 0
4
0 -> 2 -> 3 -> 1 -> 0
(macOS) Aule% python hamiltonian_path_routing.py 0 1
3
0 -> 1 -> 2 -> 0
(macOS) Aule% 
```

I am a Google engineer, and should be within the Guidelines for contributing already if this turns out to be helpful test code.

**Comment by furnon** [comment]
You are displaying variable values, not node ones. To get nodes, call
IndexToNode like this:
route = ''
while not routing.IsEnd(node):
  route += str(routing.IndexToNode(node)) + ' -> '
  node = assignment.Value(routing.NextVar(node))
route += routing.IndexToNode(node)
print(route)

It turns out that when start,end are 0, node and IndexToNode(node) are
equal.

Hope this helps,
Vincent

On Sep 11, 2016 5:13 PM, "Will Angley" <notifications@github.com> wrote:

Skiena's *The Algorithm Design Manual* gives a reduction from Hamiltonian
Cycle problems to Traveling Salesman: assign a weight of 1 to edges that
are present in the graph, and a weight > 1 to edges that are not present.

I haven't figured out how to get the ortools routing library to work
reliably with this reduction though; it often produces routes that :

   - don't use the configured start and end points
   - go through edges of high weight
   - and don't visit all the vertices in the graph

when configured as in the tsp.py example. I.e. the below program will work
if the vehicle starts and ends at 0, but will break in all of the above
ways if the vehicle starts at 0 and ends at 1.

hamiltonian_path_routing.py

import sys
from ortools.constraint_solver import pywrapcpfrom
ortools.constraint_solver import routing_enums_pb2
ROWS = 2COLS = 2
def Distance(i, j):
  y1, x1 = divmod(i, ROWS)
  y2, x2 = divmod(j, ROWS)
  return abs(y2 - y1) + abs(x2 - x1)

def main():
  start = int(sys.argv[1])
  end = int(sys.argv[2])

  routing = pywrapcp.RoutingModel(ROWS * COLS, 1, [start], [end])
  search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters()
  search_parameters.first_solution_strategy = (
    routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)

  routing.SetArcCostEvaluatorOfAllVehicles(Distance)
  assignment = routing.Solve()
  if assignment:
    print assignment.ObjectiveValue()

    route_number = 0
    node = routing.Start(route_number)
    route = ''
    while not routing.IsEnd(node):
      route += str(node) + ' -> '
      node = assignment.Value(routing.NextVar(node))
    route += '0'
    print(route)

  else:
    print 'No solution found.'
if __name__ == '__main__':
  main()

(macOS) Aule% python hamiltonian_path_routing.py 0 0
4
0 -> 2 -> 3 -> 1 -> 0
(macOS) Aule% python hamiltonian_path_routing.py 0 1
3
0 -> 1 -> 2 -> 0
(macOS) Aule%

I am a Google engineer, and should be within the Guidelines for
contributing already if this turns out to be helpful test code.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/or-tools/issues/247>, or mute the thread

**Comment by willangley** [comment]
Thanks! Also I thought about my problem a bit longer, and realized that I didn't need routing at all; there's a way to write this so that solver.Circuit is sufficient here.
