### ISSUE TITLE
Vehicle specific precedence constraints

### ISSUE THREAD

**Issue by Gyantoshkumar** [google/or-tools#2682]
Hello,
I am using OR Tools in python to solve the Vehicle Routing Problem. So far I've managed to use successfully many of the available constraints, but I have difficulties dealing with one in particular. It is a kind of precedence constraint, which must be specific for each vehicle. Let's say I've got some nodes, some of which are high priority nodes and others are normal or low priority. The high priority nodes must come first in each vehicle's list of nodes. 

PS: The same discussion happened [here](https://groups.google.com/g/or-tools-discuss/c/HsioeGr8DyA), but I am not able to identify the solution.

Any help or advice is highly appreciated

Best regards

**Comment by Mizux** [comment]
You can:
* use the `routing.NextVar(index)` to prune output arc.
* Add a very high transit cost to avoid any arc from low priority node to high priority ones
i.e. solver will have no other choice but to visit first high priority node since once vehicle visit a low priority node, vehicle is unable to visit a high priority one...

**Comment by Gyantoshkumar** [comment]
Hey  Mizux, Thanks for your reply  !  can you please help me with this same [problem](https://groups.google.com/g/or-tools-discuss/c/Vz4sJtwBM2Q/m/XirUtGPzAwAJ) with more than 1 no of vehicle lets say 2 or 3 . it would be great help .
