### ISSUE TITLE
Solution is dropping orders

### ISSUE THREAD

**Issue by Nyutkarsh** [google/or-tools#294]
What are the constraints which decide to drop orders? 
What is the use of "FirstSolutionStrategy". What type of solution strategy should be used?
I am referring "CapacitatedVehicleRoutingProblemWithTimeWindows.java" to implement the solution.

**Comment by furnon** [comment]
Hi,
Orders can be dropped for two main reasons:
- when the penalty attached to the order is less than the cost of
performing it (due to various travel costs);
- when the problem is over-constrained, "infeasible" orders can be dropped,
or if the infeasibility is due to multiple orders, some of them can be
dropped, while trying to minimize the overall cost; for example this can
happen if the capacity of a vehicle is too low to accept all orders.

FirstSolutionStrategy represents the heuristic used to build a first
solution to the problem, which will then be improved by local search.
Deciding which heuristic to use depends on the problem but in
general PATH_CHEAPEST_ARC or  SAVINGS work well for models which are not
too constrained, otherwise PARALLEL_CHEAPEST_INSERTION works well in
particular if there are pickup and delivery constraints.

Vincent

**Comment by pmateusz** [comment]
@furnon, I found your answer very helpful. You may consider adding sort of FAQ, which will bundle questions/answers like that. Some of questions may remain unanswered, waiting to be answered by the community to save you some work.

**Comment by Mizux** [comment]
Maybe we should rework the https://developers.google.com/optimization/routing/tsp/routing_options so it become a F.A.Q. than just a list of available options...
@orwant What do you think ?
