### ISSUE TITLE
ConsiderEmptyRouteCostsForVehicle not available ?

### ISSUE THREAD

**Issue by petestevens88** [google/or-tools#3241]
**What version of OR-Tools and what language are you using?**
Version: 9.2.9972

Language: Python

**Which solver are you using Routing Solver, 

**What operating system (Linux, Windows, ...) and version?**
windows

**What did you do?**
```py
# Create Routing Model.
routing = pywrapcp.RoutingModel(manager)
         
for vehicle_id in range(data['num_vehicles']):
    routing.ConsiderEmptyRouteCostsForVehicle(True, vehicle_id)
```

**What did you expect to see**

**What did you see instead?**
```
AttributeError: 'RoutingModel' object has no attribute 'ConsiderEmptyRouteCostsForVehicle'
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
v9.1:
https://github.com/google/or-tools/blob/86d4c543f717fa8716a9d66c25143660668bf825/ortools/constraint_solver/routing.h#L1040-L1043

has been removed since v9.2, If i were you I would try

v9.2:
https://github.com/google/or-tools/blob/2cb85b4eead4c38e1c54b48044f92087cf165bce/ortools/constraint_solver/routing.h#L1083-L1086
according to comment
https://github.com/google/or-tools/blob/2cb85b4eead4c38e1c54b48044f92087cf165bce/ortools/constraint_solver/routing.h#L1361-L1366

**Comment by petestevens88** [comment]
That works perfectly. Thank you!!!
