### ISSUE TITLE
`pip install` for tests prefers to download ortools wheel from PyPi 

### ISSUE THREAD

**Issue by StefanBruens** [google/or-tools#3260]
PyPi provides ortools 9.3.10349, which is apparently newer than 9.3.9999.

https://pip.pypa.io/en/stable/cli/pip_install/#finding-packages

For the ortools wheel, the just created version should always be used, so `--no-index` should be added.

https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/cmake/python.cmake#L319

**Comment by Mizux** [comment]
need to double check, I can't remember if adding `--no-index` won't add an issue to fetch dependencies of or-tools.
BTW thanks for the feedback

**Comment by StefanBruens** [comment]
`--no-index` would indeed fail to install any dependencies not yet available. Not sure if this is a good thing, or not - maybe its better anyway to explicitly install any dependencies as part of the CI setup?

Another option is to directly refer to the file instead of using `--find-links` + name, see (8.) and (9.):
https://pip.pypa.io/en/stable/cli/pip_install/#examples
I.e. somthing like `${VENV_Python3_EXECUTABLE} -m pip install ${CMAKE_CURRENT_BINARY_DIR}/python/dist/${PYTHON_PROJECT}.*whl`

**Comment by Mizux** [comment]
IIRC `.*` do not work well on windows `-_-` + in case the folder contains severals .whl files we are doomed (ed should not be the case anymore since we call `cmake -E remove_directory dist` each time)

ref:
https://github.com/google/or-tools/blob/dd29e9c0ae254fb2f79383c2a89ccca26f3dc856/cmake/python.cmake#L310

note: the new code using `ortools==<CMAKE_PROJECT_VERSION_COMPUTED>` should be less sensitive to this...
ref:
https://github.com/google/or-tools/blob/dd29e9c0ae254fb2f79383c2a89ccca26f3dc856/cmake/python.cmake#L379-L380
