### ISSUE TITLE
Add unicode support for windows

### ISSUE THREAD

**Issue by tuanchien** [google/or-tools#3394]
**What language and solver does this apply to?**
or-tools C++ library for windows.

**Describe the problem you are trying to solve.**
Build the library with unicode character set support in windows.  Linking to the MBCS version of or-tools in unicode apps can cause crashes in apps.

**Describe the solution you'd like**
Modify or-tools to handle unicode build configurations. See the error messages below relating to `ortools/base/dynamic_library.h`

**Describe alternatives you've considered**
Mixed linking of MultiByte and unicode libraries in apps. What scant information I've found online seems to suggest this is a can of worms and a bad idea.

Applications that can purely use MultiByte character sets can work around this issue, but this isn't always practical to do. Modern apps mostly target Unicode character sets.

**Additional context**
Versions impacted:
release: 9.3
stable branch at: 49b6301e1e1e231d654d79b6032e79809868a70e

Build system info:
Windows 11
Visual Studio 2022, 17.2.6
Toolset version: vc143
cmake version: 3.22.22040401-MSVC_2

Building or-tools in windows currently produces a Multibyte character set library. Trying to link a unicode app against the Multibyte or-tools library can result in crashes.

I suspect some windows users experiencing crashes who are attempting to link against the provided binary distribution or trying to link against their own compiled versions in Visual Studio projects might be impacted by this issue without realising it.

To attempt to generate a unicode build configuration in MSVC, I added the following to the root CMakeLists.txt:
```
ADD_DEFINITIONS(-DUNICODE)
ADD_DEFINITIONS(-D_UNICODE)
```
This produces a unicode character set config in the vcxproj files produced by cmake.

Build steps:
```
cmake -S . -B build -DBUILD_DEPS=ON
cmake --build build --config Release
```

Compilation fails at the or-tools library with
```
C:\or-tools\ortools/base/dynamic_library.h(49,1): error C2664: 'HMODULE LoadLibraryW(LPCWSTR)': cannot convert argument 1 from 'const _Elem *' to 'LPCWSTR' [C:\or-tools\build\ortools\gurobi\ortools_gurobi.vcxproj]
          with
          [
              _Elem=char
          ]


C:\or-tools\ortools/base/dynamic_library.h(49,72): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast [C:\or-tools\build\ortools\gurobi\ortools_gurobi.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\libloaderapi.h(665,1): message : see declaration of 'LoadLibraryW' [C:\or-tools\build\ortools\gurobi\ortools_gurobi.vcxproj]


C:\ortools/base/dynamic_library.h(49,1): error C2664: 'HMODULE LoadLibraryW(LPCWSTR)': cannot convert argument 1 from 'const _Elem *' to 'LPCWSTR' [C:\or-tools\build\ortools\linear_solver\ortools_linear_solver.vcxproj]
          with
          [
              _Elem=char
          ]
C:\or-tools\ortools/base/dynamic_library.h(49,72): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast [C:\or-tools\build\ortools\linear_solver\ortools_linear_solver.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\libloaderapi.h(665,1): message : see declaration of 'LoadLibraryW' [C:\or-tools\build\ortools\linear_solver\ortools_linear_solver.vcxproj]
  gurobi_proto_solver.cc
C:\or-tools\ortools/base/dynamic_library.h(49,1): error C2664: 'HMODULE LoadLibraryW(LPCWSTR)': cannot convert argument 1 from 'const _Elem *' to 'LPCWSTR' [C:\or-tools\build\ortools\linear_solver\ortools_linear_solver.vcxproj]
          with
          [
              _Elem=char
          ]
C:\or-tools\ortools/base/dynamic_library.h(49,72): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast [C:\or-tools\build\ortools\linear_solver\ortools_linear_solver.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\libloaderapi.h(665,1): message : see declaration of 'LoadLibraryW' [C:\or-tools\build\ortools\linear_solver\ortools_linear_solver.vcxproj]
```

**Comment by Mizux** [comment]
devNote, cureently we are using:
https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/ortools/base/dynamic_library.h#L46-L49
i.e. `LoadLibrary()` take a `LPCSTR` (`const char*` ?)
ref: https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya

But it seems the use of `/DUNICODE` will make a call to `LoadLibraryW()` which use an `LPWSTR`
ref: https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw

>  Note:
The libloaderapi.h header defines LoadLibrary as an alias which automatically selects the ANSI or Unicode version of this function based on the definition of the UNICODE preprocessor constant. Mixing usage of the encoding-neutral alias with code that not encoding-neutral can lead to mismatches that result in compilation or runtime errors. For more information, see Conventions for Function Prototypes.

ref: https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw#examples

So @tuanchien could you try to replace the call `LoadLibrary()` by `LoadLibraryA()` ? since i'm pretty sure gurobi path should not contains any unicode/wchar_t characters...

**Comment by tuanchien** [comment]
@Mizux that suggestion seems to have remedied the compile errors. It doesn't appear to break anything with unicode off either.
