### ISSUE TITLE
Build fails when trying to install or tools from source code for third party solver  (GLPK).

### ISSUE THREAD

**Issue by Sai-Chandar** [google/or-tools#3467]
**What version of OR-Tools and what language are you using?**
Version: main v9.4
Language: C#

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLPK

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
I was following the steps on https://developers.google.com/optimization/install/dotnet/source_windows

**What did you see instead?**

![image](https://user-images.githubusercontent.com/50066371/191854528-e624eafe-53d3-4a43-a346-fbe343a21b67.png)

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

I'm using x64 Native Tools Command prompt for VS 2019 to install the build

**Comment by lperron** [comment]
Could be the space in the path.

Note, GLPK is really not a great solver.

**Comment by Mizux** [comment]
1. Make is very sensitive to space + by default GLPK is not enabled (license issue).
2. If i were you I would try instead to build using the CMake based build (e.d. since v9.3 make is just a wrapper on top of the cmake based build).

You can try, these commands (ed may also work in powershell etc provide you have `cmake` in your path)
```sh
cmake -S. -Bbuild -DBUILD_DOTNET=ON -DUSE_GLPK=ON -DBUILD_GLPK=ON
cmake --build build --config Release -j -v
```
note: this will build my GLPK fork having CMake support
ref: https://github.com/mizux/glpk

then you should have in `build/dotnet/packages` what's your are looking for...

3. Next time, could you provide a "build_log.txt" file with the command and the full trace ?

**Comment by lperron** [comment]
Strangely enough, using CMake to compile with GLPK (-DUSE_GLPK=ON) works partially.
C++ and Python find GLPK.  Java does not.

**Comment by lperron** [comment]
It works on c# for me.
For java, I believe ctest calls maven that downloads the online package.

**Comment by Mizux** [comment]
@lperron try to remove your maven cache `rm -rf ~/.m2`

**Comment by Sai-Chandar** [comment]
Build compiles without any errors when I remove the space in the path.

**Comment by lperron** [comment]
OK. Closing.
