### ISSUE TITLE
Bump to SWIG 4.1.1

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#3519]
Dislaimer: postponed for v9.6

all in the title swig 4.1.1 is out need to update all docker etc..

ref:
https://sourceforge.net/p/swig/news/2022/11/-swig-411-released/
https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.1.1/
https://repology.org/project/swig/badges

**Comment by Mizux** [comment]
Warning: Currently swig 4.1.0 fail to build or-tools seems to fail to parse any declaration using `ABSL_MUST_USE_RESULT`...

**Comment by StefanBruens** [comment]
> Warning: Currently swig 4.1.0 fail to build or-tools seems to fail to parse any declaration using `ABSL_MUST_USE_RESULT`...

ABSL_MUST_USE_RESULT is special as it is set as a compile definition:

https://github.com/google/or-tools/blob/82750ac12f1ee5354e1c7869894d9af3508778f2/ortools/init/python/CMakeLists.txt#L16-L17

I am wondering why this definition is required at all - maybe it was prior to
https://github.com/abseil/abseil-cpp/commit/2a042b082ca6fc8592ec98d800012fc03c965c15#diff-09be45e1f18014e237574dfd11ba4dbe5564e77705c024f46ca80f2180b854b5

The change also added the following note:
> // For code or headers that are assured to only build with C++17 and up, prefer
> // just using the standard `[[nodiscard]]` directly over this macro.

Probably or-tools should just follow this advice. On the other hand, attributes are only supported since Swig 4.1:
https://github.com/swig/swig/issues/2326

**Comment by Mizux** [comment]
Yup, swig parser wasn't able to parse standard attribute so we had to override it to make swig parser happy.
Now, since swig 4.1 support attribute and abseil-cpp change its implementation maybe it's time (post release) to give a try to use the abseil-cpp provided `#define` and remove our "fix"

ps: thx for the link ;)

**Comment by StefanBruens** [comment]
Btw, at least for python the definition is duplicated:
https://github.com/google/or-tools/blob/82750ac12f1ee5354e1c7869894d9af3508778f2/cmake/python.cmake#L175

**Comment by StefanBruens** [comment]
For anyone wondering how to make or-tools-9.4 compatible with SWIG 4.1:
```
find -iname \*CMakeLists.txt -exec sed -i -e '/COMPILE_DEFINITIONS/ s@ABSL_MUST_USE_RESULT@@g' '{}' \;
sed -i -e '/FLAGS/ s@ABSL_MUST_USE_RESULT@ABSL_MUST_USE_RESULT="[[nodiscard]]" @g' cmake/python.cmake
```

The first one should probably applied to or-tools in any case, at it removes the duplicaton of the define. The second one depends on SWIG 4.1.
