### ISSUE TITLE
Conda do not have 9.4v, in Conda the latest is 9.2 

### ISSUE THREAD

**Issue by ZedTDean** [google/or-tools#3521]
https://anaconda.org/conda-forge/ortools-python/labels  has only v9.2 and the links 
https://anaconda.org/conda-forge/ortools-python do not seems to work at all.
Thank you

**Comment by Mizux** [comment]
Please ask/follow here ;)
https://github.com/conda-forge/or-tools-feedstock/pull/23

**Comment by BastianZim** [comment]
Hi @ZedTDean, or-tools is one of the more difficult tools to bring to conda-forge for a variety of reasons so we're currently stuck on updating it to newer versions. If you have any experience, feel free to help out by making a PR.

**Comment by h-vetinari** [comment]
I just merged the [build](https://github.com/conda-forge/or-tools-feedstock/pull/23) for 9.4, which was stuck for a couple of reasons:
1. New dependency on `eigen`
1. A wrongly-named variable (see [here](https://github.com/google/or-tools/issues/3698); not sure how this is actually working in this repo)
1. Issues with the re2-ABI between abseil & non-abseil (since conda-forge is uniformly on abseil's C++17 ABI, we had to [rebuild](https://github.com/conda-forge/re2-feedstock/pull/62) (& [migrate](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4149))  re2 to match that
1. Some issue with swig 4.1 (not present for or-tools 9.5)

All in all, 1. & 4. were easy, 2. & 3. were harder.

I actually tried building 9.3 as well, but couldn't make that work with 2. (e.g. https://github.com/google/or-tools/commit/0d3572bda874ce30b35af161a713ecd1793cd296 only landed for 9.4).

I'll follow up with 9.5 very shortly. Unfortunately the pypy builds are broken ATM, but that's hopefully more niche. Also, there's other things in that recipe I haven't had time to tackle yet (e.g. rebuilding the C++ lib for the python bindings, rather than reusing the one we've just built), aside from more featureful bindings (more solvers). Help & comments are always welcome :)
