### ISSUE TITLE
Hakan Kjellerstrand's Code (examples/contrib) License correct?

### ISSUE THREAD

**Issue by hrieke** [google/or-tools#3874]
Hello,

There appears to be roughly 200+ files with Hakan Kjellerstrand's copyright notice and I am trying to track if he contributed the code to your project, or if the Apache License attribution is correct.
The source code found at [https://github.com/hakank/hakank/blob/master/LICENSE](https://github.com/hakank/hakank/) lists the MIT License as the repository license and the individual files do not contain the Apache License 2.0.
Furthermore, Hakan does not appear to be a contributor to this project (nor an employee of Google or Alphabet).

If there is any information that someone can share on this question, I would be appreciative. 

 Thank you for your attention.

**Comment by hrieke** [comment]
Could not confirm that he contributed the code, and in finding the original source code repo under the MIT License raised a question of which was correct.

**Comment by hrieke** [comment]
Here's the answer:
https://github.com/hakank/hakank/tree/master/google_or_tools
With the proper Apache License 2.0 attribution.

Furthermore, here's his ticket on license usage:
https://github.com/hakank/hakank/issues/7

Finally, even if this just "example" code, it's still his "example" code in your code base.  Please don't belittle someone's question because they're turning over stones and asking questions.

Thank you!

**Comment by lperron** [comment]
I do not belittle :-(
I am just asking what the issue is ? I am really not an expert, the code is
clearly marked as contrib and contains the owner of the code.

I did not add a license to the file as far as I remember, and I am very
grateful for Hakan's contribution.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le lun. 31 juil. 2023 à 10:50, Henry Rieke ***@***.***> a
écrit :
