### ISSUE TITLE
Linker tools error on ortools_full.lib: "int CbcOrClpEnvironmentIndex" (?CbcOrClpEnvironmentIndex@@3HA) already defined

### ISSUE THREAD

**Issue by sarafrim** [google/or-tools#4057]
**What version of OR-Tools and what language are you using?**
Version: v9.8 binaries
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows10
Visual Studio Enterprise 2022

**What did you do?**
1. Installing OR-Tools for C++ from Binary on Windows and run `make test` to make validate the installation.
2. In Visual studio, add the additional include directories and use ortool_full.lib directory to link the project.
3. Build the project (here called MyProj).

**What did you expect to see**
Successful build. 

**What did you see instead?**
`error LNK2005: "int CbcOrClpEnvironmentIndex" (?CbcOrClpEnvironmentIndex@@3HA) already defined in in MyProj.lib(CbcOrClpParam.obj)`

**Anything else we should know about your project / environment**
In the same build log, I also get the error message error `LNK2001: unresolved external symbol "bool __cdecl utf8_range::IsStructurallyValid` as reported in [issue 3888](https://github.com/google/or-tools/issues/3888). A workaround to that is to add utf8_validity.lib into Configuration Properties > Linker > Input > Additional Dependencies.

**Comment by Mizux** [comment]
> 2. In Visual studio, add the additional include directories and use ortool_full.lib directory to link the project.

Wrong you should take a look at the cmake config, you are missing tons of defines, link flags, link libraries etc....

Take a look at this file, if you want to know what you have to setup:
9875  2023-11-14 10:16   or-tools_x64_VisualStudio2022_cpp_v9.8.3296/lib/cmake/ortools/ortoolsTargets.cmake

otherwise you can also start from any CMakeLists.txt included along each examples/

or integrate or-tools in your cmake based build (you can use this template project: https://github.com/or-tools/cmake_or-tools)
tips: take a look at the github windows workflow...
https://github.com/or-tools/cmake_or-tools/actions/runs/7544696400/job/20538613494
