### ISSUE TITLE
Can't install OR-Tools [Help]

### ISSUE THREAD

**Issue by La2g** [google/or-tools#433]
Hi guys, i'm not sure if this is right place for this, so excuse me in advance.

Note: i'm on W8.1 and using python 3.6

I'm trying to install the google OR-Tools for python and i have really been unable to do so, i have tried different methods i have found online, i will outline each and say what's my problem with it.
•The simpler one i have found is just to "pip install", so i go to the command prompt and type: pip install py3-ortools

But i get an error on install "Microsoft Visual C++ 14.0 is required" even tho i have installed it, also 2015 and 2013 i even got visual studio 2017 installed. So i don't know why this doesn't work.

•Next one is following the google guide, so i go to binary distribution and download the "Python Zip" and unpack it. Then it says to: "Open a Visual Studio Native Tools Command Prompt and change directory to ortools_examples. Then enter the following command: make install"
So i open the "Developer Command Prompt for VS 2017" i change the directory to the "ortools_examples" folder and type the "make install" command but i got the error "make" is not recognized as a internar or external command.

•I also tried the instruccion from the README that said to edit the makefile and add a few values to some variables then run it, but it says this:
```
   #Set this variable to use it as PYTHONPATH
    WINDOWS_PYTHONPATH = 
```
And i don't really know what it means to Set the variable to use as PYTHONPATH.

I'm sorry if all this seems stupid, but i spent a whole night trying to figure it out and couldn't get it working any help would be nice, thanks.

**Comment by Jarino** [comment]
Check Programs and features (or Add or remove programs, not sure which one is in W8.1) whether the "Microsoft Visual C++ 14.0" is listed here (which should be I guess, since you installed VS2017). If not, try to download and install the [redistributables directly](https://www.microsoft.com/en-us/download/details.aspx?id=48145) and the try to pip install again (note that maybe restart will be needed).

As for the second method, "Developer Command Prompt for VS2017" is not the same thing as "..Native Tools Command Prompt", look for  "VS2015 x64 Native Tools Command Prompt" or something similar. I also think you have to [install CMake](https://cmake.org/download/), in order to make command work, or use `nmake`, though this probably won't work. 

WINDOWS_PYTHONPATH should be path to folder, where your Python binary is located, you should be able to obtain it in command prompt by typing `where python`.

FYI I also wasn't able to install from binary, nor source by following the instructions in installation guide, so I guess pip install is the way to try.

**Comment by La2g** [comment]
Thanks for the answers. My problem was i had python 3.6 installed instead of 3.5, after i downgraded i was able to pip install the library.

The instructions could be simpler that's for sure.

**Comment by lperron** [comment]
Hi, 

I have delivered or-tools for windows for both python3.5 and 3.6.

see: https://pypi.python.org/pypi?:action=files&name=py3-ortools&version=6.3.4431

Can you try it again?

Thanks

**Comment by BrianGladman** [comment]
Hi, I also tried to install py3-ortools using pip with Python 3.6 and all appeared to go well.  But when I try to run any Python examples, I get this error: 

   "builtins.ModuleNotFoundError: No module named '_pywrapcp'"

It appears that a DLL called _pwrapcp.pyd should exist in the Python36\DLL folder after installation but it is absent.

I would be most grateful for any advice you can offer on how to fix this.  

I should also mention that the binary install documented on the OR-Tools site using Visual Studio 2017 'make install' also fails for me because 'make' is not present (the MS version, nmake,  fails as well).

**Comment by lperron** [comment]
about source install,
make is in tools\make.exe

I do not know about the requirements about the DLL directory.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-09-28 18:28 GMT+02:00 Brian Gladman <notifications@github.com>:

**Comment by BrianGladman** [comment]
Thank you, Laurant, for your rapid response to my query.  Sadly, I have spent a long time on trying to resolve this problem with no success.  As far as I can tell the failure occurs in what is a very complex package import mechanism internal to ortools.    It is clear from a Google search that I am not alone in facing this issue but none of the suggested solutions I have found work for me.

**Comment by lperron** [comment]
I believe (hope) this is fixed in the last release (6.5) I pushed today.
I merged py3-ortools into ortools. So please run

pip3.6 install ortools (after uninstalling py3-ortools).

It works on my machine.

Thanks

**Comment by BrianGladman** [comment]
Laurent, it now works perfectly.   Thank you so much for your work on this, which I much appreciate.

**Comment by hpswalters** [comment]
Laurent,
I too am having an awful time.  I've loaded anaconda with python 3.5 and 3.6 multiple times--no luck.  Loaded plain python 3.5 and python 3.6.1, 3.6.2, 3.6.3--all no luck.  I've cleaned registry entries and repeated the process---.

The message that I keep getting is the "Python version XX required, which was not found in the   registry. " Where is the installer looking in the registry?

**Comment by lperron** [comment]
No idea, are you using pip?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-19 20:08 GMT+00:00 hpswalters <notifications@github.com>:
