### ISSUE TITLE
Failed python_tests from installation from source: constraint_solver/pywrapcp.py

### ISSUE THREAD

**Issue by Peel40** [google/or-tools#434]
Hello, I'm trying to install unsucesfully or-tools from source for a couple of hours now but I'm getting the same problem again and again running the tests... I don't know what to do now :( 

I'm using Ubuntu 16.04.2 LTS, and I followed carefully the instructions from [or-tools](https://developers.google.com/optimization/introduction/installing.html#unix_source) as follows:

```
sudo apt-get install git bison flex python-setuptools python-dev autoconf \
libtool zlib1g-dev texinfo help2man gawk g++ curl texlive cmake subversion
make third_party
make python
make test
make test_python
```

I'm getting this error running the tests

```
swig -I. -c++ -python  -o ortools/gen/ortools/constraint_solver/constraint_solver_python_wrap.cc -module pywrapcp ./ortools/constraint_solver/python/routing.i
make: swig: Command not found
makefiles/Makefile.python.mk:161: recipe for target 'ortools/gen/ortools/constraint_solver/pywrapcp.py' failed
make: *** [ortools/gen/ortools/constraint_solver/pywrapcp.py] Error 127

```

**Comment by lperron** [comment]
you need to install swig

sudo apt-get install swig

We will improve the doc

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-07-19 5:02 GMT-07:00 Omar Francisco <notifications@github.com>:

**Comment by Peel40** [comment]
Problem solved! Thank you very much! :clap:

**Comment by manueltrotta** [comment]
I got the same error after executing the command "make test", because I installed the C++ version only typing "make cc". In [https://developers.google.com/optimization/introduction/installing/source](url) page, it is suggested to test the installation typing "make test", but this command returns lots of errors if you install or-tools for just one language.
Please, update the documentation.
