### ISSUE TITLE
mathopt: Constraints containing empty sets are invalid.

### ISSUE THREAD

**Issue by quantcn** [google/or-tools#4378]
Hi, I'am testing mathopt api. here is my code:

```py
from ortools.math_opt.python import mathopt

model = mathopt.Model(name="Linear programming example")
z = {i: model.add_integer_variable(lb=0.0, name=f"z{i}") for i in range(10)}
A={}
model.add_linear_constraint(sum(z[i] for i in A) <= 5, name="c1")
model.minimize(sum(z.values()))
```

Set A is an empty set. the constraint c1 is valid in `pywraplp` api. But in mathopt is not valid, it reports the following error, I want it to be valid like in pywraplp. In reallife applications, Set A can be evaluted to be an empty set.

```
 File "e:\test.py", line 7, in <module>
    model.add_linear_constraint(sum(z[i] for i in A) <= 5, name="c1")
  File "E:\anaconda3\envs\optim\lib\site-packages\ortools\math_opt\python\model.py", line 1746, in add_linear_constraint
    normalized_inequality = as_normalized_linear_inequality(
  File "E:\anaconda3\envs\optim\lib\site-packages\ortools\math_opt\python\model.py", line 2251, in as_normalized_linear_inequality      
    raise TypeError(
TypeError: unsupported type for bounded_expr argument: bool.
```
This error can occur when trying to add != constraints (which are not supported) or inequalities/equalities with constant left-hand-side and right-hand-side (which are redundant or make a model infeasible).

**Comment by Mizux** [comment]
try to use `expressions.fast_sum`, AFAIK mathop don't reimplement the sum operator `-_-`

**Comment by rma350** [comment]
I agree that you should use fast_sum instead of sum everywhere if possible. This is more efficient and does what you want on the empty list. The sum operation does work when your list is non-empty, as sum just calls +, and + is overloaded.

Or (worse because it is slower, but still correct) you can call sum() with an initial value of an empty linear expression:

`sum(z[i] for i in A, start=math_opt.LinearExpression())`

 so that the output of sum() has type `LinearBase` rather than double (and as a result, the result of the inequality has type `UpperBoundedLinearExpression` instead of `bool`).

MathOpt choose to not accept bool here (there was much debate about this, we may change the behavior eventually, but it is not happening any time soon). Why did we do this? First, this is protecting you from a mistake if you accidentally return the wrong thing, rather than just silently adding a cosntraint that always succeeds or always fails.

Second, there is not any reasonable behavior for us here on incrementalism/reading back the constraint/adding more coefficients. If you wrote the code

```
c = model.add_linear_constraint(sum([]) <= 5, name="c1")
c.upper_bound
```

you want to get 5 back, but we cannot give this to you, as all we see from your constraint is a bool. Further, if you go on to modify this constraint, by setting more coefficients of variables, you could think you have a real constraint, but we have lost the upper bound, so we can't really recover from this.
