### ISSUE TITLE
How to use metaheuristics from OR-tools in python? 

### ISSUE THREAD

**Issue by teresalopezchagoya** [google/or-tools#455]
Hi! 

Currently I am working on the CVRPTW using the file pywrapcp to solve a Routing Problem with a huge
amount of customers. 
What i need to do is: 

1) Use the Output of the first solution strategy: search_parameters as Input  to the local_search_metaheuristic and improve on it. 

In some groups I have read they only use two lines:

> search_parameters.first_solution_strategy =
> (routing_enums_pb2.FirstSolutionStrategy.PARALLEL_CHEAPEST_INSERTION)
> 
> search_parameters.local_search_metaheuristic =
> (routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH)

But I think that is not the correct wat to do it since I do not see in here that I am using
as INPUT the parameters given by the first_solution_strategy to do the refinement with the Metaheuristic.

I have done some research and i think i need to use SearchMonitor class and add some stop criteria and stuff but I am not sure. 
Could you please help me out to do it in my python script?

> Kindest Regards.

**Comment by furnon** [comment]
The settings you mentioned will make the solver find a first solution
with PARALLEL_CHEAPEST_INSERTION, then improve it with GUIDED_LOCAL_SEARCH.
Isn't that what you want to do ?
Note that you will need to specify a time limit as the search will run for
ever otherwise:
search_parameters.time_limit_ms = 10000

Vincent

**Comment by Adnanay** [comment]
Hi,
any updates about this issue, because i'm trying to work on my Bachelor project with OR-Tools and i've landed on the same question "How to use metaheuristics from OR-tools in python" with a first solution strategy.
I've tried it the same way as the two lines above (by setting the first-solution-strategy then setting the local-search-metaheuristic), but the value of the first solution strategy is getting worse and worse as long as i let the solver run!!!

Any help will be much appreciated
