### ISSUE TITLE
SystemError with the CVRPTW.py example

### ISSUE THREAD

**Issue by UlrikeWoell** [google/or-tools#502]
Hello, 
I tried out the CVRPTW example from the homepage. It works well after replacing 'print ...' by print(...). However, when I replace the data with data from my csv file, the error occurs:
```python
`File "C:\Program Files\Anaconda3\lib\site-packages\ortools\constraint_solver\pywrapcp.py", line 3352, in SolveWithParameters
    return _pywrapcp.RoutingModel_SolveWithParameters(self, search_parameters)

SystemError: <built-in function RoutingModel_SolveWithParameters> returned a result with an error set`
```
Please advise, what causes the error. Thank you.

**Comment by WillAyd** [comment]
Can you share the dataset and the code you have modified for it?

**Comment by nlsandler** [comment]
Hi there! I also encountered this error. In my case, the problem was a KeyError in my travel time callback function. When I ran the code in Python 2, I got a reasonable stack trace. When I ran it in Python3, I got the error message shown above.

Python 2:
```
  File "tsptw.py", line 251, in TotalTime
    travel_time = self.travel_time_callback(from_node, to_node)
  File "tsptw.py", line 238, in TravelTime
    travel_time = self.travel_times[from_node][to_node]
KeyError: 1
```

Python 3:
```
   3354     def SolveFromAssignmentWithParameters(self, assignment: 'Assignment', search_parameters: 'operations_research::RoutingSearchParameters const &') -> "operations_research::Assignment const *":

SystemError: <built-in function RoutingModel_SolveWithParameters> returned a result with an error set
```
I can share the code that caused the issue if you need me to, but I suspect you can reproduce it with any callback that raises an exception.

**Comment by naveen81** [comment]
Hello,
I also encountered the same error when running the solver using this command.
`assignment = routing.SolveWithParameters(search_parameters)`
I am using the dataset which has 3 columns like this:
quantity | x | y
---------- | -- | --
30.0 | 5 | 6

**Comment by Mizux** [comment]
Hi,

please notice there was some errors on the site [example](https://developers.google.com/optimization/routing/cvrptw#program) which has been corrected since.

If I use the [cvrptw.py](https://github.com/google/or-tools/blob/master/examples/python/cvrptw.py) example from github (e.d. also tested with a copy/paste of the site code example which is identical)
```sh
$> python --version
Python 2.7.13
$> python -m pip install --user ortools
...
$> python -m pip show ortools
Name: ortools
Version: 6.7.4973
Summary: Google OR-Tools python libraries and modules
Home-page: https://developers.google.com/optimization/
Author: Google Inc
Author-email: lperron@google.com
License: Apache 2.0
Location: /usr/local/google/home/corentinl/.local/lib/python2.7/site-packages
Requires: six, protobuf
$> python examples/python/cvrptw.py 
Route for vehicle 0:
 0 Load(0) Time(0,0) Slack(1,9) -> 12 Load(0) Time(5,13) Slack(0,8) -> 13 Load(2) Time(17,25) Slack(0,10) -> 15 Load(6) Time(45,52) Slack(0,7) -> 11 Load(14) Time(88,95) Slack(0,21) -> 0 Load(15) Time(99,120)
Distance of the route: 1780m
Load of the route: 15
Time of the route: 99min

Route for vehicle 1:
 0 Load(0) Time(0,0) Slack(0,3) -> 5 Load(0) Time(3,6) Slack(0,3) -> 8 Load(2) Time(15,18) Slack(0,3) -> 6 Load(10) Time(57,60) Slack(0,5) -> 2 Load(14) Time(80,85) Slack(0,26) -> 0 Load(15) Time(94,120)
Distance of the route: 1712m
Load of the route: 15
Time of the route: 94min

Route for vehicle 2:
 0 Load(0) Time(0,0) Slack(0,3) -> 7 Load(0) Time(2,5) Slack(0,3) -> 4 Load(8) Time(46,49) Slack(0,3) -> 3 Load(12) Time(67,70) Slack(0,5) -> 1 Load(14) Time(80,85) Slack(0,29) -> 0 Load(15) Time(91,120)
Distance of the route: 1552m
Load of the route: 15
Time of the route: 91min

Route for vehicle 3:
 0 Load(0) Time(0,0) Slack(0,8) -> 9 Load(0) Time(2,10) Slack(0,8) -> 14 Load(1) Time(10,18) Slack(0,8) -> 16 Load(5) Time(32,40) Slack(0,9) -> 10 Load(13) Time(76,85) Slack(0,28) -> 0 Load(15) Time(92,120)
Distance of the route: 1552m
Load of the route: 15
Time of the route: 92min

Total Distance of all routes: 6596m
Total Time of all routes: 376min
```

**Comment by Mizux** [comment]
The same test using Python3.6 interpreter

```sh
$> python3.6 --version
Python 3.6.2
$> python3.6 -m pip install ortools --user
...
$> python3.6 -m pip show ortools
Name: ortools
Version: 6.7.4973
Summary: Google OR-Tools python libraries and modules
Home-page: https://developers.google.com/optimization/
Author: Google Inc
Author-email: lperron@google.com
License: Apache 2.0
Location: /usr/local/google/home/corentinl/.local/lib/python3.6/site-packages
Requires: six, protobuf
$> python3.6 examples/python/cvrptw.py 
Route for vehicle 0:
 0 Load(0) Time(0,0) Slack(1,9) -> 12 Load(0) Time(5,13) Slack(0,8) -> 13 Load(2) Time(17,25) Slack(0,10) -> 15 Load(6) Time(45,52) Slack(0,7) -> 11 Load(14) Time(88,95) Slack(0,21) -> 0 Load(15) Time(99,120)
Distance of the route: 1780.0m
Load of the route: 15
Time of the route: 99min

Route for vehicle 1:
 0 Load(0) Time(0,0) Slack(0,3) -> 5 Load(0) Time(3,6) Slack(0,3) -> 8 Load(2) Time(15,18) Slack(0,3) -> 6 Load(10) Time(57,60) Slack(0,5) -> 2 Load(14) Time(80,85) Slack(0,26) -> 0 Load(15) Time(94,120)
Distance of the route: 1712.0m
Load of the route: 15
Time of the route: 94min

Route for vehicle 2:
 0 Load(0) Time(0,0) Slack(0,3) -> 7 Load(0) Time(2,5) Slack(0,3) -> 4 Load(8) Time(46,49) Slack(0,3) -> 3 Load(12) Time(67,70) Slack(0,5) -> 1 Load(14) Time(80,85) Slack(0,29) -> 0 Load(15) Time(91,120)
Distance of the route: 1552.0m
Load of the route: 15
Time of the route: 91min

Route for vehicle 3:
 0 Load(0) Time(0,0) Slack(0,8) -> 9 Load(0) Time(2,10) Slack(0,8) -> 14 Load(1) Time(10,18) Slack(0,8) -> 16 Load(5) Time(32,40) Slack(0,9) -> 10 Load(13) Time(76,85) Slack(0,28) -> 0 Load(15) Time(92,120)
Distance of the route: 1552.0m
Load of the route: 15
Time of the route: 92min

Total Distance of all routes: 6596.0m
Total Time of all routes: 376min
```

**Comment by shandilya1998** [comment]
I have been facing the same issue. The only difference in my case is that the start and end point of vehicles are different. I am getting a solution for same start and end point of all the vehicles, but getting this for the code below
`RuntimeError: SWIG std::function invocation failed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/travelapp/PycharmProjects/TravelApp/venv/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py", line 2136, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, Assignment, name, value)
  File "/Users/travelapp/PycharmProjects/TravelApp/venv/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py", line 71, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "/Users/travelapp/PycharmProjects/TravelApp/venv/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py", line 55, in _swig_setattr_nondynamic
    if type(value).__name__ == 'SwigPyObject':
SystemError: <class 'type'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/travelapp/PycharmProjects/TravelApp/travelapp.py", line 211, in <module>
    from travelapp import TripPlanner
  File "/Users/travelapp/PycharmProjects/TravelApp/travelapp.py", line 213, in <module>
    ob.plan_trip()
  File "/Users/travelapp/PycharmProjects/TravelApp/travelapp.py", line 205, in plan_trip
    solution = routing.SolveWithParameters(search_parameters)
  File "/Users/travelapp/PycharmProjects/TravelApp/venv/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py", line 3464, in SolveWithParameters
    return _pywrapcp.RoutingModel_SolveWithParameters(self, search_parameters, solutions)
SystemError: <built-in function RoutingModel_SolveWithParameters> returned a result with an error set`
This is the code that i have written. 
`from future import print_function
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp
class TripPlanner():

def __init(self):
    self.trip = []

def create_data_model(self):
    # retrieves data data for the problem
    # calls distance matrix api
    # currently test values have been plugged in
    data = {}
    data['time_matrix'] = [
        [0, 6, 7, 9, 7, 3, 6, 2, 3, 2, 6, 6, 4, 4, 5, 9, 7,0],
        [6, 0, 8, 3, 2, 6, 8, 4, 8, 8, 13, 7, 5, 8, 12, 12, 14, 6],
        [9, 8, 0, 11, 10, 6, 3, 9, 5, 8, 14, 15, 14, 13, 9, 18, 9, 15],
        [8, 3, 11, 0, 1, 7, 10, 6, 10, 10, 14, 6, 7, 9, 14, 6, 16, 14],
        [7, 2, 10, 3, 0, 6, 9, 4, 10, 19, 13, 4, 6, 18, 12, 8, 14, 9],
        [3, 6, 6, 7, 6, 0, 2, 8, 2, 2, 7, 9, 7, 7, 6, 12, 8, 3],
        [6, 8, 3, 10, 9, 2, 0, 6, 2, 5, 4, 12, 10, 10, 6, 15, 5, 10],
        [2, 4, 9, 6, 4, 3, 6, 0, 4, 4, 18, 5, 4, 23, 7, 8, 10, 12],
        [3, 8, 5, 10, 8, 2, 2, 4, 0, 3, 4, 9, 8, 7, 3, 13, 6, 5],
        [2, 8, 8, 10, 9, 2, 5, 4, 3, 0, 4, 6, 5, 4, 3, 9, 5, 8],
        [6, 13, 4, 14, 13, 7, 4, 8, 4, 4, 0, 10, 9, 8, 4, 13, 4, 9],
        [6, 7, 15, 6, 24, 9, 12, 5, 9, 6, 10, 0, 1, 3, 7, 13, 10, 11],
        [4, 5, 14, 8, 6, 7, 10, 4, 8, 5, 9, 1, 0, 2, 26, 4, 8, 1],
        [4, 8, 13, 9, 8, 7, 10, 13, 7, 4, 8, 3, 2, 0, 4, 5, 6, 2],
        [5, 12, 9, 14, 12, 2, 6, 7, 13, 13, 4, 7, 6, 4, 0, 9, 12, 4],
        [9, 10, 18, 6, 8, 12, 20, 8, 3, 9, 13, 3, 4, 5, 9, 0, 9,10],
        [7, 14, 9, 16, 14, 8, 5, 10, 6, 5, 4, 10, 8, 6, 2, 9, 0,13],
        [0, 4, 4, 6, 9, 2, 5, 8, 4, 2, 5, 15, 7, 1, 5, 13, 1, 0]
    ]
    data['time_windows'] = [
        (0, 22),  # depot
        (7, 12),  # 1
        (10, 15),  # 2
        (16, 18),  # 3
        (10, 13),  # 4
        (0, 5),  # 5
        (5, 10),  # 6
        (0, 4),  # 7
        (5, 10),  # 8
        (0, 3),  # 9
        (10, 16),  # 10
        (10, 15),  # 11
        (0, 5),  # 12
        (5, 10),  # 13
        (7, 8),  # 14
        (10, 15),  # 15
        (11, 15),  # 16
        (18,22)     #17
    ]
    data['num_days'] = 4
    data['start'] = [0,0,0,0]#,17,0,17]
    data['end'] = [17,17,17,17]
    return data

def print_solutions(self,
                    data,
                    manager,
                    routing,
                    assignment):
    # prints the final routing solution on the console
    time_dimension = routing.GetDimensionOrDie('Time')
    total_time = 0
    for vehicle_id in range(data['num_days']):
        index = routing.Start(vehicle_id)
        plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
        while not routing.IsEnd(index):
            time_var = time_dimension.CumulVar(index)
            plan_output += '{0} Time({1},{2}) -> '.format(
                manager.IndexToNode(index), assignment.Min(time_var),
                assignment.Max(time_var))
            index = assignment.Value(routing.NextVar(index))
        time_var = time_dimension.CumulVar(index)
        plan_output += '{0} Time({1},{2})\n'.format(
            manager.IndexToNode(index), assignment.Min(time_var),
            assignment.Max(time_var))
        plan_output += 'Time of the route: {}min\n'.format(
            assignment.Min(time_var))
        print(plan_output)
        total_time += assignment.Min(time_var)
    print('Total time of all routes: {}min'.format(total_time))

@property
def plan_trip(self):
    """Entry point of the program."""
    # Instantiate the data problem.
    data = self.create_data_model()

    # Create the routing index manager.
    manager = pywrapcp.RoutingIndexManager(
        len(data['time_matrix']), data['num_days'], data['start'], data['end'])

    # Create Routing Model.
    routing = pywrapcp.RoutingModel(manager)

    # Create and register a transit callback.
    def time_callback(from_index, to_index):
        """Returns the distance between the two nodes."""
        # Convert from routing variable Index to distance matrix NodeIndex.
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data['time_matrix'][from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(time_callback)

    # Define cost of each arc.
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    # Add Distance constraint.
    dimension_name = 'Time'
    routing.AddDimension(
        transit_callback_index,
        30,  # maximum waiting time for a vehicle
        30,  # vehicle maximum travel time
        False,  # start cumul to zero
        dimension_name)
    time_dimension = routing.GetDimensionOrDie(dimension_name)
    # Add time window constraints for each location except depot.
    for location_idx, time_window in enumerate(data['time_windows']):
        if location_idx == 0:
            continue
        index = manager.NodeToIndex(location_idx)
        print(location_idx)
        print(index)
        print(time_dimension.CumulVar(index))
        time_dimension.CumulVar(index).SetRange(time_window[0], time_window[1])
    # Add time window constraints for each vehicle start node.
    for vehicle_id in range(data['num_days']):
        index = routing.Start(vehicle_id)
        time_dimension.CumulVar(index).SetRange(data['time_windows'][0][0],
                                                data['time_windows'][0][1])
    for i in range(data['num_days']):
        routing.AddVariableMinimizedByFinalizer(
            time_dimension.CumulVar(routing.Start(i)))
        routing.AddVariableMinimizedByFinalizer(
            time_dimension.CumulVar(routing.End(i)))

    time_dimension.SetSpanCostCoefficientForAllVehicles(30)

    # Setting first solution heuristic.
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)

    # Solve the problem.
    solution = routing.SolveWithParameters(search_parameters)

    # Print solution on console.
    if solution:
        self.print_solutions(data, manager, routing, solution)

from travelapp import TripPlanner
ob = TripPlanner()
ob.plan_trip` 
I was following the following two examples on the documentation site- 
[https://developers.google.com/optimization/routing/vrptw](url) and 
[https://developers.google.com/optimization/routing/routing_tasks](url)

This is the first time i am using OR tools so am not sure why am i even getting the error. 
Is it due to the dataset that i am using? I tried both symmetric and asymmetric datasets and have also tried changing the time windows. 
Can anyone tell me what is the cause of the error and if there is anything else wrong with what i have written?
