### ISSUE TITLE
Vehicle Routing model - ApplyLocksToAllVehicles bug

### ISSUE THREAD

**Issue by emakarov** [google/or-tools#542]
Hello

I have a very strange behaviour of routing solver with partial routes (`ApplyLocksToAllVehicles`).

Short description.
I'm using `ApplyLocksToAllVehicles` to solve "real-time" vehicle PDPTW use-case.
Methodology
- create nodes with pickups, deliveries, vehicle positions, depot
- create partial routes (take into account which nodes have been picked up already)
- find a solution

And in very evident case solver cannot find it.

The minimal test case reproducing the bug is here:

https://gist.github.com/emakarov/88ffc202937b298f3aa3025f4447e78e

**Comment by emakarov** [comment]
@furnon could you kindly give any comments on this behaviour?

**Comment by emakarov** [comment]
Hello @furnon @lperron @Mizux !
Is there any chance that you could review this issue?

**Comment by emakarov** [comment]
Hello @furnon @lperron @Mizux !
Could you kindly check this issue?
or give any comments..

**Comment by Mizux** [comment]
Hi,

I've tested your code, thanks for the test case !

It seems the solver don't like to have two pickups without their dropoff in the partial route (some people seems to have worked +- on a similar bug internally).
My understanding is the constraint "pickup and dropoff must be in the same route (aka same vehicle)" need to be valid in the partial route given.
i.e. If you decide to put two pickup (i.e. 4 & 5) in the route 0 it's better to provision their dropoff too.
I think solver work by pair of nodes when building the first solution (note: you can only omit one dropoff  "[pickup1/dropoff1],[p2,d2], p3") otherwise routing can't find a first solution and suppose the problem is unfeasible...

Need to verify the assertion: "you can't have more than one pickup without its dropoff in a partial route"
if true we should add a note in the documentation concerning this caveat...

**Comment by emakarov** [comment]
Hi @Mizux 
Thanks for the answer. Seems like a deep detail of the solver behaviour
Let me check options that you have described. Although, I think, eventually I came to a confguration that more or less satisfies me.
Otherwise seems like we need to do C++ coding

**Comment by emakarov** [comment]
Hi @Mizux 
After your comments, I analysed the option. If I comment out the line 123 (remove AddPickupAndDelivery), then solver finds the solution. Seems like AddPickupAndDelivery and partial routes should not contradict each other?
```
              #  routing.AddPickupAndDelivery(index, dropoff_index)
```

**Comment by emakarov** [comment]
@Mizux I think issue is resolved in some sense
at least now I understand the reasons and possible workarounds
many thanks

**Comment by SiddharthaPaul** [comment]
@emakarov 
I am trying to start the VRP with an initial solution (e.g. [1,3,8,5]) where I want to lock the first two nodes of the route (i.e. [1,3]). In this context how do I use ApplyLocksToAllVehicles() in python? I did not find any example or documentation on the same. Any quick help will be highly appreciated.

What version of OR-tools and what language are you using?
Version: 6.10.6025
Language: Python
