### ISSUE TITLE
Cannot set (Linear)-SolverParameters or solver-specific parameters  for CBC in .Net

### ISSUE THREAD

**Issue by orwant** [google/or-tools#57]
Originally reported on Google Code with ID 41

```
I would like to solve a LP by using different parameters (especially different from
the default parameters). I tried to set some solver specific parameters for CBC by
two different ways:

1. I  tried to change the default values of the parameters LP_ALGORITHM, BARRIER and
DUAL by using the SetIntegerParam/SetDoubleParam-methods, but the values are unchanged
afterwards. The other default-parameters are changeable by using this methods.

2. Additionally, I tried to use SetSolverSpecificParametersAsString() with a string
of CBC-specific parameters. Currently, SetSolverSpecificParametersAsString() always
returns false, unless the input is empty. Could you give me an example to use this
method?

What version of the product are you using? On what operating system?
.Net OrTools.dll Version 3236 





```

Reported by `luisachristine` on 2014-04-10 09:10:26

**Comment by maeehart** [comment]
This seems not to work on C++ either. Is anybody working on this?

The comments in the header linear_solver.h are not helpful since I cannot find any information about CBC configuration files. I have tried SetSolverSpecificParametersAsString("ratio 0.05") and SetSolverSpecificParametersAsString("-ratio 0.05"). Firs of these works from the command line and the second one from the interactive optimizer, but neither has any effect from Google or-tools.

Any help is appreciated. Also, there is a question about this at https://groups.google.com/forum/#!searchin/or-tools-discuss/cbc%7Csort:date/or-tools-discuss/pfjxg7bg0Rg/e2VJD82XCgAJ, with no answer, so I am not the only one struggling with this.

**Comment by lperron** [comment]
I do not know how to do it in C++. Api is really unfriendly.
