### ISSUE TITLE
System.AccessViolationException in C#

### ISSUE THREAD

**Issue by johny8228** [google/or-tools#591]
Hello,

I keep getting `System.AccessViolationException` from time to time in an nondeterministic way  when I try to call the method `Solve` or `SolveWithParameters`. I searched the internet for a solution and there are suggestions to keep references to the OR-Tools object instances in a List.I did this but I get the same exception  `System.AccessViolationException`. Is this a known issue in C# that will be fixed?Are there any solutions for this?Unfortunately if I don't pass this critical issue I'm afraid I need to search another library for optimization even if I started to get used to or-tools.

Best regards,
Ionut

**Comment by Mizux** [comment]
Seems a duplicate from #308

**Comment by lperron** [comment]
Most the access violation are due to callbacks being GCed while the search is running.
Can you double check these are referenced correctly.

The bad pattern is the following:

void BuildModel(RoutingModel model) {
  // Create distance callback
  // pass it to the solver
}

void Search(RoutingModel model) {
  // Call SolveWithParameters
}

void Main() {
  RoutingModel model = new RoutingModel();
  BuildModel(model);
  Search(model);
}
