### ISSUE TITLE
Getting the value of variables created during the search at solution

### ISSUE THREAD

**Issue by JKBehrens** [google/or-tools#628]
Hello,

during search, I create variables and add constraints using those variables. What is the preferred option to retrieve the values (or domains) of variables created in this way at a solution? How could I build a decision builder for the variables created during search?

```
from ortools.constraint_solver import pywrapcp

class myConstraint(pywrapcp.PyConstraint):
    def __init__(self, solver, intvar):
        # type: (pywrapcp.Solver, pywrapcp.IntVar)
        pywrapcp.PyConstraint.__init__(self, solver)
        self._intvar = intvar

    def Post(self):
        demon = self.Demon(myConstraint.InitialPropagate)
        self._intvar.WhenBound(demon)

    def InitialPropagate(self):
        solver = self.solver()  # type: pywrapcp.Solver
        newIntVar = solver.IntVar(0, 5, "new_var")
        solver.AddConstraint(newIntVar == self._intvar)
        # alternative constraint, which doesn't neccesarily bind newIntVar 
        # solver.AddConstraint(newIntVar >= self._intvar)

if __name__ == "__main__":
    solver = pywrapcp.Solver("mySolver")
    first_int_var = solver.IntVar(0, 10, "first_var")
    solver.Add(myConstraint(solver, first_int_var))

    db = solver.Phase([first_int_var], solver.CHOOSE_FIRST_UNBOUND, solver.ASSIGN_MAX_VALUE)

    solver.NewSearch(db)

    while(solver.NextSolution()):
        print first_int_var.Value()
        # how can I acces the variable newIntVar here
    solver.EndSearch()
```

The above code produces the following output:
> 5
> 4
> 3
> 2
> 1
> 0

This shows, that the Constraint myConstraint works as the solutions 6 to 10 don't exist.

Thank you in advance!
Jan

**Comment by srowan** [comment]
I believe the steps are something close to...

Before you call NewSearch:

1) Create a solution collector, for example via `collector = solver.MakeLastSolutionCollector()`
2) Add the vars you care about to the collector : `collector.add(newIntVar)`

Then add the collector when calling newsearch: `solver.NewSearch(db, collector)`

Then in your while loop, access it via `value = collector.Solutions(0).Value(newIntVar)` or `value = collector.Value(0, newIntVar)`

https://acrogenesis.com/or-tools/documentation/user_manual/manual/first_steps/monitors.html#solutioncollectors

**Comment by JKBehrens** [comment]
Thank you for your answer, @srowan! My question is not that simple, because `newIntVar` is not existent before the call to `NewSearch`, so it can't be added to a solution collector outside search. Rather, it is created during the search in the constraint propagation, i.e. in `myConstraint.InitialPropagate().` This has two implications:
   
1. The Variable is not present before the search (as mentioned) -> can't be added to SolutionCollector before NewSearch
2.  In case the decision of the solver on `first_int_var` has to be refuted (i.e. here in the case of values 6 to 10), the newly created variables `newIntVar` should also be deleted -> forbids simple saving of the newly created variables to a list or dictionary.

Before I implement my own SearchMonitor to track the current set of variables in the solution, I wanted to discuss the options. 

Thanks! 
Jan

**Comment by lperron** [comment]
Hi,

simple remarks:

The storage part has to exist outside of the search, so if you create a
variable inside the search, there must be a way to exploit its solution
value from outside the search.
It means that you need to have a data structure that can mimic the
structure of the expanded model.

The best solution IMO it to:
  - store all new variables in reversible data structures because you need
a handle on these variables.
  - use a search monitor and an AcceptSolution callback to create that
solution data structure.

This being said, I prefer code where the model and the solve are self
contained.
Thus the meta exploration can be done manually outside the search (base
model, add a new factory, run solve to compute cost and efficiency, change
model to change the characteristics of the factory, resolve, compare...).

If possible, I prefer this approach.

I hope this helps.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 3 avr. 2018 à 13:06, Jan Behrens <notifications@github.com> a
écrit :
