### ISSUE TITLE
changing the constraints on num_nurses/num_days

### ISSUE THREAD

**Issue by niiarmah95** [google/or-tools#674]
pls i would like to know how you would change the constraints on nurse_stat/day_stat

ive tried but still cant figure it out

any help pls

**Comment by Mizux** [comment]
Do you talk about [this](https://github.com/google/or-tools/blob/master/examples/python/nurses_sat.py) example ?

**Comment by niiarmah95** [comment]
nope
the one from [here](https://github.com/google/or-tools/blob/master/examples/python/nurse_rostering.py)

**Comment by niiarmah95** [comment]
and from the one you just sent [here](https://github.com/google/or-tools/blob/master/examples/python/nurses_sat.py) do your have to change any constraint after you have changed the
`num_nurses = 4`

  `num_shifts = 4` 
    
`num_days = 7`

**Comment by qq88976321** [comment]
For the [nurse_rostering.py](https://github.com/google/or-tools/blob/master/examples/python/nurse_rostering.py) example, there are three main constraints.

1. Regular constraint (http://www.minizinc.org/downloads/doc-latest/minizinc-tute.pdf page44 has the DFA figure)
- one day off every 4 days
- no 3 nights in a row.
```
  #
  # constraints
  #
  for i in range(num_nurses):
    reg_input = [x[i, j] for j in range(num_days)]
    regular(reg_input, n_states, input_max, transition_fn,
            initial_state, accepting_states)
```

2. Each nurse must work between 7 and 10 days during this period
```
  #
  # Statistics and constraints for each nurse
  #
  for i in range(num_nurses):
    # number of worked days (day or night shift)
    b = [solver.IsEqualCstVar(x[i, j], day_shift) +
         solver.IsEqualCstVar(x[i, j], night_shift)
         for j in range(num_days)]
    solver.Add(nurse_stat[i] == solver.Sum(b))

    # Each nurse must work between 7 and 10
    # days during this period
    solver.Add(nurse_stat[i] >= 7)
    solver.Add(nurse_stat[i] <= 10)
```

3. The shifts distribution for weekends and workdays
- weekends: day_shift == 2, night_shift == 1, off_shift == 4
- workdays: day_shift == 3, night_shift == 2, off_shift == 1
```
  #
  # Statistics and constraints for each day
  #
  for j in range(num_days):
    for t in shifts:
      b = [solver.IsEqualCstVar(x[i, j], t)
           for i in range(num_nurses)]
      solver.Add(day_stat[j, t] == solver.Sum(b))

    #
    # Some constraints for this day:
    #
    # Note: We have a strict requirements of
    #       the number of shifts.
    #       Using atleast constraints is much harder
    #       in this model.
    #
    if j % 7 == 5 or j % 7 == 6:
      # special constraints for the weekends
      solver.Add(day_stat[j, day_shift] == 2)
      solver.Add(day_stat[j, night_shift] == 1)
      solver.Add(day_stat[j, off_shift] == 4)
    else:
      # workdays:

      # - exactly 3 on day shift
      solver.Add(day_stat[j, day_shift] == 3)
      # - exactly 2 on night
      solver.Add(day_stat[j, night_shift] == 2)
      # - exactly 1 off duty
      solver.Add(day_stat[j, off_shift] == 2)
```

So, if you want to change `num_days`, you should also change constraint 2. as mentioned above, because the sum of the three shifts each day must equal to `num_nurses`.

For example, try `num_days = 3` and
```
# Each nurse must work between 3 and 7 days during this period
solver.Add(nurse_stat[i] >= 3)
solver.Add(nurse_stat[i] <= 7)
```

Similary, if you want to change `num_nurses`, you should also change constraint 3. as mentioned above, because the sum of the three shifts each day must equal to `num_nurses`.

For example, try `num_nurses = 10` and
```
if j % 7 == 5 or j % 7 == 6:
  # special constraints for the weekends
  # 3+2+5==num_nurses
  solver.Add(day_stat[j, day_shift] == 3)
  solver.Add(day_stat[j, night_shift] == 2)
  solver.Add(day_stat[j, off_shift] == 5)
else:
  # workdays:
  # 4+3+3==num_nurses
  solver.Add(day_stat[j, day_shift] == 4)
  solver.Add(day_stat[j, night_shift] == 3)
  solver.Add(day_stat[j, off_shift] == 3)
```
