### ISSUE TITLE
minimum-cost flow problem with floating cost

### ISSUE THREAD

**Issue by chengricky** [google/or-tools#687]
Platform: vs2015 x64 on windows 10
Version: ortools 6.4
Language: C++

Is it possible for ortools to sovle a minimum-cost flow problem with floating cost?
I noticed that in the original codes, only int64 type is permitted to assigne to costs of egdes, in view of the explicit instance of template class in "min_cost_flow.cc" using template class "GenericMinCostFlow".

I have modified the codes in  "min_cost_flow.cc" and "min_cost_flow.h", (moving the implementation of template class from .cc to .h), which allow to assign costs of edges as floating types. 

Though the compiling is passed, the errors occurred as follows:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0510 22:39:03.924849 14172 min_cost_flow.h:1549] Infeasible problem.
F0510 22:39:03.927866 14172 min_cost_flow.h:808] node_excess_[0] != 0
*** Check failure stack trace: ***
```

i am not familiar with the principle of minimum-cost flow problem. I would like to know is it possible to solve a minimum-cost flow problem with floating cost?

Thanks.

**Comment by rodowi** [comment]
AFAIK, it is possible to solve for a minimum-cost flow problem with fractional values **using the LP solver**. I did it by accident actually, as my original intention was to work with integer values. So if you create the flow variables using MakeNumVar you'll get floating point values instead of integer (i.e. costs and total flows with fractional values), as seen in the documentation here https://developers.google.com/optimization/reference/linear_solver/linear_solver/MPSolver/#MakeNumVar

If you decide to make the switch to LP that might work for you.

**Comment by rodowi** [comment]
I'm assuming that you are working with https://developers.google.com/optimization/flow/ and I'm suggesting defining the problem as https://developers.google.com/optimization/lp. It's just a bit more of work but you get more granular control.

**Comment by chengricky** [comment]
Thanks for @rodowi 's help. But I think it's hard for me to rewrite the minimum-cost flow problem by LPsolver. I have found a substitute that the actual cost (floating number) is enlarged to 100 times.

**Comment by lperron** [comment]
OK, LP is quite easy though, but I would think the flow algorithm to be faster, at the price of expandability.
