### ISSUE TITLE
Cannot find an answer to issues

### ISSUE THREAD

**Issue by olushako** [google/or-tools#689]
Dear Team, I am trying to use OR-Tools with C# to optimize routes.
But faced with several issues with no idea how to solve it: 

1. How to limit length of the route? Cumulative distance in the route
2. How to put constrain to limit number of locations served in the route? for example to max 3 nodes
3. is it possible to serve one node with several trucks? for example: we have a demand in node 30. max capacity of trucks - 20. currently if I am putting this demand in node with 30 - the program goes to the loop without any result. 
```
Routing.AddDimension(demandCallback, 0, 20, true, "capacity");
var distances = new RandomManhattan();
routing.SetCost(distances);
var searchParameters =RoutingModel.DefaultSearchParameters();
searchParameters.FirstSolutionStrategy = FirstSolutionStrategy.Types.Value.PathCheapestArc;
var solution = routing.SolveWithParameters(searchParameters);
```
In theory it should be served by two trucks but I don't know how to do it. 
Will appreciate your help
Thanks, Sasha

**Comment by alanbato** [comment]
Wish I could provide code examples but I haven't used the C# wrapper and I don't remember the implementation details quite well. I hope I can help at least a bit.
1. You need to set a constraint on the Max value of the distanceDimension CumulVar for every vehicle.
2. You need to create another "demand" demansion that adds 1 to your vehicle's CumulVar everytime it visits another node. Then you constraint on such CumulVar like in (1)
3. I'm not sure, haven't done it myself.

Kind Regards and Good luck

**Comment by Mizux** [comment]
Hi,

for 3 it is currently not possible, the solver can only visit one time each node. However, the tricks is to split the node in two for example...

**Comment by olushako** [comment]
@alanbato thanks a lot for feedback. theoretically really cool approaches. I am trying to realize it but every time cannot understand how to build this structure, because I am very new to ortools... Do you have **any** implementation in different languages? it is not important to have it in C# . will really appreciate your help

**Comment by olushako** [comment]
@Mizux split to several nodes... very cool approach. thanks a lot!

**Comment by alanbato** [comment]
Alright, I'll tell you how I'd do it with the Python wrapper.
For (1) You'll need to have a dimension called `Distance` that keeps track of the total distance of the trip in a CumulVar.
For that you can look at the [AddDimension()](https://github.com/google/or-tools/blob/0777e4d12ff9b45397c3aa6bbe14fc72b19bf453/ortools/constraint_solver/routing.h#L399) function.
Then, you get the dimension in a variable and constraint it so the CumulVar at any node cannot be bigger than your limit `my_limit`, like this:
```python
dist_dimension = routing.GetDimensionOrDie("Distance")
for customer in customers:
    dist_dimension.CumulVar(customer.index).SetMax(my_limit)
```
This restrains the domain of the distance CumulVar on that node. You could also do it the constraint way like this:
```python
dist_dimension = routing.GetDimensionOrDie("Distance")
for customer in customers:
    solver.Add(dist_dimension.CumulVar(customer.index) <= my_limit)
``` 
I don't know for sure which approach is best for you, but the first one leaves you with a "harder" constraint than the second approach.

While doing research trying to answer this question, I just came up with using [AddDimensionWithVehicleCapacity](https://github.com/google/or-tools/blob/0777e4d12ff9b45397c3aa6bbe14fc72b19bf453/ortools/constraint_solver/routing.h#L405) to solve the same problem with less code, you wouldn't need to use `SetMax()` or a constraint, as it is done automatically by using the `vehicle_capacities` list as the limit value for each vehicle.

The same can be done for (2). The only difference is the `node_evaluator` callback function which you use. For (1), given `a` and `b` it should return the distances between nodes `a` and `b`. For (2), you can always return `1` because you are counting the nodes visited.

These are the approaches I came up with and I don't know if the authors have better ways of doing either of them :)

Best of luck!
