### ISSUE TITLE
Help Needed (Constraint Programming, Job Scheduling)

### ISSUE THREAD

**Issue by kisna72** [google/or-tools#690]
I created a simple problem to learn the basics. I got stuck while solving and am hoping I can find some help here.  
There are three jobs. Each take a certain time to get done.
`jobs = [[1,60],[2,8],[3,100]]`

There are two identical machines. Both are capable of performing all three jobs.
`machines = [1,2]`

I created all tasks:
```
for i in machines:
  for j in jobs:
    all_tasks[(i,j)] = solver.FixedDurationIntervalVar(0,horizon,jobs[j][1],False,"part_%s_job_%s" %(i,j))
```

Next, I added disjunctiveConstraint (A machine can perform one task at a time)
`disj = solver.DisjunctiveConstraint(jobs_on_machine, "machine_%s" %i  )`

Next, I want to add a constraint that 1 job can only be solved on one machine, and cannot figure out how to add  that constraint. 

How do I add that constraint? Any pointers?

**Comment by lperron** [comment]
You need to make jobs as optional (True instead of False),

then for jobs that can happen on either machine, sum(PresenceExpr()) == 1.

for the job that can happen on only one machine, just create it non optional, and do not create the optional one on the other machine.

Furthermore, if you are starting, please look at the CP-SAT solver instead.

https://github.com/google/or-tools/blob/master/ortools/sat/doc/index.md

Thanks
