### ISSUE TITLE
Constrain destinations only reachable by some vehicles

### ISSUE THREAD

**Issue by bertop89** [google/or-tools#718]
I was wondering if there is any way I can add a restriction to a VRP so that some destinations can only be visited by a subset of the available vehicles. Thank you very much!

**Comment by Mizux** [comment]
I would model it as the opposite: i.e. the list of vehicles which are not allow to visit this node (i.e. using 'and' instead of 'or')

E.g. supposing you have three vehicles 'A',  'B' and 'C', and only 'C' could visit node `node_idx` you should be able to add some constraints like this:
```python
routing.solver().Add(routing.VehicleVar(node_idx) != A_idx)
routing.solver().Add(routing.VehicleVar(node_idx) != B_idx)
```

note: Inspired by Pickup&Delivery issue #703

**Comment by bertop89** [comment]
Thanks once again @Mizux , it worked perfectly!

**Comment by GuyBenhaim** [comment]
zzz
