### ISSUE TITLE
CMake build support future

### ISSUE THREAD

**Issue by navidR** [google/or-tools#732]
I am trying to add or-tools to vcpkg [1].  But before that, I need to know what is future of cmake support in or-tools? I see it is experimental. Experimental means there is a good chance of removing it in future? Or experimental in this context means it is going to get more stable and eventually fully supported in or-tools? (In this case, I can rely on CMake support of or-tools team and add it to vcpkg).

1) https://github.com/Microsoft/vcpkg/issues/692

**Comment by lperron** [comment]
We would like to drop make in favor or cmake completely.

There are still a few issues, but this is the future of the build part of
or-tools.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 25 juin 2018 à 07:30, Navid Rahimi <notifications@github.com> a
écrit :

**Comment by Mizux** [comment]
Hi,

Yes it is intended to use CMake as default build (at least for C++) and to replace our current Makefile based system.
For vcpkg it's a long term goal but before we ant or-tools deps to be also in vcpkg IMHO.

i.e. currently in CMakelists.txt I build zlib, gflags, glog, protobuf, mizux/CBC and merge everything.
I would like to depends on vcpkg instead but:

ZLIB: want to use my CMake version https://github.com/madler/zlib/pull/337
GFlag: better if we could use gflags::gflags https://github.com/gflags/gflags/pull/247
CBC: 
- on github it is split in 5 repos (CoinUtils, Osi, CLP, CGL, CBC) we now use this layout for unix since most distro use this instead of the svn standalone CBC build
- there i no support for CMake so I did one here https://github.com/Mizux/Cbc but i use the svn one repo version instead of the splited ones -> need to redo it

Then we will provide an OR-Tools vcpkg after if you want to work on our dependencies to vcpkg them all...

CMake is currently experimental since:
- dependencies management is not still clear (currently we `add_subdirectory()` all our deps using `AddProject` tricks)
- Currently I only did C++ / python swig support. I need to figure out how to do the .Net and Java support since CMake is a C/C++ project generator at its core.
e.g. CMake learn C# in CMake 3.8 https://cmake.org/cmake/help/v3.8/release/3.8.html ...
- We would like to here from community (tester) if my CMake support is stable enough and work for them

**Comment by navidR** [comment]
It is good news to hear we are going to rely on CMake. And only C++ would suffice I think.

I am fighting right now with https://github.com/google/or-tools/blob/master/CMakeLists.txt#L12

It seems you are redefining find_package. I think it is better to have something like ortools_find_library than redefining find_package. (LLVM does this with add_llvm_library). redefining find_package does not play well when I want to integrate vcpkg and use dependencies of or-tools from vcpkg.

**Comment by navidR** [comment]
Are you guys open to looking into PR? I use clone vcpkg itself in our code repository. It makes management of dependencies way more easier. You should basically have a git submodule of vcpkg and then you can customize vcpkg to your need. 

So basically  the flow for compiling or-tools will be like this : 

```
git clone $url --recursive
cd ortools/vcpkg
./bootstrap
./vcpkg install gflags glogs Cbc protobuf
cd ..;
cmake -G "Ninja" .. -DCMAKE_TOOLCHAIN_FILE:STRING=$(PWD)/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_PYTHON=OFF
```

That's about it. In all supported platform that is going to make work. I am doing this in our private code repository.

**Comment by Mizux** [comment]
While I'm agree with your flow,  I don't think we need to have some vcpkg file here.

I mean vcpkg is a tools by Microsoft to fix their own package management issue (yes it's multi platform but we don't wait them to build some tools)...
I mean on GNU/linux distro you already have package manager and on MacOS you have homebrew
So objective is for OR-Tools C++ deliveries:
- Linux Distro Package for Linux
- Homebrew formula for MacOS (which should be in homebrew/homebrew-core)
- vcpkg for Windows
Further more Microsoft provide a repo (i.e. Microsoft/vcpkg) for all package recipe (like homebrew)

So, while I'm open to have some change to CMake to be more usable, I think vcpkg stuff should live directly in https://github.com/Microsoft/vcpkg/tree/master/ports not in this repo.

i.e. here we should have an agnostic CMake that you can use/embed with your prefered tools (e.g. vcpkg, adment, conan, yocto recipe, android toolchain etc...).

note: Homebrew Makefile test https://github.com/Mizux/homebrew-or-tools/blob/master/or-tools.rb basically I want the same workflow for CMake,  i.e. you can have installed all dependencies in the host system, then having a way to CMake/Make OR-Tools using them instead of compiling them.

**Comment by navidR** [comment]
Just as small fix, I think you have to reinvestigate vcpkg. The developers of vcpkg designed it to be integrated into every kind of project (not as a system-wide package manager, but as a customized dependency manager integrated into your codebase rather than being universal). It is basically dependency management tool. So having a one united dependency management tool for a C++ project is a huge sum. While the cost is very low and we have to only maintain a private branch of vcpkg (if we don't need anything special to the main branch, even *that* is not requirement).

The problem with using Linux distro package managers or homebrew (as I use right now) is mostly inconsistent version between libraries. Some are older, some are newer. vcpkg would give us one united and robust dependency management. Something like Rust's cargo. And as far as I know, some enterprises do use the approach I am explaining to you in their private repos. 

But I agree with your other point. The integration of vcpkg would mean a headache for Android, embedded stuff, or custom targets. (Since it only supports Windows/Linux/OSX, right now. But I have heard from its developers they are going to add a way to have custom triplet).

Anyways, I hope we will see more cmake improvement to or-tools.

**Comment by ras0219-msft** [comment]
>they are going to add a way to have custom triplet

Just to bump this up, we definitely have this capability[1]! Additionally, we accept CMake toolchain files[2], and have several users who've successfully build libraries for Android and iOS via that mechanism :)

[1] https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md
[2] https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_chainload_toolchain_file

**Comment by lperron** [comment]
Currently no plan, sorry.
CMake support is still not finished after more than 1 year of work.
And no visible increase in user adoption of vcpak.
