### ISSUE TITLE
No module named 'ortools'

### ISSUE THREAD

**Issue by uioplmn** [google/or-tools#737]
I am very new to Python an OR-Tools, so please excuse the simplicity of my question.
I installed OR-Tools by executing `ortools-6.7.4973.win-amd64-py3.6.exe` on my 64-bit, Win10 machine.
When I try to execute `from ortools.constraint_solver import pywrapcp` in the command prompt of Spyder, I get the error `No module named 'ortools'`.
What am I doing wrong? Thanks in advance!

**Comment by lperron** [comment]
Most likely, you need to install visual studio 2017 redistributables c++
libraries.

https://aka.ms/vs/15/release/VC_redist.x64.exe

Please also make sure the python you are using is 64 bit.

Can you try?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
```sh
python --version
python -c "import platform; print(platform.architecture()[0])"
python -m pip --version
```

**Comment by justinwkUKM** [comment]
I had the same issue. Like @Iperron mentioned it is usually caused due to missing Microsoft Visual Studio 20** redistributables c++. 
This is how I solved it.
1. Got the latest Microsoft Visual Studio 20** redistributables c++ from https://support.microsoft.com/en-my/help/2977003/the-latest-supported-visual-c-downloads
2. Installed it and Restarted the computer.
3. Uninstall the ortools 'python -m pip uninstall ortools'
4. Install back the ortools 'python -m pip install --user ortools'
5. Validated installation with python -c "from ortools.linear_solver import pywraplp"

**Comment by Mizux** [comment]
I'll try to add the Redistributable in the installation doc
