### ISSUE TITLE
Mandate Vehicle N to serve Node M

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#752]
I need certain vehicles to serve certain nodes. Options:

>Is there such an **explicit** constraint?
>Can I use **PickupandDrop** constraint for each such node (+ a dummy)?
>Can I first **synthesize** a solution just for these vehicles & nodes, **lock it**, and run solver for all vehicles and nodes? (could disable optimizing distances by the solver)

**Comment by Mizux** [comment]
yes you can "force" the vehicle id for each node like for PD problems:
```python
idx = routing.nodeToIndex(N)
routing.solver().Add(routing.VehicleVar(idx) == routing.VehicleVar(routing.Start(vehicle_id)))
```

**Comment by Mizux** [comment]
> Do the node-to-vehicle assignment constraints mandate the vehicle to serve ALL these nodes, and contradicts the Disj that include some or all these nodes?

I would say yes, since [`AddDisjunction`](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h#L514) solver is allow to visit **at most** one node  or nothing and pay the penalty.
So it must interfere with the `vehicle(nodeA) == vehicle(nodeB) == vehicle(nodeC)`.

My 2 cents (not tested !!!)
Maybe you can try to create an ["or"](https://developers.google.com/optimization/cp/cp_solver#combine)
aka "vehicle of node N is vehicle M **or** node N is not assigned"
```python
idx = routing.nodeToIndex(location_idx)
solver.Add(
  solver.Max(
    routing.VehicleVar(idx) == routing.VehicleVar(routing.Start(vehicle_idx),
    routing.VehicleVar(idx) == NOT_ASSIGNED) == 1
 )
)
```
note: not tested, and need to figure out the value of "NOT_ASSIGNED".
EDIT: I guess a not assigned node has itself as next so maybe `routing.NextVar(idx) == idx` or `routing.ActiveVar(idx) == 0` could be use to replace the "NOT_ASSIGNED" line.
src: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h#L852

**Comment by GuyBenhaim** [comment]
Thx,
OR probably what I need. For the one node in the Disj set that is served, it should be by the requested/forced vehicle. Other nodes that are not served (due to Disj).

Can you please elaborate: What does Max or MakeMax(?) perform? 
It gets two expressions and maximizes what?  Why do we need the "== 1" at the end?

**Comment by Mizux** [comment]
each expression (e.g. `x != y`) is a boolean expression which is `True` if the constraint is respected.
Now you want  a least one of the two expression to be true (i.e. evaluate to 1). So using `Max(Bool_expression_1, bool_expression_2) == 1` you say I want **at least** one of the expression to be evaluated to one (yes both can be true).

For XOR i agree **BUT** since or both constraints are mutually exclusive (i.e. you can't be "not served" and "served by vehicle N" at the same time) -> you don't care of this case (both constraint true) which is impossible...

**Comment by GuyBenhaim** [comment]
Brilliant

**Comment by GuyBenhaim** [comment]
For some reason, just forcing a certain vehicle to serve a set of nodes, which are also in a Disj set causes a crash. Maybe forcing a certain vehicle to **potentially** serve a node contradicts not serving it, due to Disj.

The condition: Serve with specific vehicle **OR** Don't Serve seems to work. Will check Sum later.

**Comment by GuyBenhaim** [comment]
Would you say that the Sum(expr1, expr2) == 1 condition is more strict than the MakeMax() condition in ensuring the OR/XOR constraint is met?
