### ISSUE TITLE
"Linear solver not recognized" when using SCIP

### ISSUE THREAD

**Issue by mandaboss** [google/or-tools#759]
macOS 10.13.4:

I built google or-tools 6.7.2 from source with SCIP, following instructions on documentation page (i.e. make_third party, specifying scip folder in Makefile.local, etc).  When running the examples (from bin folder), integer_programming worked fine for both CBC and SCIP.  However, when using the generated .dylib as a library (in c++ xcode project), CBC works but SCIP does not.  When trying to use SCIP, error generated:
 F0716 10:06:04.858498 25363328 linear_solver.cc:394] Linear solver not recognized.
*** Check failure stack trace: ***

I tried this with scip 4.0.0, 4.0.1, and 5.0.1.  

Help appreciated!

**Comment by Mizux** [comment]
Hi,

How did you integrate it in your C++ project ? I mean did you use the corresponding compilation flags ?
For example if I run `make detect_cc` (on debian here)
```sh
Relevant info for the C++ build:
PROTOC = LD_LIBRARY_PATH=/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib64:/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib: /usr/local/google/home/corentinl/work/or-tools/dependencies/install/bin/protoc
CCC = g++ -fPIC -std=c++11 -fwrapv
CFLAGS = -O4 -DNDEBUG -I. -Iexamples -Iortools/gen -I/usr/local/google/home/corentinl/work/or-tools/dependencies/install/include -I/usr/local/google/home/corentinl/work/or-tools/dependencies/install/include -I/usr/local/google/home/corentinl/work/or-tools/dependencies/install/include -I/usr/local/google/home/corentinl/work/or-tools/dependencies/install/include -I/usr/local/google/home/corentinl/work/or-tools/dependencies/install/include/coin -I/usr/local/google/home/corentinl/work/or-tools/dependencies/install/include -I/usr/local/google/home/corentinl/work/or-tools/dependencies/install/include/coin -I/usr/local/google/home/corentinl/work/or-tools/dependencies/install/include -I/usr/local/google/home/corentinl/work/or-tools/dependencies/install/include/coin -DUSE_CLP -I/usr/local/google/home/corentinl/work/or-tools/dependencies/install/include -I/usr/local/google/home/corentinl/work/or-tools/dependencies/install/include/coin -I/usr/local/google/home/corentinl/work/or-tools/dependencies/install/include -I/usr/local/google/home/corentinl/work/or-tools/dependencies/install/include/coin -DUSE_CBC -Wno-deprecated -DUSE_GLOP -DUSE_BOP
LDFLAGS = -lz -lrt -lpthread -Wl,-rpath,$ORIGIN -Wl,-rpath,$ORIGIN/../lib -Wl,-rpath,$ORIGIN/../dependencies/install/lib64 -Wl,-rpath,$ORIGIN/../dependencies/install/lib
LINK_CMD = g++ -shared
DEPENDENCIES_LNK = -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lgflags -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lglog -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib/ -lprotobuf -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lCbcSolver -lCbc -lOsiCbc -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lCgl -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lClpSolver -lClp -lOsiClp -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lOsi -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lCoinUtils
SRC_DIR = .
GEN_DIR = ortools/gen
EX_DIR = examples
OBJ_DIR = objs
LIB_DIR = lib
BIN_DIR = bin
prefix = /usr/local
OR_TOOLS_LNK = -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lgflags -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lglog -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib/ -lprotobuf -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lCbcSolver -lCbc -lOsiCbc -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lCgl -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lClpSolver -lClp -lOsiClp -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lOsi -L/usr/local/google/home/corentinl/work/or-tools/dependencies/install/lib -lCoinUtils -L/usr/local/google/home/corentinl/work/or-tools/lib -lortools
OR_TOOLS_LDFLAGS = -lz -lrt -lpthread -Wl,-rpath,$ORIGIN -Wl,-rpath,$ORIGIN/../lib -Wl,-rpath,$ORIGIN/../dependencies/install/lib64 -Wl,-rpath,$ORIGIN/../dependencies/install/lib
OR_TOOLS_LIBS = lib/libortools.so
```

look at the `CFLAGS` in your case you should **also** have a `-DUSE_SCIP` i.e. you must have this define when compiling in your external project

**Comment by mandaboss** [comment]
Thanks for the response,

I don’t have any cflags.  I just linked the 4 .dylibs and added the include directory to include paths.  I do #define USE_(whichever solver i’m using) at the top of my main.cpp file (before includes).  Are there cflags i need to add? Am I setting the project up wrong?  I have been using ortools like this in Xcode projects for a while now using CBC_MIXED_INTEGER and GLOP...is there something else I need to do to get SCIP working?

**Comment by mandaboss** [comment]
Ok, I'm only linking the libortools.dylib now, but same problem.  CBC works fine but SCIP gives me the same error as before.

result of otool -L:
	@rpath/libortools.dylib (compatibility version 6.7.0, current version 6.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)

**Comment by GIrisarri** [comment]
Concerning issue #759, I ran into exactly the same problem building or-tools-6.10. I was able to build the tools, from source, on a Linux CentOS 7 environment including SCIP 6.0.1 (which I also needed to build from source because the binaries provided from SCIP cannot run in CentOS 7 due to GLIBC incompatibilities.) However, as said, both SCIP 6.0.1 and or-tools 6.10 (cc, dotnet, ...) can be built without any errors. However, when running 'make test_cc USE_SCIP', the error

"Linear solver not recognized using SCIP" 

shows up and that portion of the test run is skipped. The question is, is this issue really closed? What is the solution? I am assuming that or-tools were built with the proper libraries (libscip, ...) because there were no complaints after building. Is or-tools using shared libraries? Or is it using static libraries? Should the shared libraries be placed somewhere else than the UNIX_SCIP_DIR/lib?

Your help is highly appreciated.

**Comment by Mizux** [comment]
@GIrisarri can you post the command line of the example you build
e.g. `make build SOURCE=examples/cpp/integer_programming.cc`

Fist you should define UNIX_SCIP_DIR
https://github.com/google/or-tools/blob/554cbccaa95b4c11eced13f145de1bf468e1f919/makefiles/Makefile.unix.mk#L96-L100
https://github.com/google/or-tools/blob/554cbccaa95b4c11eced13f145de1bf468e1f919/makefiles/Makefile.unix.mk#L129-L136
you can check SWIG is correctly detected using
`make detect_port` and `make detect_cc` you should see a `-DUSE_SCIP` etc...  in CFLAGS,

**Comment by GIrisarri** [comment]
Thank you very much for your response. 

In Makefile.local (after doing make third_party), I defined UNIX_SCIP_DIR and pointed to a directory that contains three other directories (bin, include, lib). These three directories are the same as the SCIP directories provided in the binary distribution of SCIP for CentOS 7, only that they are the result of my source build. or-tools recognizes them without a problem when I do make cc, or make dotnet, ... or-tools  6.10 then builds without any errors (I do make all it reports successful build of all versions.) By the way, I needed to install SWIG from source, latest version. The default version in the CentOS distribution is too old for or-tools 6.10. 

The problem I found appeared when I ran: make test_cc USE_SCIP. This compiles all the tests, including the linear programming and the integer programming. Those run fine with CBC/CBL, but failed when attempting to run with SCIP with the above error. The test_cc, I believe, is equivalent to running the command you suggest above for the individual integer_programming case. I have not ran that one but I could try it.  Is this an issue with dynamic libraries (shared libraries?) The error resport, and since the error is reported at the point of trying to use SCIP/SOPLEX, it appears that it is trying to load the shared library at that point and is not finding it. Does that make sense?

**Comment by GIrisarri** [comment]
@Mizux. Thanks again for the information provided above. I managed to resolve the issue. It appears that google-or builds on Linux (CentOS 7 in my case) use the static libraries (libscip.a, ...) Therefore, I built scip-6.0.1 from source and got the static library for scip. With that, and a rebuild or google-or tools, then all the tests (make test_cc) run and the SCIP solver is used as expected.

Notice that SCIP binaries, however, are not distributed using the static libraries (only shared libraries). Therefore, any one who runs into the same issue will need to build scip from source and expect that the static build is done. Then is a matter of putting the library in the directory pointed to by UNIX_SCIP_DIR.

**Comment by Mizux** [comment]
@GIrisarri we decide to go for the static one since it easier for us to expect a correct package in python and nuget or Java wrapper otherwise we need to deal with keeping the shared library in archive etc...

Last time I tested was SCIP 6.0.0 and CMakeLists.txt and Makefile were both half broken (see patch they provide as emergency fix).
IIRC shared library didn't work on MacOS because they didn't correctly set RPATH and/or PIC in CMAke configuration -> I choose to go for the "working on all platform (more or less)" static library.

I'll try to give a try for the v7.1 to SCIP 6.0.1 see if things are better now (and I should have send a email to SCIP team, too sad they don't have an github mirror with issue tracker :( )
