### ISSUE TITLE
Provide separate Examples NuGet Packaging

### ISSUE THREAD

**Issue by mwpowellhtx** [google/or-tools#760]
Hello, I think this would be helpful to accelerate delivery of especially prerelease, RC, if not production, bits, especially with and taking nothing away from the the breadth of helpful illustrative examples. For instance, ``google.ortools.examples.$(semver).nupkg``, with appropriate dependencies on the ``google.ortools.$(semver).nupkg``. For instance if we could draw from those RCs from, say, an AppVeyor style staging area. Thanks!

**Comment by Mizux** [comment]
I agree UnitTest and Examples shouldn't be part of the Google.OrTools.nupkg.

However, since usually for examples you want the source code to study them, I prefer to deliver them as an archive (better will be to have a separate repo like https://github.com/Microsoft/dotnet-samples) where all example are provided with a .csproj and depend on Google.OrTools package.

note: Need to leverage on the use of [DEVPATH](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-locate-assemblies-by-using-devpath)

**Comment by mwpowellhtx** [comment]
@Mizux :+1: Even better.

**Comment by Mizux** [comment]
Since the dotnet refactor:

* `make dotnet` **won't** build examples, sat_samples, unit tests...
  * Google.OrTools.nupkg doesn't contains/depends on examples... 
* `make test_dotnet` depends on `test_dotnet_samples` (40s) `test_dotnet_csharp` `test_dotnet_fsharp` and `test_dotnet_examples` (480s)
* examples/test use a `PackageReference` on `Google.OrTools` and set `<RestoreSources>../../packages;...` to use the source package when building
  * note: `ProjectReference` doesn't work since Google.OrTools is a meta-package

**Comment by mwpowellhtx** [comment]
@Mizux To be clear, the base package should not depend on ***anything*** examples. The references would be hopelessly circular then. I think that's what you are driving at here, but I just wanted to clarify.

Otherwise, looking forward to at least test driving a pre-release package source. If not an official NuGet release.

**Comment by mwpowellhtx** [comment]
@Mizux Just following up; if we can see the evaluation or beta packages land in a permanent or semi-permanent package source, that would be best, I think. I think Appveyor may support at least a limited life cycle availability, for instance. I can just add that among my package sources for evaluation purposes. Thanks again!
