### ISSUE TITLE
Bad link to Debian-9 binary in installation guide

### ISSUE THREAD

**Issue by udalrich** [google/or-tools#763]
The link on 
https://developers.google.com/optimization/introduction/installing/binary to the debian version is for Debian 9.3, but only the Debian 9.4 version appears to be available.

**Comment by Mizux** [comment]
Hi,

Currently we are targeting Debian-9 since it is the last stable version.
Optimization site, installation will be updated soon (with a better layout IMHO) feel free to post any feedback.
> stable - The current stable release (Stretch).

note: Stretch is the Debian-9
src: https://wiki.debian.org/DebianReleases#Current_Releases.2FRepositories

And we follow the last update
> 2017-12-09: Updated (9.3) (press release)
> 2018-03-10: Updated (9.4) (press release)

src: https://wiki.debian.org/DebianStretch#Release_and_updates

Is it possible for you to update your machine ?

**Comment by Mizux** [comment]
Link should be fixed now cf https://developers.google.com/optimization/install/download
