### ISSUE TITLE
Pickup, Drop, Pickup 

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#783]
Hello,
Can we constrain three Nodes to be served in order, and by the same vehicle?
E.g.
Add PickDrop(A,B)
Add PickDrop(B,C)

B participates in both conditions,  but it could look like B is visited twice...

**Comment by Mizux** [comment]
Hi,
yes and no:
* I think it's ok to have a node part of different PickDrop, otherwise you can split B in `B` and `B'` with zero distance from each other etc...
* internally solver can only visit once each node (it maintain a list of next node for each node which can't contains several nodes). i.e. we cannot also half (un)load a node etc...

```python
A = routing.NodeToIndex(A_Index)
B = routing.NodeToIndex(B_Index)
C = routing.NodeToIndex(C_Index)
routing.AddPickupAndDelivery(A, B)
routing.AddPickupAndDelivery(B, C)
routing.solver().Add(routing.CumulVar(A, "distance") <= routing.CumulVar(B, "distance"))
routing.solver().Add(routing.CumulVar(B, "distance") <= routing.CumulVar(C, "distance"))
routing.solver().Add(routing.VehicleVar(A) == routing.VehicleVar(B))
routing.solver().Add(routing.VehicleVar(B) == routing.VehicleVar(C))
```

**Comment by GuyBenhaim** [comment]
Thx.
Will check.

**Comment by GuyBenhaim** [comment]
As Node B is a drop point, this scheme cannot account for vehicle capacity due to the added volume picked up at B - as there can't also be an additional 'visit' for pickup at Node B.

So probably need to add a Node, or maybe assign 0 volume for the first drop and 0 for the second pickup so both do not account ...

**Comment by GuyBenhaim** [comment]
Is there a way to force the 2nd pickup by another vehicle? (guessing: yes)
Is there a way to dictate the visiting order dependency (between two separate routes), or only in case we dictate an absolute time-window for the 1st drop?

**Comment by jmarca** [comment]
Just commenting here based on my experience.  If B is both a pickup and a dropoff node, you absolutely have to split it into two nodes, for example, B1 and B2

A -> B1
B2 -> C

Alternately, if you have a pickup at A that needs some delivered to B and some delivered to C, you'll have to split A

A1 -> B
A2 -> C

In your distance callback, you can provide zero travel time between A1, A2, and/or B1, B2, and the model does the right thing.  You can also force B to come before C in any number of ways.  Time windows work, but you can also require that the "distance" or "time" or whatever for the cumulative value at B1 be greater or less than B2, as in 

```
    time_dimension = routing.GetDimensionOrDie("Time")
    ...
    solver.AddConstraint(
        time_dimension.CumulVar(B1) <= time_dimension.CumulVar(B2)
    )
```

I've also managed to add conditional constraints.  For example, if you want to force that B2 always immediately follows B1 if A->B1 and B2->C are served by the same vehicle, then you might be able to do something like:

```
next_node_constraint = routing.NextVar(B1) == B2
same_vehicle_condition = routing.VehicleVar(B1) == routing.VehicleVar(B2)

expression = solver.ConditionalExpression(same_vehicle_condition,
                                          next_node_constraint,
                                          1)
solver.AddConstraint(
    expression >= 1
)
```

(although I haven't actually ever *tried* to use the `NextVar(B1)==B2` type thing as a constraint...I've only ever used it as a condition (the first argument in that ConditionalExpression call.)

Similarly, if you want to make sure that when using different vehicles, B1 is delivered before B2 is picked up, then you could flip the same_vehicle_condition to be different_vehicle_condition, and replace the next_node_constraint with something like a time constraint (time at B1 is less than time at B2)

(Hope that helps, sorry if it's just noise)

**Comment by GuyBenhaim** [comment]
Helpful thanks!  (not noise)

I guess that the callback for ArcCost between the split Node (E.g. B split to B1 and B2) should return 0, but the time or distance callback **should return a value**, so we can apply the constraint. Correct?

Can you please explain a bit more re **Solver.ConditionalExpression**?
This one:  IntExpr* Solver::MakeConditionalExpression(IntVar* const condition,  IntExpr* const expr, int64 unperformed_value)    ?

Finally, for using two vehicles, is that possible to constrain on a cumulative value (e.g. over Distance dimension) **across two differen**t vehicles/routes? If so, how?

Guy

**Comment by Mizux** [comment]
I guess @jmarca  means you can use
```python
routing.solver().Add(routing.VehicleVar(A) != routing.VehicleVar(B))
```
if you want a **different** vehicle for A and B.

Also each node as a CumulVar variable for each Dimension and solver doesn't take into account the route when comparing CumulVar, it only check there is no constraint violation each it try to find a successor of a node...
That's why for pickup & delivery usually you need two constraints
`CumulVar(A) <= CumulVar(B)` (i.e. time/distance precedence) and `VehicleVar(A) == VehicleVar(B)` (i.e. same route)

**Comment by jmarca** [comment]
@GuyBenhaim  Sorry, `expression = solver.ConditionalExpression(...)` is the python binding for ` IntExpr* Solver::MakeConditionalExpression(IntVar* const condition, IntExpr* const expr, int64 unperformed_value)`, as you can see from [this file](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/python/constraint_solver.i#L791)

@Mizux I was just trying to note that you can add conditional constraints that depend on certain conditions.  

Assuming the solver assigns the same vehicle to both pickups, it might just work out that the sequencing is correct, perhaps due to time windows, etc.  However, in my experience, if you assume things will just work out and then they don't, you'll have problems!

So what I was saying was if you want to make *sure* that "If vehicle 1 serves both B1 dropoff and B2 pickup, then B2 pickup follows immediately after B1 dropoff", then you can put that into a conditional constraint.

Another possible use case for conditional constraints is to constrain delivery times if the vehicles are different.  For example, maybe the solver can assign one vehicle to A -> B1, and then another vehicle to B2 -> C.  If the dropoff load at B1 is needed for the pickup load at B2 (say this is a break-bulk depot), then you'd have to be explicit that "if the vehicles are different, make sure that B1 gets delivered before B2 is picked up".  So then your conditional expression can be 

```
different_vehicle = routing.VehicleVar(A) != routing.VehicleVar(B)
time_constraint = time_dimension.CumulVar(B1) < time_dimension.CumulVar(B2)
expression = solver.ConditionalExpression(different_vehicle,
                                          time_constraint,
                                          1)
solver.AddConstraint(
    expression >= 1
)
```

Of course this is a tortured example, and simply requiring the basic time constraint that B1 < B2 is probably cleaner, but there may be cases where business logic requires a conditional constraint, and I had a difficult time figuring out how these work.
