### ISSUE TITLE
Start/End Nodes indexing:  input and solution

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#794]
The list of locations includes first the orders, indexed by 0 .. (#Orders-1) and then each vehicle's start point and   then its endpoint, followed by stat and end of the next vehicle, etc

In the solution seems that start and end Nodes are counted differently:
![image](https://user-images.githubusercontent.com/20749469/43839703-6e5e405a-9b27-11e8-90ac-f7e386fc8009.png)

Can you please clarify how to keep these consistent, so we do not mis-interpret Nodes

**Comment by Mizux** [comment]
Internally solver use "index" and generate a start and end index for each vehicle.
On the other side "you" use NodeIndex so when solver provide you some index you need to convert them to NodeIndex etc...
node: since several vehicle can start from the depot the NodeIndexToIndex(depot) is not defined (i.e. undefined behaviour) for the depot (and end) you must use `Start(<vehicle_id>)` and `End(<vehicle_id>)` respectively.

try to look at:
https://github.com/google/or-tools/blob/master/examples/python/vrp.py#L118
https://github.com/google/or-tools/blob/master/examples/python/vrp.py#L122

Related to #708 #717
