### ISSUE TITLE
Python example of pickup and delivery with time window

### ISSUE THREAD

**Issue by Westlife1002** [google/or-tools#807]
Hi, 

I am wondering if there is a python example for me to study how to implement both pickup and delivery with time window. I saw one example here but it's written in java which is difficult for me to get through.

My problem is to ask the model run the delivery scheduling in the morning (e.g. 8.00 - 12:00), starting from the warehouse), then run another backhaul pick up scheduling using the same group of trucks in the afternoon (12:00 - 18:00, starting from the end point of the morning delivery of each truck and then back to the warehouse). the model has to take into account the required time window for each pickup/delivery and truck capacity limit.

I already have a working model for delivery only. Is there an easy way to add the pick based on current model.

**Comment by Mizux** [comment]
Unfortunately not yet.

For break please read #569 i.e. break is currently not working well

**Comment by Westlife1002** [comment]
Is there a built-in functionality allowing me to model the above scenario? Alternatively I could think of running the model twice with the first time as delivery and the second time as pickup by taking the routing result from the first time to form a complete loop for every truck. Also, I would like to know a few configurations:

1). before running the second model (afternoon pickup on the way back to warehouse), how to setup the starting points of each truck be the same as the ending points of morning delivery. 

2). can we make the truck load_var (CumulVar) descending along the way to zero in the morning delivery, then increment again for the pickup loads along the way back to warehouse?

**Comment by jmarca** [comment]
I had no problem remixing the python ["cvrptw_plot"](https://github.com/google/or-tools/blob/master/examples/python/cvrptw_plot.py) example with the C++ ["pdptw.cc"](https://github.com/google/or-tools/blob/master/examples/cpp/pdptw.cc) example.  I also used the breaks example given in the documentation to implement per-vehicle breaks.  So it is totally possible to model your scenario in one run---no need to split the run into two---but you'll have to do most of the work yourself to implement the constraints for your particular use case.

One thing to keep in mind is that each pickup and delivery should be a unique node.  I call them "events" in my code, which I think is the right way to approach it.  If you model each point based on coordinates or something you're going to have troubles.

**Comment by bcoghe** [comment]
@jmarca, Did you implement the breaks with MakeFixedDurationIntervalVar? Do you have some example code? Would be greatly appreciated!

Another more general question (@Mizux ), is there a way to optimize the time window of your break within your routes (following some constraints). 
For example: Vehicles should not drive 4 h continually but have a 15 min break. It might be more ideal to have that break after 2 hours instead of after 4h in some cases so would be nice if the optimizer could take this into account.

**Comment by jmarca** [comment]
I did add breaks, pretty much copy and paste the examples to start, then modify for python/my case.

Original is here https://github.com/google/or-tools/blob/master/examples/cpp/cvrptw_with_breaks.cc, starting at about line 132.  I did not need two break options, just one break roughly halfway through the vehicle's shift.

So here is how I translated that C++ to Python originally (from the first commit that says "breaks are working")

``` python
print("Schedule break times")
# break time scheduling
# first cut, just hard code things, copying C++ example
break_data = [
    {'start_min':11, 'start_max':13, 'duration':2400}
    # ,{'start_min':10, 'start_max':15, 'duration':1800}
    # ,{'start_min':10, 'start_max':15, 'duration':1800}
]

for vnum in range(vehicles.number):
    veh = vehicles.veh_input.loc[vnum]
    breaks = [None]*len(break_data)
    for  bidx in range(len(break_data)):
        label = ' '.join(["Break", str(bidx), "on vehicle", veh.id])
        break_interval = solver.FixedDurationIntervalVar(
            break_data[bidx]['start_min'] * 3600,
            break_data[bidx]['start_max'] * 3600,
            break_data[bidx]['duration'],
            True,
            label
        )
        bip = break_interval.MustBePerformed()
        # print (bip)
        # print(break_interval)
        breaks[bidx] = break_interval

    solver.AddConstraint(
        breaks[0].PerformedExpr() == 1
    )

    # # break1 performed iff break2 performed
    # solver.AddConstraint(
    #     breaks[1].PerformedExpr() == breaks[2].PerformedExpr()
    # )
    # # break2 start 1h after break1.
    # solver.AddConstraint(
    #     solver->MakeIntervalVarRelationWithDelay(
    #    breaks[2], operations_research::Solver::STARTS_AFTER_END, breaks[1],
    #    3600));
    # break0 performed iff break2 unperformed
    # solver->AddConstraint(solver->MakeNonEquality(breaks[0]->PerformedExpr(),
    #                                               breaks[2]->PerformedExpr()));
    #solver.AddConstraint(
    # breaks[0].MustBePerformed()
    #)

    # print("set breaks ",breaks," for vehicle ", vnum)
    time_dimension.SetBreakIntervalsOfVehicle(breaks, int(vnum));

```

As I recall, the print statements were very helpful, as you could see the breaks being required to be performed, etc.

(I do this kind of stuff for a living, so if you want to hire me, I'd be happy to help more!)

**Comment by makaveli10** [comment]
@jmarca do I need to port the pdptw.cc into python if I have constraints on both pick up and delivery time windows ?

**Comment by jmarca** [comment]
@makaveli10 not sure what you are asking.  Sure, port it to python.  Or start fresh and write your own.  Constraints on time windows for pickup and delivery nodes are possible whether you port the pdptw.cc or not.

Typically, I just do a loop over all nodes, and set time windows.  I don't care what kind of node it is.

**Comment by makaveli10** [comment]
@jmarca yeah you decoded my question correctly though. 
So, I have multiple nodes to pick up from with a time window and a single node to deliver to that is depot. So my question is how to impose time window constraint both on pickup and delivery ?

**Comment by jmarca** [comment]
I typically do something like this:

if you have a node i with a time window, then the service time has to be inside that window, right?

So assuming you have a "time dimension", and a function that, given a node, returns the minimum and maximum service time, you do:

```python
time_dimension = routing.GetDimensionOrDie(time_dimension_name)
for node in nodes:
    index = manager.NodeToIndex(node)
    (min,max) = get_time_window(node)
    time_dimension.CumulVar(index).SetRange(min,max)

The set range call means that the cumulative value (time) at a node cannot be less than or greater than (min,max).  This holds for both pickup and delivery nodes.

If this is a strict pickup and delivery problem, you'll also need to create one dummy delivery node paired with each pickup.  If you just want the vehicle to do all the pickups and get back to the depot before time is up, then that shouldn't matter.  

Finally, don't forget you'll need disjunctions on all pickup nodes  (and dummy delivery nodes, if you have them) in order to drop nodes, if you expect that some will fall outside of the time window.  However, you can't include the depot node(s) in the disjunction, because that doesn't make sense...you can't drop the depot.

hope that helps

**Comment by makaveli10** [comment]
@jmarca I appreciate your efforts. Yes this is helpful but the only issue I am facing now is that all the orders are to be delivered to the depot itself with a delivery time window constraint. And as soon as I give depot as delivery node the algorithm fails to output. Hope to get some help.

**Comment by jmarca** [comment]
I'm not sure what you mean by "give depot as delivery node", so I'm guessing here.  If you mean for each pickup you are using the pickup and delivery code to link the depot with the pickup, yes that will fail.  You can only visit a node once.  If all your pickups are assigned a delivery at the depot by code like:

```python
for pickup_index in pickups:
    # this will fail.  Don't do this
    routing.AddPickupAndDelivery(pickup_index,depot_index)
```

Then the solver might get confused because only one visit to the depot is allowed, but you are pairing it with every pickup.  

I think the minimum possible solution for your case (again, guessing because I haven't seen any code) is one dummy delivery node per vehicle.  Same "location" as depot, (distance is calculated to all nodes as if it is the depot) but it is *not* the depot, it is a regular node that is zero distance away from the depot.  One per vehicle so that all vehicles can "deliver" their items before returning to the depot.  In that case, I would try to solve it *without* using the call to `AddPickupAndDelivery`, instead just doing the pickups as a usual routing model with the addition of the dummy depot nodes.

Depending on what you are doing, you might need to pair dummy delivery nodes with each pickup node, and turn it into a full pickup and delivery problem.  This simplifies thinking about it, but adds to the complexity of the problem the solver has to tackle (which means longer solution time).

**Comment by makaveli10** [comment]
Thanks for the explanation. Sorry for having naive doubts, if you pair dummy delivery nodes with each pickup node, and add time window constraint to both pickup and delivery nodes how would you solve it without 
`for pickup_index,dummy_delivery_index in pickups_delivery:
       routing.AddPickupAndDelivery(pickup_index,depot_index)`

**Comment by jmarca** [comment]
Sorry, I'm explaining too many things at once.

If you *are* going to make a dummy delivery node for every pickup node, then it is fine to call the add pickup and delivery function.

If you aren't, then I'd avoid it.

Also, the solver doesn't really "know" anything, except what you tell it.  

So if you want to make sure a pickup at A is delivered to B, you need to set constraints appropriately---make sure the same vehicle serves both A and B, and make sure that node A is served before node B.  I *believe* (I could be wrong) that the call to `AddPickupAndDelivery(a,b)` is just a hint to the solver.  It does *not* take the place of setting the same vehicle constraint and the precedence constraint.  Note that all three are called in the example: https://developers.google.com/optimization/routing/pickup_delivery#define_pickup_and_delivery_requests

So, if you just want all of the pickups to be delivered to a single dummy node inside of the dummy node's time window, you can probably just set the same vehicle and precedence constraints for the dummy node and the pickup nodes.  

If you are taking the step of creating a unique dummy node for each pickup node, then of course call the `AddPickupAndDelivery()` call so that the solver gets its pickup and delivery help.

But again, I'm explaining possible alternative approaches without any clue what you are actually doing, so I'm probably confusing you

**Comment by makaveli10** [comment]
@jmarca Thanks for your help.

**Comment by lperron** [comment]
Indeed. Thanks

**Comment by Raf1001** [comment]
Hi all, I'm a newbie to Python and am trying to solve a similar problem.
So am trying to also add time window constraints with pickup and deliveries.
I have  a pickup location with a pickup time window and then a delivery location with a delivery time window and have x number of drivers available, no specific starting location (no depot) so it  can just be the first pickup location of each calculated route.

I would much appreciate a relatively simplified guide as how to best approach this, I read above about having each pickup/delivery as a single node but didn't quite understand this.

Would it be best to use the Python OR pick-up delivery example and work from that to try add the time window constraints?

Many thanks for your help in advance!!! :)
