### ISSUE TITLE
Missing namespace Google.OrTools in nuget 6.9.5841 

### ISSUE THREAD

**Issue by kivantos** [google/or-tools#882]
After updating to version 6.9.5841, the namespace `Google.OrTools` cannot be found. Is this intended?

**Comment by Mizux** [comment]
Hi, could you be more precise ?

currently `example/dotnet/*.cs` still use:
```cs
using Google.OrTools.ConstraintSolver;
....
RoutingModel routing = new RoutingModel(...
```
src: https://github.com/google/or-tools/blob/master/examples/dotnet/tsp.cs#L16

**Comment by Mizux** [comment]
We don't have any `RootNamespace` in csproj is it what are you looking for ?
Do you know why we need it ? What change with/without it ?

https://github.com/google/or-tools/blob/6a177338f944e09edd007cfddf814bb930454095/ortools/dotnet/Google.OrTools/Google.OrTools.csproj.in#L6-L9

**Comment by kivantos** [comment]
I was using nuget version 6.7.4973 before, everything worked fine. When I update to nuget version 6.9.5841, the following code does not compile anymore:

```csharp
using Google.OrTools.ConstraintSolver;

namespace ModelToolbox
{
    public interface IModel
    {
        Solver Solver { get; }
        void AddToSolver();
    }
}
```

![grafik](https://user-images.githubusercontent.com/4759262/46793669-9837d200-cd46-11e8-9177-3ee5660ce895.png)

**Comment by Mizux** [comment]
you have to use `targetFramework="netstandard2.0"`

**Comment by Mizux** [comment]
Since "Google.Or"-Tools is a **native** multi-(os)platform multi packages you may be interested by:
[Additions to the csproj format for .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
[Package references (PackageReference) in project files](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
And last but not the least
[Or-Tools .Net build dev note documentation](https://github.com/google/or-tools/blob/master/ortools/dotnet/README.md)
