### ISSUE TITLE
What happened to .NET ConstraintSolver CpModelLoader.IntegerExpressionByName

### ISSUE THREAD

**Issue by mwpowellhtx** [google/or-tools#905]
It's been a little while since I last worked with this one at all. There used to be a ``CpModelLoader.IntegerExpressionByName``. Where did it go?

**Comment by lperron** [comment]
I did not touch the constraint solver code, so I do not know.

Please note that all the CP part, especially the model loading part is
completely subsumed by the CP-SAT solver.
Furthermore, for non routing problems, the CP-SAT is much faster that the
original CP solver. So I highly recommend switching to the new solver.

Finally, the original CP solver has been in maintenance mode for more than
2 years now, while the CP-SAT solver is under heavy development.

For a quick intro to the CP-SAT solver, please read
https://github.com/google/or-tools/blob/master/ortools/sat/doc/index.md.

Next release is 6.10, it will be a minor release with few bug fixes, like
parallelism for the CP-SAT solver on windows.

End of November, we should release 7.0, this version will feature a much
improved routing library (more robust first solution strategies, much
better break managements, simple dimension API...).

But:
  - It will break source compatibility, although the migration is not that
complex.
  - I will start trimming down the original CP solver. In particular, I
will remove the CpModelLoad, as I said, because it it subsumed by the
CP-SAT solver in very way possible, I will also remove no-goods, the
connection with the simplex solver (which never worked really with this
solver, while it is an integral part of the CP-SAT solver). I will continue
to remove all experimental parts of the code that never really worked. For
instance, when we implement symmetry breaking in the CP-SAT solver, I will
likely remove that from the original CP solver.

--Laurent

PS: The new routing is visible in the abseil branch on github. All routing
examples have been ported.


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 25 oct. 2018 à 21:25, Michael W Powell <notifications@github.com> a
écrit :

**Comment by mwpowellhtx** [comment]
@lperron Sounds like my timing is about right then, pulling my own wrappers forward, sorting the bits out, then strategizing around CP-SAT activities.

**Comment by mwpowellhtx** [comment]
I'm not sure if I had done my own extension method, but this is the approach I am taking at the moment, i.e.:

```C#
internal static IntExpr IntegerExpressionByName(this CpModelLoader loader, string expressionName);
```

**Comment by Mizux** [comment]
My 2 cents,
I can't found any `IntegerExpressionByName()` in any OrTools release.

```shell
 %git tag | xargs git grep "CpModelLoader::IntegerExpression"
v2016-04:src/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v2016-06:src/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v4.2:src/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v4.3:src/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v4.4:src/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v5.0:src/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v5.1:src/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v6.0:ortools/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v6.1:ortools/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v6.2:ortools/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v6.3:ortools/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v6.4:ortools/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v6.5:ortools/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v6.6:ortools/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v6.7:ortools/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v6.7.1:ortools/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v6.7.2:ortools/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v6.8:ortools/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v6.9:ortools/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
v6.9.1:ortools/constraint_solver/io.cc:IntExpr* CpModelLoader::IntegerExpression(int index) const {
```

**Comment by mwpowellhtx** [comment]
:+1: Thanks for the feedback. No worries.
