### ISSUE TITLE
Is there some articles or other materials about the detail of the tools implementation？

### ISSUE THREAD

**Issue by Liu-Ming-De** [google/or-tools#920]
I want know the algorithm in VRP,  Is there some articles or other materials about the detail of the tool implementation？

**Comment by Mizux** [comment]
Not I'm aware off.
You can look at the source code: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.cc
node: I would recommend a good IDE (i.e. with good code completion) to navigate through the source code.

Otherwise you can find [here](https://devsite.googleplex.com/optimization/routing/routing_options#first-solution-strategy-options) reference to which methods are currently in use...

**Comment by Mizux** [comment]
You can found few papers in the link above according the "First Solution Strategy" you use

**Comment by lperron** [comment]
This is local search and meta-heuristics on top of a Constraint Programming
solver.

Unfortunately, we have not published anything. The ideas are well described
in the following paper:
https://www.researchgate.net/publication/226021015_A_Constraint_Programming_Toolkit_for_Local_Search

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
The CP-SAT solver uses a lazy clause generation solver on top of an SAT solver. The best description is a presentation from Peter Stuckey called [Search is Dead](https://people.eng.unimelb.edu.au/pstuckey/PPDP2013.pdf)

**Comment by Mizux** [comment]
https://github.com/or-tools/awesome_or-tools
