### ISSUE TITLE
CVRPTW continuous route with penalties

### ISSUE THREAD

**Issue by piv199** [google/or-tools#924]
Hi, I have specific interpretation of time dimension and I can't understand how to model it using or-tools.

In my cvrptw problem vehicle can arrive earlier than customers Time Window begins then vehicle waits until customer opens and serves him. On the other hand, if vehicle arrives after customer TW begins, the vehicle serves customer immediately. Any time spent by vehicle before time window should be penalized by penaltyWaitCoeff, after time window - penaltyLateCoeff.

So, for example
```
Departure(A) = 0
Time(AB) = 2000
TW(B) = 2900...3600
ServiceTime(B) = 300

VehicleWaitPenalty(AB) = max(TW(B).start -  Departure(A) + Time(AB), 0) * penaltyWaitCoeff
Departure(B) = max(TW(B).start, Departure(A) + Time(AB)) + ServiceTime(B)
VehicleLatePenalty(AB) = max(Departure(B) - TW(B).end, 0) * penaltyLateCoeff
```

Setting penalties is obviously done by 

```
dimension->SetCumulVarSoftLowerBound(model->IndexToNode(i), timeWindow->Begin(), timeWindow->PenaltyWait());
dimension->SetCumulVarSoftUpperBound(model->IndexToNode(i), timeWindow->End(), timeWindow->PenaltyLate());
```

But in this case if vehicle arrives earlier, it doesn't wait until TW of the customer starts. 
I tried to add 
```
dimension->CumulVar(i)->SetRange(timeWindow->Begin(), timeWindow->End());
IntVar * slackVar = dimension->SlackVar(i);
slackVar->SetMax(24 * 3600);
model->AddToAssignment(slackVar);
```

But it still not produces right results as far as I understand. Slack var is not penalized. The vehicle can arrive in TW but departure at

```
Departure(B) = max(TW(B).start, Departure(A) + Time(AB)) + ServiceTime(B) + SomeSlack
```

What can I do to model this type of problem?

P.S. In my current model ResultCallback2 for time dimension calculated as ServiceTime(A)  + Time(AB)

**Comment by Mizux** [comment]
My 2cents, 

I would say in your example TW are Arrival TW and the constraint is:
```
Transit(AB) = ServiceTime(A) + Time(AB)
Arrival(B) = Arrival(A) + Transit(AB) + Slack(A)
```
src: [here](https://github.com/google/or-tools/blob/eefaaeba86a7eeeeee7ec272f3f91b7e2275b170/ortools/constraint_solver/routing.h#L383)
note: `CumulVar(A) == Arrival(A)` and `Transit(AB)` is the "ResultCallBack2" i.e. transit in the comment

So It means Slack(A) could be use to target Arrival(B) TW and add a waiting time when possible.
Since the Slack Value is added to the CumulVar which can be added to the objective Cost. (see [Span cost](https://github.com/google/or-tools/blob/eefaaeba86a7eeeeee7ec272f3f91b7e2275b170/ortools/constraint_solver/routing.h#L1412-L1419)) 

On the other hand when using a SoftLowerBound you allow to **serve** earlier and paying the penalty cost BUT what you want to model is arrive earlier **and** wait for the TW (that's how Slack should be use IMHO). So I would not use the SoftLowerBound but the slackVar to modelize waiting time when you arrive to ealier.

I will keep the SoftUpperBound to modelize the tardiness. i.e. when late pay the penalty cost.

**Comment by piv199** [comment]
@Mizux Hi,
Thanks for your response

In my code now I have:

        int64 kHorizon = 24*3600;
        vector<int64> *maxWorkingTimes = new vector<int64>();
        for (int v = 0; v < (int)vehicles->size(); v++) {
            Vehicle *vehicle = vehicles->at(v);
            TimeWindow *timeWindow = vehicle->WorkingTimeWindow();
            maxWorkingTimes->push_back(timeWindow->End());
        }
        model->AddDimensionWithVehicleTransitAndCapacity(*times, kHorizon, *maxWorkingTimes, false, "Time");
        RoutingDimension *dimension = model->GetMutableDimension("Time");
        for (int i = 1; i < (int)customers->size(); i++) {
            Customer *customer = customers->at(i);
            TimeWindow *timeWindow = customer->TimeWindow();
            dimension->CumulVar(i)->SetRange(timeWindow->Begin(), kHorizon);
            IntVar * slackVar = dimension->SlackVar(i);
            slackVar->SetMax(kHorizon);
            model->AddToAssignment(slackVar);
            dimension->SetCumulVarSoftUpperBound(model->IndexToNode(i), timeWindow->End(), timeWindow->PenaltyLate());
        }
        for (int v = 0; v < (int)vehicles->size(); v++) {
            Vehicle *vehicle = vehicles->at(v);
            TimeWindow *timeWindow = vehicle->WorkingTimeWindow();
            int64 startPointIndex = model->Start(v);
            dimension->CumulVar(startPointIndex)->SetValue(timeWindow->Begin())
        }


I set customer availability from TW.begin to kHorizon (end of the whole day), so it could be visited after it's TW.end. I left SetCumulVarSoftUpperBound to penalize late for serving customer. I set min and max values for each vehicle. 

This code finds a suitable solution, but it's not so good as I expected, as was obtained earlier... Are there any ways to improve calculation of cost function?
