### ISSUE TITLE
Routing Solver: Vehicle Capacity Configuration

### ISSUE THREAD

**Issue by ConnerWestover** [google/or-tools#947]
I've come across an interesting issue that I can't seem to solve. I'm working in C# and I've modified the cscvrptw.cs to work using pickups and drop-offs. My issue is that each pickup/dropoff can require certain properties on the vehicle (ex: extra large seat or wheelchair capable). Considering that each vehicle has a custom configuration how would I implement this in a vehicle capacity dimension, better yet is there a way in the Run function of a dimension callback to know what's currently on the vehicle?

Here's a slightly more detailed description of the problem I'm trying to solve. 

I have 20 pickup/dropoffs that are wheelchairs and 20 pickup/dropoffs that don't have any need.

Vehicle 1 allows 4 people with any needs
Vehicle 2 allows 3 wheelchairs and 0 others, 2 wheelchairs and 2 others, 1 wheelchair and 4 others, or 5 others.
Vehicle 3 allows 4 wheelchairs and 2 others, 3 wheelchairs and 2 others, 2 wheelchairs and 3 others, 1 wheelchair and 4 others, or 5 others.

How do I ensure the rules for each vehicle are not broken? I appreciate any and all help I receive.

**Comment by Mizux** [comment]
I would create two capacity dimensions i.e. one for wheelchairs and one for others.
Then you'll need to use `AddDimensionDependentDimensionWithVehicleCapacity()` which is not binded in C# see #339.
Also in your case, since you have both dimensions depending on each others it won't work (since dimension builder need pointer to the other dimension at build time).

An other approach would be to find an arithmetic relation between wheelchairs and others to have both in the same capacity dimension.
e.g.
```
wheelchair := 5
other := 3
capacity_v2 := 17
3 * wheelchair = 15 // not full capacity but you can't add others so ok
2 * wheelchair + 2 * others = 2*5 + 2*3 = 16 // not full capacity but you can't add others so ok
1 * wheelchair + 4 * others = 1*5 + 4*3 = 17
5 * others = 15
```
But not sure it is doable here...

**Comment by jmarca** [comment]
I solved exactly this in Python, which also does not have access to `AddDimensionDependentDimensionWithVehicleCapacity()`.  A bit hacky and complicated to describe completely here, but I used an equivalence approach---more or less option 2 above.  If I recall correctly, each vehicle type has an equivalence:  in vehicle A 1 wheelchair = 2 passengers.  In vehicle B, 1 wheelchair = 3 passengers, etc.  Then each vehicle gets a dimension for passengers, wheelchairs, etc etc (there can be multiple dimensions as long as they have some common denominator like passengers...if I remember right, I had an input hash where the key was the common denominator dimension, and the value was another hash of dimensions and equivalents, so here it would be 
```
{'veh1':{ pass: 4, whlchr: 2,... ,'equivalence': {'passenger':{'wheelchair':2, 'large_wheelchair':4}} ...},
 'veh2':{ pass: 6, whlchr: 2,... ,'equivalence': {'passenger':{'wheelchair':3, 'large_wheelchair':3}} ...},}
 ```

Then, the irritant here is that the equivalent capacity that is eaten up by a passenger is a feature of the vehicle, not the passenger.  So a wheelchair has one impact on vehicle 1, and another on vehicle 2.   So my solution is that each vehicle type has its own "fingerprint" in this equivalent dimension, and then each passenger demand can be translated into each vehicle's equivalent dimension.  If a "fingerprint" doesn't apply to a vehicle, then its capacity in that dimension is increased such that it isn't binding (in practice, supply is made equal to the passenger supply plus 10, to be safe).  

So every vehicle has a number of supply dimensions, some of which are non-binding.  Then prior to model run, each passenger has their "demand" value (a single value) expanded into an array, as appropriate.  So a wheelchair would demand:

* 0 passenger seats, 
* 1 wheelchair seat, 
* 2 VehTypeA_equivalent_passengers, 
* 3 VehTypeB_equivalent_passengers

A passenger demand would convert into 

* 1 passenger seats, 
* 0 wheelchair seat, 
* 1 VehTypeA_equivalent_passengers, 
* 1 VehTypeB_equivalent_passengers

one wheelchair and one passenger in vehicle type A would look like:

Load | passengers | wheelchairs | type_A_equivalent | type_B_equivalent 
--------|------------------|-------------|----------------------|----------------------
empty | o o o o  |  o o  |  o o o o  | o o o o o o o o o o o o o o 
1 pass | x o o o | o o | x o o o| x o o o o o o o o o o o o o 
1 whlchr | o o o o | x o | x  x o o | x x x o o o o o o o o o o o
1 p, 1 w | x o o o  | x o | x x x o | x x x x o o o o o o o o o o
3 pass | x x x o  | o o | x x x o | x x x o o o o o o o o o o o

etc.  

In the 1 passenger, 1 wheelchair case, there is still "space" for one more wheelchair and three more passengers in the vanilla dimensions, but the type_A_equivalent will allow just one more passenger, not one more wheelchair, because a wheelchair needs two spaces in the type_A_equivalent dimension. Also note for a type A vehicle, the type_B_equivalent is non-binding no matter who gets on, because some other dimension will always fill up first.

Similarly, in the three passengers case, there is still space for two wheelchairs in the vanilla dimensions, but the type_A_equivalent will only allow one passenger to be loaded and will prevent another wheelchair pickup.

In a type B vehicle you'd see:

one wheelchair and one passenger in vehicle type A would look like:

Load | passengers | wheelchairs | type_A_equivalent | type_B_equivalent 
--------|------------------|-------------|----------------------|----------------------
empty | o o o o o o |  o o  |  o o o o o o o o o o o o o o  | o o o o o o 
1 pass | x o o o o o | o o | x o o o o o o o o o o o o o | x o o o o o 
1 whlchr | o o o o o o | x o | x  x o o o o o o o o o o o o | x x x o o o
1 p, 1 w | x o o o o o | x o | x x x o o o o o o o o o o o | x x x x o o 
3 pass | x x x o o o | o o | x x x o o o o o o o o o o o | x x x o o o

etc.

(and those tables might be wrong, I'm just doing this off the top of my head)

Hope that helps.  Please hit me up with an email if you have more questions.
