### ISSUE TITLE
OR-Tools & SCIP v6

### ISSUE THREAD

**Issue by SpyRefused** [google/or-tools#948]
Hi
I've been trying to compile both SCIP and OR-Tools according to the web guide. As far as I can see, it's pretty loose because most things don't work. My scenario is:
* Ubuntu 18.04,
* SCIP v6,
* OR-Tools,
* OR-Tools Python Wrapper.

I'm using SCIP version 6 and OR-Tools branch. On the one hand SCIP is giving me a lot of problems, but what I haven't managed is to compile a version where you can find the "/include" folder that OR-Tools is going to look for when the "make python" is done. On the other hand, I've tried to do it through the *.deb package, which does include headers and libs, but then the errors are that there are static libs that are not in the package, *.a, then also try to find the file libscipopt.a that has to be generated in a different way... I never just generated what OR-Tools needs from SCIP. The question is that it seems that OR-Tools does not seem compatible with version 6 of SCIP, right?

If so, is there a simpler way to do this? I don't know anything about gcc, c++ and the truth is that it is hard fo me.

Regards.

**Comment by Mizux** [comment]
Here my devnote, I'll try to clean it and keep them up to date...
(note: will be backported to optimization site later)

# SCIP 6.0
## Windows
### Makefile based build
Not available...
### CMake based build
Using git-bash
```
$ cd ~/source/repos/tmp/scipoptsuite-6.0.0
$ cmake -H. -Bbuild -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=plop
$ cmake --build build --target install
```

```
$ make run SOURCE=examples/cpp/binpackging_problem
Error: missing scip.dll
```
Need to copy `scip/bin/scip.dll` to `BIN_DIR` (<ortools_root_dir>/bin/)

## MacOS
### Make based build
$ make GMP=false READLINE=false TPI=tny ZIMPL=false install INSTALLDIR=plop

### CMake based build
Bug when using MACOSX_RPATH -> @rpath/ not used in the library name

## GNU/Linux
### CMake based build
Fail to use since it doesn’t use -fPIC so you can’t link the static lib libscip.a into the shared lib libortools.so ...

$ cmake -H. -Bbuild -DGMP=OFF -DSHARED=OFF 
$ cmake --build build --target install -- DESTDIR=install -j8

Makefile.local:
UNIX_SCIP_DIR=.../scipoptsuite-6.0.0/build/install/usr/local

$ make cc
…
g++ -shared \
 -o lib/libortools.so \
….
/usr/bin/ld: /usr/local/google/home/corentinl/work/scipoptsuite-6.0.0/build/install/usr/local/lib/libscip.a(cons_linear.c.o): relocation R_X86_64_PC32 against symbol `SCIPincludeConshdlrLinear' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
makefiles/Makefile.cpp.mk:160: recipe for target 'lib/libortools.so' failed
make: *** [lib/libortools.so] Error 1

Note: scip provides a `libsoplex-pic.a` but not a `libscip-pic.a`

### Makefile
Need to apply the patch otherwise symmetry won’t be available…
Note: Makefile based build use -fPIC when building static lib scip and soplex

make GMP=false READLINE=false ZIMPL=false TPI=tny USRCFLAGS=-fPIC USRCXXFLAGS=-fPIC USRCPPFLAGS=-fPIC install INSTALLDIR=plop

SCIP_STATIC:

**Comment by SpyRefused** [comment]
@Mizux 

Thank you very much, your indications have been a great help, I also see that the installation guide has also been updated :)

We appreciate very much this help.

Regards.

**Comment by Mizux** [comment]
Please follow #1115 to follow SCIP 6.0.1 integration...

**Comment by rlloretb** [comment]
With "applying the patch", do you mean replacing the files of the patch on the SCIP directory?
It is giving me this error:
clang-5.0: error: no such file or directory: '/Users/didi/Documents/SOFTWARE/scipoptsuite-6.0.0/plop/lib/libsoplex-pic.a'
make: *** [makefiles/Makefile.cpp.mk:177: lib/libortools.dylib] Error 1
