### ISSUE TITLE
One vehicle per Edge

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#987]
Hello,
If we have a pick at point A and a drop at point A', and similarly a pick at point B and a drop at point B'.
In practice, **A and B are at the same location and A' and B' are at another same location and are connected via the one road** (Edge).
 
Using the Routing library, can we constrain such that only **one vehicle** could be driving/present over that road? (In this case, this vehicle could be any vehicle that Solver assigns).
Would that be possible if we constrain the Solver such that a specific vehicle is assigned to serve A and A' and another specific vehicle serves B and B'?

**Comment by GuyBenhaim** [comment]
Hello,
If we have a pick at point A and a drop at point A', and similarly a pick at point B and a drop at point B'.
In practice, **A and B are at the same location and A' and B' are at another same location and are connected via the one road** (Edge).
 
Using the Routing library, can we constrain such that only **one vehicle** could be driving/present over that road? (In this case, this vehicle could be any vehicle that Solver assigns).
Would that be possible if we constrain the Solver such that a specific vehicle is assigned to serve A and A' and another specific vehicle serves B and B'?

**Comment by jmarca** [comment]
```
A         V1             A'
----------------
B           V2           B'
```

You're saying you want V1==V2, right? 

If you just want one vehicle on the link, you already have  VehicleVar(A)==VehicleVar(A') and VehicleVar(B)==VehicleVar(B') because of the same vehicle constraint for PDPTW, so all you have to do is say either VehicleVar(A)==VehicleVar(B) or VehicleVar(A')==VehicleVar(B'). 

(The specific vehicle serving AA' should be the *same* as vehicle serving BB', which is the opposite of what you said, so maybe I'm misunderstanding your question.)

**Comment by lperron** [comment]
Short answer no.

You can still expand the graph to have one node per edge, and a disjunction on all 'paths' using one node of the original graph.

But this would not be practical.
